### ISSUE TITLE
Update the XenServer Tools Upgrade article

### ISSUE THREAD

**Issue by hdansou** [rackerlabs/rackspace-how-to#1007]
The article should instruct about updating the Rackspace Cloud Server Agent to at least 1.3.1.1 and the Xentools to 6.5.

**Comment by hdansou** [comment]
The PR https://github.com/rackerlabs/rackspace-how-to/pull/1006 included all changes.

**Comment by DonNateR** [comment]
Changes transferred to PR #1015
