### ISSUE TITLE
Clarify step 7

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1012]
https://support.rackspace.com/how-to/common-windows-issues-key-management-server-activation/

At step 7 we should probably clarify that “w32tm /resync” and “slmgr.vbs /ato” are 2 distinct commands — if you enter them all on the same line as our article suggests, they won’t work.

Steven Gilmore

**Comment by kylelaffoon** [comment]
Applied change.
