### ISSUE TITLE
Rackspace CDN edge rules - style edit

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-how-to#1018]
@kmsholcomb Could you give this one a thorough editing? There are a TON of notes/warnings/tips and can probably be whittled down.

https://support.rackspace.com/how-to/rackspace-cdn-edge-rules/

**Comment by kmsholcomb** [comment]
Sure thing! That is a lot of notations!!

**Comment by kmsholcomb** [comment]
Sigh. I edited this article a little over a year ago, and if all of my edits had been applied, the article would have been better! (IMHO) I will make it better now!

**Comment by kmsholcomb** [comment]
Hi @stephamon. See the attached edits. Let me know if you have any questions. Thanks!

[Rackspace CDN edge rules_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/297895/Rackspace.CDN.edge.rules_editsKH.pdf)
[Rackspace CDN edge rules_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/297896/Rackspace.CDN.edge.rules_editsKH.docx)

**Comment by stephamon** [comment]
Thanks!
