### ISSUE TITLE
Editorial edits to "Modify your hosts" article

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1033]
As apart of issue #903, this article(https://support.rackspace.com/how-to/modify-your-hosts-file/), needs an editorial review from @kmsholcomb.

**Comment by kmsholcomb** [comment]
I'll look at it today, @DonNateR.

**Comment by kmsholcomb** [comment]
Hi @DonNateR. My suggested edits are in the attached PDF. Please let me know if you have any questions. Thanks! 

[Modify your hosts file_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/301364/Modify.your.hosts.file_editsKH.pdf)
