### ISSUE TITLE
Refresh diagrams in Pillars of the Rackspace monitoring solution

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-how-to#1067]
@DonNateR there are a couple diagrams in here that could use a refresh. I'd cut them out, but the whole article is featured around them, so we either need to redo the diagrams or just delete the whole article.

https://support.rackspace.com/how-to/pillars-of-the-rackspace-monitoring-solution/

**Comment by DonNateR** [comment]
Agree with your assessment. I'll get to these tomorrow.
