### ISSUE TITLE
Audit #12 of top 20 most viewed - "Check Linux file permissions with ls"

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1079]
https://support.rackspace.com/how-to/checking-linux-file-permissions-with-ls/

- [x]  SME check
- [x]  Editor check
- [x]  Update the 'audit_date' and 'last_modified_by' metadata
- [x]  If any changes were made, update the 'last_modified_date' metadata

**Comment by catlook** [comment]
Looks like a SME responded with: Looks good submitted a PR around df -h. I then reviewed and merged PR #1098

**Comment by catlook** [comment]
done
