### ISSUE TITLE
Audit #14 of 20 - "Install Apache and PHP on CentOS 6"

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1080]
https://support.rackspace.com/how-to/centos-6-apache-and-php-install/
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-servers/centos-6-apache-and-php-install.md

- [x]  SME check
- [x]  Editor check
- [x]  Update the 'audit_date' and 'last_modified_by' metadata
- [x]  If any changes were made, update the 'last_modified_date' metadata

**Comment by ReneeRendon** [comment]
#13 of 20 is an Office article and will be audited through Beau's team.

**Comment by catlook** [comment]
done
