### ISSUE TITLE
Audit #11 of top 20 most viewed - "Generate a CSR with OpenSSL"

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1081]
https://support.rackspace.com/how-to/generate-a-csr-with-openssl/

- [x]  SME check
- [x]  Editor check
- [x]  Update the 'audit_date' and 'last_modified_by' metadata
- [x]  If any changes were made, update the 'last_modified_date' metadata

**Comment by kmsholcomb** [comment]
Hi @catlook: I edited the article as it was in https://github.com/rackerlabs/rackspace-how-to/pull/1140. The PDF with my suggestions is attached. Please let me know if you have any questions. Thanks!

[Generate a CSR with OpenSSL_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/332409/Generate.a.CSR.with.OpenSSL_editsKH.pdf)

**Comment by catlook** [comment]
done!
