### ISSUE TITLE
Audit #13 of 20 top viewed articles - "Rackspace Email and Hosted Exchange settings"

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1082]
Beau's team is performing the SME check on all of the Office articles. 
https://support.rackspace.com/how-to/rackspace-email-and-hosted-exchange-settings/

- [x]  SME check
- [x]  Editor check
- [ ]  Update the 'audit_date' and 'last_modified_by' metadata
- [ ]  If any changes were made, update the 'last_modified_date' metadata

**Comment by stephamon** [comment]
@kmsholcomb can you add this one to your list? #1083 too, but I'll tag you on that one as well :)

**Comment by kmsholcomb** [comment]
Will do!

**Comment by kmsholcomb** [comment]
Edits attached, @stephamon. Please let me know if you have any questions. Thanks!

[Rackspace Email and Hosted Exchange settings_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/369853/Rackspace.Email.and.Hosted.Exchange.settings_editsKH.pdf)
[Rackspace Email and Hosted Exchange settings_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/369854/Rackspace.Email.and.Hosted.Exchange.settings_editsKH.docx)
