### ISSUE TITLE
Audit #15 of 20 top viewed articles - "Outlook Web Access (OWA) for Exchange"

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1083]
Beau's team is performing the SME check on all of the Office articles. 
https://support.rackspace.com/how-to/outlook-web-access-owa-for-exchange/

- [x]  SME check
- [x]  Editor check
- [x]  Update the 'audit_date' and 'last_modified_by' metadata
- [x]  If any changes were made, update the 'last_modified_date' metadata

**Comment by stephamon** [comment]
@kmsholcomb this one needs an edit too. Gotta keep you busy since the Zipit ones have been put on hold ;)

**Comment by kmsholcomb** [comment]
Edits attached, @stephamon. Please let me know if you have any questions. Thanks!

[Outlook Web Access for Exchange_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/369855/Outlook.Web.Access.for.Exchange_editsKH.pdf)
[Outlook Web Access for Exchange_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/369856/Outlook.Web.Access.for.Exchange_editsKH.docx)
