### ISSUE TITLE
Update Rackspace Cloud Essentials - CentOS - Configuring a user in vsftpd

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1085]
**We received this comment from Uservoice. This article needs a full audit.**

This page: https://support.rackspace.com/how-to/rackspace-cloud-essentials-centos-configuring-a-user-in-vsftpd/

States: “This article shows you how to create a system user in vstfpd and chrooting (jail – isolation to their home directory) them if necessary.”

But the end of the article has the text “Alright and probably the most important part of this article is the ability to lock a user down to their own home directory so they don’t go around mucking with things they aren’t supposed to.” but the instructions themselves are not actually there.

**Comment by kmsholcomb** [comment]
@kylelaffoon asked me to take a look, and I ended up editing both this article and the one that precedes it (installing vsftpd). My markup is in the attached PDFs. And it does seem like the "configuring" file is missing the instructions for chroot-ing an added user. See my comment about it in that file. Please let me know if you have any questions about the edits. Thanks!

[Rackspace Cloud Essentials-CentOS-Installing vsftpd_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/314516/Rackspace.Cloud.Essentials-CentOS-Installing.vsftpd_editsKH.pdf)
[Rackspace Cloud Essentials-CentOS-Configuring a user in vsftpd_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/314515/Rackspace.Cloud.Essentials-CentOS-Configuring.a.user.in.vsftpd_editsKH.pdf)

**Comment by kylelaffoon** [comment]
Aaron Davis is currently reviewing the options for this.

**Comment by kylelaffoon** [comment]
Aaron Davis updated the verbiage in PR 1104 (https://github.com/rackerlabs/rackspace-how-to/pull/1104). Applied Kelly's edits.

**Comment by kylelaffoon** [comment]
Applied Kelly's edits.
