### ISSUE TITLE
Audit #16 of 20 top viewed articles - Understanding logrotate utility

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1086]
https://support.rackspace.com/how-to/understanding-logrotate-utility/

- [x] SME check
- [x] Editor  check
- [x] Update the 'audit_date' and 'last_modified_by' metadata
- [x] If any changes were made, update the 'last_modified_date' metadata

**Comment by kylelaffoon** [comment]
Per Aaron Davis, "Looks good." Routing to Kelly for edit.

**Comment by kmsholcomb** [comment]
Will do, @kylelaffoon.

**Comment by kmsholcomb** [comment]
Hi @kylelaffoon. My suggested edits are in the attached PDF. Please let me know if you have any questions. Thanks!

[Understanding logrotate utility_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/337399/Understanding.logrotate.utility_editsKH.pdf)
