### ISSUE TITLE
Audit #17 of 20 top viewed articles - Connect to Linux from Windows by using PuTTY

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1087]
https://support.rackspace.com/how-to/connecting-to-linux-from-windows-by-using-putty/

- [x] SME check
- [x] Editor check
- [x] Update the 'audit_date' and 'last_modified_by' metadata
- [x] If any changes were made, update the 'last_modified_date' metadata

**Comment by kylelaffoon** [comment]
Ben Temple confirmed "Still accurate." Routing for Editor check.

**Comment by kmsholcomb** [comment]
Hi @kylelaffoon: My edits, light as they are, are in the attached PDF. Please let me know if you have any questions. Thanks!

[Connect to Linux from Windows by using PuTTY_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/331990/Connect.to.Linux.from.Windows.by.using.PuTTY_editsKH.pdf)

**Comment by kylelaffoon** [comment]
Audit completed.
