### ISSUE TITLE
Audit #18 of 20 top viewed articles - Check DNS Records on Windows with nslookup

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1088]
https://support.rackspace.com/how-to/nslookup-checking-dns-records-on-windows/

- [x] SME check 
- [x] Editor check
- [x] Update the 'audit_date' and 'last_modified_by' metadata
- [x] If any changes were made, update the 'last_modified_date' metadata

**Comment by kylelaffoon** [comment]
Ben Temple confirmed "Still accurate." Routing for Editor check.

**Comment by kmsholcomb** [comment]
Hi @kylelaffoon: Edits are in the attached PDF. Please let me know if you have any questions. Thanks!

[Check DNS Records on Windows with nslookup_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/332244/Check.DNS.Records.on.Windows.with.nslookup_editsKH.pdf)
