### ISSUE TITLE
Audit #20 of 20 top viewed articles - Generate RSA Keys With SSH - PuTTYgen

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1090]
https://support.rackspace.com/how-to/generating-rsa-keys-with-ssh-puttygen/

- [x]  SME check
- [x] Editor check
- [x] Update the 'audit_date' and 'last_modified_by' metadata
- [x] If any changes were made, update the 'last_modified_date' metadata

**Comment by catlook** [comment]
The comment from Ben Temple in the spreadsheet is that this article "is on point"! I checked off SME check.

**Comment by catlook** [comment]
done!
