### ISSUE TITLE
Style edit for Configure Apache on Ubuntu

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-how-to#1110]
Hi @kmsholcomb, this article has been verified by the Servers team as having correct and up-to-date commands, but the article needs your touch, I think.

https://support.rackspace.com/how-to/apache-configuration-on-ubuntu/

The article doesn't say, but this is Apache2 and I don't know which Ubuntu version. I also don't know why in the "Assumptions" section, it says that you need to use `aptitude` to install Apache.

Do you think it would be better to snap Apache2 configuration instructions from the Ubuntu website? (https://help.ubuntu.com/lts/serverguide/httpd.html)

**Comment by kmsholcomb** [comment]
Hi @stephamon. I'm not sure. Given that the article pretty much has nothing to do with Rackspace products or services, per se, it makes me wonder why we have it at all. But, if it is popular, then I guess we are keeping it. I'm not sure what you mean by "snapping" the instructions from the Ubuntu website. I suppose we could link to them. And I have no idea about `aptitude`. I think that's a question for a SME. But, I will edit the article and see if I have any better ideas when I am done. Thanks!

**Comment by stephamon** [comment]
Oops, I meant **snag** not snap. 

It's one of our top viewed articles, as you guessed.

**Comment by kmsholcomb** [comment]
Hi @stephamon. My edits are in the attached PDF. This article is focused on just the site and module settings (enabling and disabling), which are really just a subset of the Apache configuration settings. So, if the commands are correct, I don't think we need to snag anything from the Ubuntu website (although we could certainly refer to it, in a general way, for complete Apache on Ubuntu configuration information). See my comments and edits in the file, and please let me know if you have any questions or further thoughts on revision. Thanks!

[Configure Apache on Ubuntu_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/323977/Configure.Apache.on.Ubuntu_editsKH.pdf)
