### ISSUE TITLE
Rewrite Installing NGINX and PHP-FPM series

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-how-to#1167]
There are 6 of these articles and they're kind of a mess. It'd probably be easier to just start with a new article and pull the important information from the existing articles.

- https://support.rackspace.com/how-to/installing-nginx-and-php-fpm-preface/
- https://support.rackspace.com/how-to/installing-nginx-and-php-fpm-running-on-unix-file-sockets/
- https://support.rackspace.com/how-to/installing-nginx-and-php-fpm-setup-for-nginx/
- https://support.rackspace.com/how-to/installing-nginx-and-php-fpm-setup-for-php-fpm/
- https://support.rackspace.com/how-to/installing-nginx-and-php-fpm-the-fun-begins/
- https://support.rackspace.com/how-to/installing-nginx-and-php-fpm/

**Comment by kmsholcomb** [comment]
Hi @stephamon. I printed out all the articles and read them through (physically printing and highlighting paper copies is the trick to figuring out a content puzzle!). When you cut through the excessive verbiage, the process is pretty straightforward. I mocked up a suggested single article that incorporates what seems relevant from the six articles. I've attached the Word doc I created, a PDF of it, and an MD file (well, I can't attach an MD file, ironically; I will send it to you in Slack). The Word/PDF doc has some comments that are not in the MD file (obviously). 

Let me know how it looks, and if you have any questions. Feel free to change whatever you think needs to be changed; I just wanted to take a first pass at the revision!

[Install NGINX and PHP-FPM_KH.docx](https://github.com/rackerlabs/rackspace-how-to/files/341892/Install.NGINX.and.PHP-FPM_KH.docx)

[Install NGINX and PHP-FPM_KH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/341893/Install.NGINX.and.PHP-FPM_KH.pdf)
