### ISSUE TITLE
Audit Install MySQL server on Ubuntu

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-how-to#1177]
Install MySQL server on Ubuntu was created in 2011 and should probably have the commands checked. At the very least, it should have version numbers added. Also, the tone is pretty conversational.

https://support.rackspace.com/how-to/installing-mysql-server-on-ubuntu/ 

- [x] SME check
- [ ] Editor Check
- [ ] Update the 'audit_date' and 'last_modified_by' metadata
- [ ] If any changes were made, update the 'last_modified_date' metadata

**Comment by kylelaffoon** [comment]
Emailed Aaron Davis and requested SME review of Ubuntu commands listed.

**Comment by kylelaffoon** [comment]
@kmsholcomb Your turn. :)

**Comment by kmsholcomb** [comment]
On it!

**Comment by kmsholcomb** [comment]
Hi @kylelaffoon. My suggested edits are duplicated in the attached PDF/Word docs. This article was very similar to **installing-mysql-server-on-centos.md**, which I edited a couple of weeks ago, so I heavily referenced those edits while making my suggestions. As a result, I decided to make some changes to that other file, via a PR (I always catch more things on a second look). So, in conjunction with this issue and article, you could also review and merge https://github.com/rackerlabs/rackspace-how-to/pull/1205. I'll assign you to it.

Please let me know if you have any questions. Thanks!

[Install a MySQL server on Ubuntu_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/352947/Install.a.MySQL.server.on.Ubuntu_editsKH.docx)
[Install a MySQL server on Ubuntu_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/352946/Install.a.MySQL.server.on.Ubuntu_editsKH.pdf)

**Comment by kylelaffoon** [comment]
Applied edits under https://github.com/rackerlabs/rackspace-how-to/pull/1212.
