### ISSUE TITLE
Cloud Sites Top 10 issues - Migrate a site

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1195]
- Relates to #1165 

- [ ] From  the table that contains all of the URLS for the articles that contain references to the following 10 items: https://one.rackspace.com/display/devdoc/How-To+top+10+list+for+Cloud+Sites add your name next to the topic.
- [ ] Review the articles listed for that topic to identify the pertinent articles.
- [ ] Discuss overlapping issue items with related reviewers.
- [ ] Discuss findings at Milestone 11 sprint meeting.

**Comment by kylelaffoon** [comment]
Three articles needed:

    Debugging in WordPress (Customer App category) Need to build this as an article. Also relates to Site Down Topic (#8 below)
    Site Migration
    Zipit backup utility (2 existing articles)
        https://support.rackspace.com/how-to/zipit-backup-utility-for-cloud-sites-linux/
        https://support.rackspace.com/how-to/zipit-backup-utility-for-cloud-sites-iis/

**Comment by stephamon** [comment]
@DonNateR just FYI, I'm working on issue #1199, which may overlap with this one a bit with the Zipit backup utility articles. #1199 is to do a full audit on those, which I've initiated with Jereme Hancock, who developed the tool.

**Comment by DonNateR** [comment]
@stephamon: I'll remove this from my checklist, since you are handling the audits.

**Comment by kylelaffoon** [comment]
Pausing on this until we discuss list with Linda Rutherford and Thomas Hester.
