### ISSUE TITLE
Cloud Sites Top 10 issues - Zipit Backup Utility

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1199]
- Relates to #1165 

- [ ] From  the table that contains all of the URLS for the articles that contain references to the following 10 items: https://one.rackspace.com/display/devdoc/How-To+top+10+list+for+Cloud+Sites add your name next to the topic.
- [ ] Review the articles listed for that topic to identify the pertinent articles.
- [ ] Discuss overlapping issue items with related reviewers.
- [ ] Discuss findings at Milestone 11 sprint meeting.

**Comment by kylelaffoon** [comment]
urls: 
 - https://support.rackspace.com/how-to/zipit-backup-utility-for-cloud-sites-linux/ 
 - https://support.rackspace.com/how-to/zipit-backup-utility-for-cloud-sites-iis/

Audit both versions.

**Comment by stephamon** [comment]
[] SME check
[] Editor check

**Comment by stephamon** [comment]
Emailed Jereme Hancock, who developed the Zipit tool, today (07/14).

**Comment by stephamon** [comment]
Jereme Hancock confirmed that the Linux article is current, and Matt Costello confirmed for the IIS article. 

@kmsholcomb can you add both of these to your list as well? I don't need them done today or anything :)

**Comment by kmsholcomb** [comment]
I'll add them to my list, @stephamon, and send edits either later today or early next week.

**Comment by kylelaffoon** [comment]
Pausing on this until we discuss list with Linda Rutherford and Thomas Hester.

**Comment by kmsholcomb** [comment]
@stephamon, @kylelaffoon: So, should I wait to edit these?

**Comment by kylelaffoon** [comment]
Anything we had reviewed with Thomas already, let's finish out. But not anything else.

-Kyle

**Comment by kmsholcomb** [comment]
OK. I'll wait for further instructions, then!
