### ISSUE TITLE
Full audit for Cloud Control Panel article

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1202]
https://support.rackspace.com/how-to/introducing-the-rackspace-cloud-control-panel/

Because this article is linked to from at least two prominent places on the Rackspace website, and it is an important article for new customers, it should get a full audit. I know that @stephamon recently updated it, but I'm not sure how comprehensive the audit was.

**Comment by stephamon** [comment]
Under Melissa Ushakov's guidance, I pulled out specific references to where things are located in the CP and kept an overview of the types of information and actions available there. It could use a look from @kmsholcomb though :)

**Comment by kmsholcomb** [comment]
Hi @stephamon. Will do!

**Comment by kmsholcomb** [comment]
Hey @stephamon. So is the published version the most recent one? It doesn't look like you have a PR for it, so I am assuming so, but I thought I'd check.

**Comment by stephamon** [comment]
@kmsholcomb Yes, the published version is the most recently edited version :)

**Comment by kmsholcomb** [comment]
Hi @stephamon. See my suggested edits in the attached docs. Let me know if you have any questions. Thanks!

[Introducing the Rackspace Cloud Control Panel_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/371838/Introducing.the.Rackspace.Cloud.Control.Panel_editsKH.pdf)
[Introducing the Rackspace Cloud Control Panel_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/371837/Introducing.the.Rackspace.Cloud.Control.Panel_editsKH.docx)
