### ISSUE TITLE
Full audit for Rackspace billing article

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1203]
#https://support.rackspace.com/how-to/rackspace-billing-faq/

Because this article is linked to from at least two prominent places on the Rackspace website, and it is an important article for new customers, it should get a full audit.

- [x]  SME check
- [x]  Editor check
- [x] Update the 'audit_date' and 'last_modified_by' metadata
- [x] If any changes were made, update the 'last_modified_date' metadata

**Comment by kylelaffoon** [comment]
Routed to cloud.ams@rackspace.com mailbox for technical review by SME.

**Comment by kylelaffoon** [comment]
@kmsholcomb I haven't heard back from the SME group yet, but you can edit this in the interim if you want.

**Comment by kmsholcomb** [comment]
Sure, I'll get to it tomorrow, @kylelaffoon.

**Comment by kmsholcomb** [comment]
Hi @kylelaffoon. My edits are attached. They are light, but please let me know if you have any questions. Thanks!

[Rackspace billing FAQ_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/374536/Rackspace.billing.FAQ_editsKH.pdf)
[Rackspace billing FAQ_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/374537/Rackspace.billing.FAQ_editsKH.docx)

**Comment by kylelaffoon** [comment]
Forwarded request to Christie Camp. She shared Richard Ortegon as a SME on this. I shared the intention of the technical review.

Applied edits from @kmsholcomb except forwarded question on debit/credit of difference to technical SMEs.

**Comment by kylelaffoon** [comment]
Richare and Christie will not be good SMEs for this audit. 
Found the Billing QE mailbox today and sent to that mailbox.

**Comment by kylelaffoon** [comment]
Have not heard back from Biling QE team. Shared with Billing Staff and Billing_Cloud teams. Also requested information on the "correct" team to contact, if this isn't something their teams would handle.

**Comment by kylelaffoon** [comment]
Alicia Acosta, from the Billing_Cloud Team, accepted the SME request. She will review and get back to us.

**Comment by kylelaffoon** [comment]
Sent follow up message to Alicia.

**Comment by kylelaffoon** [comment]
Alicia confirmed with her manager that the article is still current on the steps listed.

**Comment by kylelaffoon** [comment]
Adding audit_date.
