### ISSUE TITLE
Full audit for CMS Comparison: Drupal, Joomla, and WordPress

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1204]
https://support.rackspace.com/how-to/cms-comparison-drupal-joomla-and-wordpress/

We need to do a full audit on this Cloud Sites article because it will be linked to from our new Getting Started site. The last update was in January 2016.

**Comment by stephamon** [comment]
- [ ] SME check
- [ ] Editor check

**Comment by stephamon** [comment]
Thomas Hester confirms that the content of this article is 👍

**Comment by stephamon** [comment]
@kmsholcomb can you add this to your list to edit?

**Comment by kmsholcomb** [comment]
@stephamon Will do!

**Comment by kmsholcomb** [comment]
Hi @stephamon. My suggested edits are in the attached PDF (and Word doc). Note the suggested breakup of the paragraphs at the beginning of the article (for some reason, Track Changes doesn't note new paragraph breaks). Please let me know if you have any questions. Thanks!

[CMS comparison drupal joomla wordpress_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/369243/CMS.comparison.drupal.joomla.wordpress_editsKH.pdf)
[CMS comparison drupal joomla wordpress_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/369244/CMS.comparison.drupal.joomla.wordpress_editsKH.docx)
