### ISSUE TITLE
CBS article update - tweet from customer

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/rackspace-how-to#1210]
From: Dave Post <dpost@rackspace.com>
Date: Thursday, July 7, 2016 at 7:31 PM
To: Knowledge Center <KB_center@rackspace.com>
Cc: "Help (Social Support Team)" <Help@rackspace.com>, James Arellano <james.arellano@RACKSPACE.COM>, Dustin Wray <dustin.wray@RACKSPACE.COM>
Subject: Re: Dave Craige

Hello Knowledge Center Team,

I hope all is going well today. We've had a conversation on Twitter today with a customer named Dave Craige (DDI 986581). At the end of our conversation with Dave, he observed that a Support article needs to be updated:

-------------------------------------------------------
Tweet from @davecraige:
@Rackspace this document is out of date.  https://support.rackspace.com/how-to/create-and-attach-a-cloud-block-storage-volume
 
"Click Servers in the main navigation."

http://twitter.com/davecraige/status/751184206592503809

-------------------------------------------------------
Tweet from @Rackspace:
@davecraige Our apologies, Dave. We'll get the document updated. Thanks for letting us know.

http://twitter.com/Rackspace/status/751185025333362688

-------------------------------------------------------
Tweet from @davecraige:
@Rackspace yea I think you meant to say "Click Storage"

http://twitter.com/davecraige/status/751185581757968384

-------------------------------------------------------
Tweet from @Rackspace:
@davecraige Yes, you're exactly right. We will ask our Knowledge Center Team to correct this item. Thanks again!

http://twitter.com/Rackspace/status/751196348368691200

When you have a moment, can you update this article?

Thank you very much in advance!

Dave Post
Social Media Specialist

dpost@rackspace.com
phone: 210-312-3611
mobile: 210-445-3440

From: Microsoft <dpost@rackspace.com>
Date: Thursday, July 7, 2016 4:53 PM
To: James Arellano <james.arellano@RACKSPACE.COM>, Dustin Wray <dustin.wray@RACKSPACE.COM>
Cc: "Help (Social Support Team)" <Help@rackspace.com>
Subject: RE: Dave Craige

Hello James,
 
I just wanted to let you know that Dave Craige tweeted again:

-------------------------------------------------------
Tweet from @davecraige: 
@Rackspace thanks. Yea would love a bit better support. I'm paying $4k a year and would love more help.
http://twitter.com/davecraige/status/751166551391211521
-------------------------------------------------------
Tweet from @Rackspace: 
@davecraige Thank you, Dave. We will be sure to pass along your feedback to your AM and to our Support Team.
http://twitter.com/Rackspace/status/751171799346479104
 
Best regards,
 
Dave Post
Social Media Specialist

**Comment by DonNateR** [comment]
Fixed by #1211

**Comment by cyrichardson** [comment]
Reopened this one. #1207 is the one closed by #1211

**Comment by davecraige** [comment]
Thanks guys!
