### ISSUE TITLE
Change the Permanent Link for StatsD Guide

### ISSUE THREAD

**Issue by wolfdancer** [rackerlabs/rackspace-how-to#1231]
I have submitted a PR for the easy fix on link text: https://github.com/rackerlabs/rackspace-how-to/pull/1230

The link itself is still misleading.  It should match the file name to clarity.   Instead of "https://support.rackspace.com/how-to/deploying-rackspace-metrics/" it should be "https://support.rackspace.com/how-to/integrate-statsd-with-rackspace-metrics/"

I can submit PR but I have some pending question:
- How to make the change for the link change? 
- Is there a way to make the original link an HTTP forward, in case readers have it on the bookmark or browser history?

**Comment by cyrichardson** [comment]
#1230 Fixes this.

**Comment by wolfdancer** [comment]
@cyrichardson I don't think #1230 fix it.  The URL still says "https://support.rackspace.com/how-to/deploying-rackspace-metrics/" right now.  Can you please double check?  Thanks

**Comment by cyrichardson** [comment]
Thanks, Shane! Checking...

**Comment by cyrichardson** [comment]
@kylelaffoon Do you know if what Shane is requesting is possible? Would this be a redirect?

**Comment by DonNateR** [comment]
@cyrichardson: We would need to change the permalink and file name of the article, and than add a redirect in Nexus Control. You want me to do this for you?

**Comment by cyrichardson** [comment]
@DonNateR Thanks! If you have time to do it, that's be great!
I haven't done this before and you will be faster. I will then look at what you do to change it. @wolfdancer FYI...

**Comment by DonNateR** [comment]
@wolfdancer: Well get my PR changing permalink merged right away, but will have to wait for a merge from our support network deployment repo for the redirect from the old article to work.

**Comment by wolfdancer** [comment]
@DonNateR thanks!  This is not a blocker and can wait to be part of the regular process.  I should have mentioned it when submitting the issue.

**Comment by DonNateR** [comment]
Permalink for article fixed. Even though the redirect is awaiting merge in Nexus Control, I am closing this since the issue of permanence has been addressed.
