### ISSUE TITLE
Incorrect file path in Parse Migration How-To

### ISSUE THREAD

**Issue by amandalee-rax** [rackerlabs/rackspace-how-to#1253]
Hello!

  A customer recently noticed that the "Migrating from Parse to Rackspace" article is incorrect (https://github.com/rackerlabs/rackspace-how-to/blob/756acc017f201566532a00a6e19533db6ac67d57/content/cloud-files/migrating-from-parse-to-rackspace.md)

  Under the "Configure Your Certificate" section of the article there's a sentence that says "After Parse is running, you can configure a valid certificate within NGINX by modifying /etc/nginx/conf.d/.conf, where is replaced with the URL you provided when you deployed your Parse stack."  Instead, the sentence should read "After Parse is running, you can configure a valid certificate within NGINX by modifying /etc/nginx/conf.d/**<your_url>**.conf, where **<your_url>** is replaced with the URL you provided when you deployed your Parse stack."  It looks like the <your_url> part disappeared at some point.  

  I will be out on maternity leave after Tuesday, 7/19, so I decided to create a ticket rather than submitting the edit myself just in case something went wrong.  If you have any questions or need anything after 7/19 please contact Chris Hultin or Raj Patel on the Orchestration team.

Thanks,
Amanda

**Comment by amandalee-rax** [comment]
Ok, I think I see how this happened since the necessary text disappeared in the ticket as well.  Apparently markdown doesn't like that formatting.

The sentence above should read "After Parse is running, you can configure a valid certificate within NGINX by modifying /etc/nginx/conf.d/**(your_url)**.conf, where **(your_url)** is replaced with the URL you provided when you deployed your Parse stack."

**Comment by DonNateR** [comment]
@amandalee-rax: Your issue has been fixed. Thank you for contributing!
