### ISSUE TITLE
Article on IPs

### ISSUE THREAD

**Issue by everett-toews** [rackerlabs/rackspace-how-to#1256]
With so many type of IPs, I think we're going to need a single how to article that explains all of the different IPs a customer can use, what the differences are, when/why they would be used, and links to the docs on how to use them. 

* Virtual IP
* Floating IP
* PublicNet IP
* ServiceNet IP
* Private Network IP address from a network created by a user
* Shared IP (when we get it)
* [RackConnect public IP record](https://support.rackspace.com/how-to/rackconnect-v30-retained-public-ip-addresses/)

**Comment by kylelaffoon** [comment]
Created list of related article with definitions and use steps: https://one.rackspace.com/display/devdoc/List+of+IP+references

**Comment by kylelaffoon** [comment]
Shared list and draft of article with Everett. Asked for confirmation of layout and direction on items I'm still researching.

**Comment by kylelaffoon** [comment]
Article published at https://support.rackspace.com/how-to/understand-ip-options/.
