### ISSUE TITLE
Remove all references to First Gen Cloud Servers from How-To articles

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1258]
Trey H:  We're nearing completion of the migration and we wanted to have the work scoped and planned for removing it from the KC after the completion of the migrations.

- We can move forward with this issue once we get a date from Trey.

Task List:
- [x] Remove "First Generation" references from articles.
- [x] Remove "First-Generation" references from articles.
- [x] Remove "Next Genration" and "Next-Generation" references from articles.
- [x] Publish central redirect page for retired articles.
- [x] Redirect "First Generation" specific articles to retired-redirect page.

**Comment by tryhoehne** [comment]
In October, I leave the exact date to you and your team.

**Comment by ReneeRendon** [comment]
@tryhoehne 
Okay, give us the earliest date that we can do it, and we'll take care of it. 

We were approached with this before and made all the changes only to discover that we were too hasty and needed to go back and revert.

**Comment by tryhoehne** [comment]
Sep 12th for removing the documentation.

**Comment by ReneeRendon** [comment]
Final fix from PR #1510
