### ISSUE TITLE
On boarding doc suggestions

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1264]
The on boarding team sent doc suggestions for our team to look into. They are located in a table here. https://one.rackspace.com/display/devdoc/On+boarding+team+doc+suggestions

These suggestions need to be vetted and made into separate tickets.

**Comment by ReneeRendon** [comment]
@kylelaffoon   My original comment said "7 suggestions"; however, I removed the "7" because we will continue to get requests added to the table. 

(We received another one today!)

**Comment by kylelaffoon** [comment]
Emailed Tyler and Yesenia on their respective items on the list. Asked if we had drafted information anywhere and if we could meet to discuss the processes. Tyler replied with looping in Allison Henslee. Extended invitation to Allison.

**Comment by kylelaffoon** [comment]
Research complete.
