### ISSUE TITLE
Update Migrating from Parse to RS article

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1265]
I have a customer that has been using this tutorial to set up her Orchestration Parse Stack. https://support.rackspace.com/how-to/migrating-from-parse-to-rackspace/
 
The customer really benefitted from this command  nginx -t -c /etc/nginx/nginx.conf  in order to validate her SSL configuration. As well as quick instructions linking her Object Rocket account with Rackspace Could Control since the tutorial calls for an Object Rocket MongoDB. Linked accounts under “Databases” > ”MongoDB”.
Can we get this added on to the article?
 
Also, she greatly appreciated the last update you guys did about the path so thank you.
 
Best regards,
Yesenia Ceja,

**Comment by kylelaffoon** [comment]
Checked with Yesenia to see when the user should validate their ssl. She directed "They should validate at the end of "Configuring your Certificate" right before moving on to configuring the Parse dashboard."

**Comment by kylelaffoon** [comment]
Completed this request through [PR#1299](https://github.com/rackerlabs/rackspace-how-to/pull/1299)
