### ISSUE TITLE
On boarding team doc suggestion - Migration article needed

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1271]
#Relates to #1264 
SME: Tyler Lutz
Input table: https://one.rackspace.com/display/devdoc/On+boarding+team+doc+suggestions
Migration – take a look at this digital ocean article
https://www.digitalocean.com/community/tutorials/migrate-your-current-vps-linode-rackspace-aws-ec2-to-digitalocean
They even have an article to help you transition control panels:
https://www.digitalocean.com/community/tutorials/how-to-transition-from-rackspace-to-digitalocean-s-control-panel

**Comment by kylelaffoon** [comment]
Contacted Tyler to discuss available information for this. We will be meeting with Allison Henslee to outline the process.

**Comment by DonNateR** [comment]
Issue will be addressed by #1322
