### ISSUE TITLE
On boarding team doc suggestion - How to install and use CPanel

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1272]
#Relates to #1264 
SME: Tyler Lutz
I know this one may be a community item but just in case: CPANEL and Rackspace – how to install and utilize CPANEL high level overview

**Comment by kylelaffoon** [comment]
Contacted Tyler to discuss available information for this. We will be meeting with Allison Henslee to outline the process.

**Comment by kylelaffoon** [comment]
Reviewed request and available material. Posted the following to Wordstorm group channel for discussion: Discussing this issue with On boarding (https://github.com/rackerlabs/rackspace-how-to/issues/1272) They would like an article on installing and using cPanel. We have a Community post we could convert: https://community.rackspace.com/products/f/25/t/6798 However, cPanel is a third-party package. Should we politely decline this request? I am open to discussion on this.

**Comment by ReneeRendon** [comment]
Kyle: Reviewing cPanel's requirements, the clean server seems to be specific to our product. Likely this is a troubleshooting item we should share. That could be an FAQ Q/A pair.

Renee: That sounds like a good option.

**Comment by kylelaffoon** [comment]
This post discourages using CPanel and Plesk due to interference with our administrators' work: https://community.rackspace.com/products/f/25/t/4888

**Comment by ReneeRendon** [comment]
@kylelaffoon 
The post discourages using cPanel with our managed operations. Is it only discouraged with the use of managed operations or in all cases?

**Comment by kylelaffoon** [comment]
Completed needed change in the Cloud Servers FAQ through PR #1349
