### ISSUE TITLE
On boarding doc suggestion - FAQ for common issues

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1273]
#Relates to #1264
SME: Tyler L.
Maybe some sort of FAQ for common issues like “my site is timing out” and what the possible issues could be.

**Comment by DonNateR** [comment]
Moving to Milestone 14 because we need SME feedback.

**Comment by DonNateR** [comment]
Emailed Chris Estrada and other Cloud support SME's to assist with this article

**Comment by DonNateR** [comment]
Meeting with Joey Davis on Friday to build out a draft of this article. He also provided a few resources for me to get started with

**Comment by DonNateR** [comment]
Meeting with Joey Davis has been moved to next Wednesday. Placing a Milestone 15 on this one.

**Comment by DonNateR** [comment]
Closing, as this issue will be addressed by Issues #1440, #1441, #1443, and #1444.
