### ISSUE TITLE
On boarding doc suggestion - Troubleshoot SSL error

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1276]
Relates to #1264 
SME: Yesenia C.

Customer is getting “An SSL error has occurred and a secure connection to the server cannot be made.”
Could we get something on how customers can troubleshoot this error?

**Comment by kylelaffoon** [comment]
Contacted Yesenia to inquire about gathering information on this article.

**Comment by kylelaffoon** [comment]
Emailed Yesenia requesting her notes captured on the troubleshooting steps the users will complete for this.

**Comment by kylelaffoon** [comment]
We do have one reference to SSL error in the How-To in the article at https://support.rackspace.com/how-to/requesting-additional-ipv4-addresses-for-cloud-servers/ .
I will check with Yesenia to see what details she has on the SSL error in question.

**Comment by kylelaffoon** [comment]
From: Yesenia Ceja <yesenia.ceja@RACKSPACE.COM>
Date: Friday, August 5, 2016 at 12:50 PM
To: Rackspace Hosting <kyle.laffoon@RACKSPACE.COM>
Cc: Nate Archer <Nate.Archer@rackspace.com>, Tyler Lutz <tyler.lutz@RACKSPACE.COM>
Subject: RE: What we need on your doc suggestion - 7

Hello Kyle,
 
This was another topic I brought up not knowing the process myself. I thought you were just looking for topics to build from. 
The troubleshooting assistance I provided was just ensuring her SSL cert was applied correctly and that the load balancer was configured correctly which I did find articles on.
 
We were never able to actually get the customer up and running. 
 
Thank you,
Yesenia Ceja,
Launch Manager
Phone: (210) 312-4774
Toll free: 1-877-934-0407
https://community.rackspace.com/ 
Restorative | Developer | Empathy | Achiever | Strategic



 
 
From: Kyle Laffoon 
Sent: Thursday, August 04, 2016 3:52 PM
To: Yesenia Ceja
Cc: Nate Archer; Tyler Lutz
Subject: What we need on your doc suggestion - 7
 
(Capturing the items in this email until we can sync up in person. This is 2 of 3)
 
Hi Yesenia,
 
From the list at https://one.rackspace.com/pages/editpage.action?pageId=174901302, we have the following 3 items attributed to you:
 
6. Setting up cron jobs on the Parse stack or any stack/server for that matter. I couldn’t find any documentation.
7. Customer is getting “An SSL error has occurred and a secure connection to the server cannot be made.” - Could we get something on how customers can troubleshoot this error?
8. How-To apply SSL cert to NGINX.
 
 
On 7, I need your notes captured on the troubleshooting steps the users will complete for this.
 
Thanks,
Kyle

**Comment by stephamon** [comment]
@kylelaffoon @ReneeRendon Seems like this one is lacking in some information. What did the customer's set up look like? It seems like making sure that SSL cert and the load balancers were set up correctly didn't solve the problem, so I'm not sure what else we could do on this one. 

We would probably need to get more data about the customer's setup and error messages and work with a technical support Racker to solve the issue and figure out whether it was a unique problem or something that would be beneficial for everyone to know.

**Comment by ReneeRendon** [comment]
Yes, @stephamonand @kylelaffoon .

Exactly what Stephanie said, "figure out whether it was a unique problem or something that would be beneficial for everyone to know."

**Comment by kylelaffoon** [comment]
Fowarded the questions to Yesenia and requested the technical support Racker assigned to this.

**Comment by kylelaffoon** [comment]
We lack information from which to build on this. We will open a new issue when more is available.
