### ISSUE TITLE
On boarding doc suggestion - How-To apply SSL cert to NGINX

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1277]
Relates to #1264 
SME: Yesenia Ceja
Request list: https://one.rackspace.com/pages/editpage.action?pageId=174901302

Need article on How to apply SSL cert to NGINX.

**Comment by kylelaffoon** [comment]
Emailed Yesenia to inquire about input for this article.

**Comment by kylelaffoon** [comment]
Emailed Yesenia and shared the SSL validation step we added to the "Migrating from Parse to Rackspace" article. Asked if this would cover this need or, if not what the next steps should be.

**Comment by kylelaffoon** [comment]
From: Yesenia Ceja <yesenia.ceja@RACKSPACE.COM>
Date: Friday, August 5, 2016 at 12:54 PM
To: Rackspace Hosting <kyle.laffoon@RACKSPACE.COM>
Cc: Tyler Lutz <tyler.lutz@RACKSPACE.COM>, Nate Archer <Nate.Archer@rackspace.com>
Subject: RE: What we need on your doc suggestion - 8

These are the articles that helped the customer actually install the cert and what was added in to the previous article was to validate the cert.
https://www.digicert.com/ssl-certificate-installation-nginx.htm
https://support.comodo.com/index.php?/Default/Knowledgebase/Article/View/1091/0/certificate-installation--nginx -She bought her SSL from comodo so this was perfect for the customer.
 
Thank you
Yesenia Ceja,
Launch Manager
Phone: (210) 312-4774
Toll free: 1-877-934-0407
https://community.rackspace.com/ 
Restorative | Developer | Empathy | Achiever | Strategic



 
 
From: Kyle Laffoon 
Sent: Thursday, August 04, 2016 3:59 PM
To: Yesenia Ceja
Cc: Tyler Lutz; Nate Archer
Subject: What we need on your doc suggestion - 8
 
(Capturing the items in t email until we can sync up in person. This is 3 of 3)
 
Hi Yesenia,
 
From the list at https://one.rackspace.com/pages/editpage.action?pageId=174901302, we have the following 3 items attributed to you:
 
6. Setting up cron jobs on the Parse stack or any stack/server for that matter. I couldn’t find any documentation.
7. Customer is getting “An SSL error has occurred and a secure connection to the server cannot be made.” - Could we get something on how customers can troubleshoot this error?
8. How-To apply SSL cert to NGINX.
 
 
On 8, we did add the following to the Migrating from Parse to Rackspace article. Will this cover this issue? If not, what is needed next?
 
“Configure Your Certificate
After Parse is running, you can configure a valid certificate within NGINX by modifying /etc/nginx/conf.d/<your_url>.conf, where <your_url> is replaced with the URL you provided when you deployed your Parse stack.
Validate your ssl certificate with the following command:
nginx -t -c /etc/nginx/nginx.conf
If you do not have a valid certificate, you can purchase one through Rackspace if you are hosting a physical server with us. Please contact your Account Manager or Rackspace Support with further questions.”
 
Thanks,
Kyle

**Comment by stephamon** [comment]
@kylelaffoon @ReneeRendon Same as #1275 here. Since the customer was able to successfully install the SSL cert on NGINX using those outside resources, is this something that should belong in Community instead as general advice? 

Other than the piece that you already added, there doesn't seem to be anything Rackspace specific here.

**Comment by stephamon** [comment]
After talking with Renee, I'm going to see if NGINX has official installing instructions for SSL certs and if so, link to them in the article. If not, I'll add the steps on how to install the cert.
