### ISSUE TITLE
Edit High availability for Cloud Databases article for "in the future" references

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1288]
-Relates to #409 

url:https://support.rackspace.com/how-to/high-availability-for-cloud-databases/ 

Second paragraph "In the future, we will increase the limit on the maximum number of replicas." Emailed Riddhi Shah and Tom Blankenship on 07/13/16 to inquire on the current status.
Riddhi replied that it is not in effect yet and reached out to Steve Croce for a possible timeline.

Steve replied "It’s still in the backlog and just hasn’t been a priority of late. I expect us to raise it in the next month or two. Maybe I’ll remove the reference to raising it and just leave the statement at calling out the current limit."

The table for the 21 articles that reference 'future" is located in the one wiki

**Comment by ReneeRendon** [comment]
Hi @RackerSCroce 

The following two sentences are in the article:
"In the future, we will increase the limit on the maximum number of replicas. There is no design limitation for the maximum number of replicas."

**What is the difference between "limit on the maximum number of replicas" and "design limitation for the maximum number of replicas"?**

**Comment by kylelaffoon** [comment]
Steve is OOO until 8/25.

**Comment by kylelaffoon** [comment]
Sent follow up email to Steve on this to find out the answer to Renee's question and if there is an ETA on the referenced limitation being increased is.

**Comment by kylelaffoon** [comment]
This issue was resolved with Steve's update on August 11th.
