### ISSUE TITLE
Edit Replicate backup for disaster recovery with Cloud Databases article for "in the future" references

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1289]
-Relates to #409 

url: https://support.rackspace.com/how-to/replicate-backup-for-disaster-recovery-with-cloud-databases/

Revisit in August. Set reminder in my calendar.

Second paragraph "In the future, we will add the ability to add backup replication to a backup schedule, so every backup in a schedule gets automatically copied to another region." Setting reminder to check back August.

Revisit in August. Set reminder in my calendar.

**Comment by kylelaffoon** [comment]
Relates to #409

**Comment by kylelaffoon** [comment]
Sent updated message to Steve Croce inquiring if this is underway or refocused.

**Comment by kylelaffoon** [comment]
per Steve: "Still coming soon. We’ve just been bogged down with some other issues lately."

**Comment by DonNateR** [comment]
Closing per Renee's suggestion.
