### ISSUE TITLE
Full audit: Open ports in the Linux firewall to access ...

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1292]
This article is due for a full audit. (SERVERS)
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-servers/open-ports-in-the-linux-firewall-to-access-pop-and-imap-mail-servers.md

- [x] SME check
- [x]  Editor Check
- [x]  Update the 'audit_date' and 'last_modified_by' metadata
- [x]  If any changes were made, update the 'last_modified_date' metadata

**Comment by kylelaffoon** [comment]
Fixed layout to correct numbering sequence on PR #1301. Sent link to this issue and the article to the COE_Content mailbox to request SME review.

**Comment by kylelaffoon** [comment]
@kmsholcomb If you want to begin your review at this point, you can.

**Comment by kylelaffoon** [comment]
Forwarded request for SME review to Echo-ESC Team.

**Comment by kmsholcomb** [comment]
Hi @kylelaffoon. My suggested edits are in the attached Word file (and PDF copy). I think that we can start simplifying steps by omitting the "by using the following command" phrase. Let me know what you think about taking that out. And if you have any questions, please let me know. Thanks!

[Open ports in the Linux firewall to access POP and IMAP mail servers_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/390859/Open.ports.in.the.Linux.firewall.to.access.POP.and.IMAP.mail.servers_editsKH.pdf)
[Open ports in the Linux firewall to access POP and IMAP mail servers_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/390860/Open.ports.in.the.Linux.firewall.to.access.POP.and.IMAP.mail.servers_editsKH.docx)

**Comment by kylelaffoon** [comment]
Ben Temple volunteered as our SME for this item. He shared his review notes, specifying that we need to update for firewalld function for distros after RHEL7. I added the commands for this alternative to Kelly's edits submitted and forwarded to Ben for confirmation.

**Comment by kylelaffoon** [comment]
Incorporated Kelly and Ben's feedback in https://github.com/rackerlabs/rackspace-how-to/pull/1304
