### ISSUE TITLE
Full audit: Migrating a Linux server from the command line

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1293]
This article is due for a full audit. (SERVERS)
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-servers/migrating-a-linux-server-from-the-command-line.md

- [x]  SME check
- [x]  Editor Check
- [ ]  Update the 'audit_date' and 'last_modified_by' metadata
- [ ]  If any changes were made, update the 'last_modified_date' metadata

**Comment by stephamon** [comment]
According to Trey Hoehne: "Yes it still looks good. This is a general guide line that shouldn't become stale or outdated anytime soon."

**Comment by stephamon** [comment]
@kmsholcomb can you take a look at this article please? The link in the description goes to the GitHub file, so here's the live URL if you need it: https://support.rackspace.com/how-to/migrating-a-linux-server-from-the-command-line-1/ r

**Comment by kmsholcomb** [comment]
I'll send you feedback by the end of the day, @stephamon

**Comment by kmsholcomb** [comment]
Hi @stephamon. The attached Word doc (plus PDF copy) has my suggested edits. Please let me know if you have any questions. Thanks!

[Migrate a Linux server from the command line_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/394546/Migrate.a.Linux.server.from.the.command.line_editsKH.pdf)
[Migrate a Linux server from the command line_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/394547/Migrate.a.Linux.server.from.the.command.line_editsKH.docx)

**Comment by kmsholcomb** [comment]
Oh, I forgot to mark this in the file. Because the article is not a procedure, I would begin the title with "Migrating" rather than "Migrate."
