### ISSUE TITLE
Return to adjust "in the future" references in Using the myrackspace firewall manager article

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1294]
Relates to #409 
**Return to this in late August.**

url - https://support.rackspace.com/how-to/using-the-myrackspace-firewall-manager/ 

Emailed Dusty Simoni with the 5 occurrences in this article to ask if any had already been implemented or were already under way. 07/15/2016 Send 2nd notice 160726 Dusty replied with  Rob Jackson as a better SME for this. Copied Rob. Replied to all and asked Rob if he could answer or recommend a better SME.

Rob responded "That he is the right person, that we should also incliude the MyRAck team and that there is a launch pending in a couple months. Replied asking if we should calendar these for lat August and asking which of the 3 MyRack mailboxes to use.

See list at https://support.rackspace.com/how-to/using-the-myrackspace-firewall-manager/

**Comment by kylelaffoon** [comment]
Shared this issue with Jason Hammons of the On boarding team for his input and reference.

**Comment by kylelaffoon** [comment]
From Jason Hammons: "Some notes:
 
FW Manager does work for firewalls in a high-availability configuration, I just checked and it comes up and apparently allows configuration on both firewalls.  I don’t know if it’s a good idea to use it this way however, setting different configurations on each firewall in the HA pair may cause issues but there’s nothing to keep a customer from doing it that I can see.
 
Under ‘Add a permit policy’, the image is incorrect, the source IP address is missing a . (should be 207.250.49.146 instead of 207.25049.146).
 
I can’t really address the ‘future’ statements very well, most of them seem to relate to features on Juniper and we haven’t had a Juniper firewall yet.
 
Also, it sounds like you may need to do a major rewrite in a couple of months, once they get the new version of Firewall Manager live.  For our purposes it would work pretty well as-is, but a few more examples or a little more how-to and less documentation and definitions might do better in the next version.  Having everything well-documented is great, but our customers tend to be a bit more focused on ‘How do I open up web access to my server through the firewall?’ and ‘How do I get remote desktop access to my servers?’
 
I hope this helps, I’m not exactly sure what you’re looking for but if you have any other questions please let me know."

**Comment by ReneeRendon** [comment]
Closing this because Cloud Sites will not be updated thru Rack.
