### ISSUE TITLE
Return to update "in the future" reference in Cloud Servers FAQ

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1296]
**Return to this in August**
url - https://support.rackspace.com/how-to/cloud-servers-faq/ 
1.The answer to the question, "Are Security Groups on Cloud Networks supported?" references "future".
2.The answer to the question, "Are Outbound Security Groups supported?" references "future".
07/14/2016 Emailed Jorge Miramontez and inquired about implementation timeline. Cat and Jorge confirmed this went into effect this year. Inquired about additional information to include for these services now available. 160725 Jorge and Trent Gillespie will be discussing what should be included since phase III is about to start. 

list on page https://one.rackspace.com/pages/editpage.action?pageId=172926978

**Comment by ReneeRendon** [comment]
Reached out to Cat. Both items are in production. The “future” references need to be removed from the article.

**Comment by ReneeRendon** [comment]
@kylelaffoon 
Security Groups and Outbound Security Groups are supported.
