### ISSUE TITLE
Return to update "in the future" rerence in Rackspace Webmail chat FAQ

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1297]
Reached out to Aaron Medrano on this for an update to in the future items.

https://support.rackspace.com/how-to/rackspace-webmail-chat-faq/	

Emailed Aaron Medrano with occurences in this article. 07/18/2016 Sent 2nd request 160726

See list at https://one.rackspace.com/display/devdoc/Articles+containing+reference+to+the+future

**Comment by ReneeRendon** [comment]
Reached out to Brian Hazzard today. The references need to be removed. They are on hold indefinitely.

**Comment by kylelaffoon** [comment]
Remove in the future references in PR #1347. Routing preview to Brian Hazzard for his review before asking for merge.

**Comment by kylelaffoon** [comment]
Brian approved.
