### ISSUE TITLE
Suggestion for Contributing doc

### ISSUE THREAD

**Issue by meker12** [rackerlabs/rackspace-how-to#1302]
Might want to include a link to the training material that you've created in the Contributor guidelines.  Also, consider adding a TOC at the top of the document. See http://doctoc.herokuapp.com/.

**Comment by ReneeRendon** [comment]
Thanks Margaret. Great suggestions! We'll add the TOC and the link when the course is ready. It should be finalized and in the RackU choices the week of August 15.

**Comment by kylelaffoon** [comment]
Waiting on final - final class url.

**Comment by DonNateR** [comment]
Cannot put class URL on contributing doc. We need to look into possibly uploading the class on Youtube.

**Comment by ReneeRendon** [comment]
Checked with Laura on this. She is looking for the Rack YouTube guidelines.

**Comment by kylelaffoon** [comment]
Renee also reached out to Alan Bush on this. He is researching and getting back to her.

**Comment by ReneeRendon** [comment]
I'm meeting with Alan this Thursday.

**Comment by ReneeRendon** [comment]
Spoke with Alan and Stuart Thursday. (Sep 22)

@DonNateR is going to send the training team the edits that we need to whittle the class down to 3-5 minutes. The training team will make a screencast for Alan Bush to post to the Rack YouTube channel.

**Comment by DonNateR** [comment]
Rack U should have this ready by Friday, the 7th

**Comment by ReneeRendon** [comment]
The final edited class will be sent to Alan for review and post this week.

**Comment by DonNateR** [comment]
Closed by PR #1566
