### ISSUE TITLE
Possible new CBS partition article

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1312]
From Uservoice feedback: 

Here’s the message.
 
Ref: www.support.rackspace.com/how-to/prepare-your-c..
After completing the steps in the above article, it would be great to have an article describing how to mount the /home folder or any other folder to a new partition / mount after creating a block storage device.

This article was helpful for me, but I think RS should include a similar one: www.help.ubuntu.com/community/Partitioning/Home..

**Comment by DonNateR** [comment]
Emailed Melissa Biles for second opinion on whether or not a new partitioning article is necessary. Placing blocked on this one until we receive a response.

**Comment by kylelaffoon** [comment]
This is covered under the Move a Cloud Block Storage volume between servers. This article is listed in the All articles area for Cloud Block Storage, but not in the Introduction area. I could modify that.

**Comment by DonNateR** [comment]
That could work. It's probably easier to find a SME to look over the article as opposed to finding one to help write an article

**Comment by kylelaffoon** [comment]
Emailed Cory Stone and David Orman for verification that this will meet the need of the request.

**Comment by kylelaffoon** [comment]
Applying David's Linux unmount / remount suggestions. Emailed Ben Temple on the Windows steps.

**Comment by kylelaffoon** [comment]
Updated Prepare your Cloud Block Storage volume article to include un-mounting instructions for Linux and Windows servers. David Orman reported this was the fix needed. David supplied the Linux information and Ben Temple supplied the Windows reference.
