### ISSUE TITLE
On boarding - Create article "Permissions in the MyRackspace control panel"

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1315]
Fixes part of issue #1270 
 
SME: Elizabeth Wirth, Tyler Lutz, Allison Henslee

Create an article with a list of all the permission in the myRack control panel, and the process for how to change those permissions. The article will link to the article described in issue #1313.

You can use these resources to help you make the article:

- [Adding contacts through MyRack.docx](https://github.com/rackerlabs/rackspace-how-to/files/398097/Adding.contacts.through.MyRack.docx)

-  [PermissionsGuide.pdf](https://github.com/rackerlabs/rackspace-how-to/files/398098/PermissionsGuide.pdf)

**Comment by kylelaffoon** [comment]
Per Yesenia, this needs to be an article on adding users in the Cloud Sites Control Panel.

**Comment by kylelaffoon** [comment]
Completed through PR #1327
