### ISSUE TITLE
On boarding - Create article "How to set-up a cloud account through the MyRack customer portal"

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1316]
Fixes part of issue #1270 

SME: Tyler Lutz, Alison Henslee

Create article showing how to sign up for a cloud account using MyRack and how to link an existing cloud account to a MyRack account. This article will link to the article described in issue #1313 

This article should also be compared with the content contained in this article(https://support.rackspace.com/how-to/faq-for-seamless-sign-on-between-myrackspace-and-the-cloud-control-panel/). 

As a resource, use the document 
[Connecting a cloud account through the MyRack portal.docx](https://github.com/rackerlabs/rackspace-how-to/files/398154/Connecting.a.cloud.account.through.the.MyRack.portal.docx)

**Comment by ReneeRendon** [comment]
Not necessary now that Cloud Sites is moving.
