### ISSUE TITLE
On boarding - Article audit "Seamless sign-on between MyRackspace and the Cloud Control Panel

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1317]
- [ ] SME review, use Tyler Lutz or Allison Henslee. Allison alluded to the article being an unnecessary step for MyRack users. We may need to consider combining this article with the one described in #1316 

- [ ] Editorial review (if necessary)

**Comment by ReneeRendon** [comment]
Not necessary now that Cloud Sites is moving.
