### ISSUE TITLE
Add Shared Ip to Networks FAQ

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1328]
To be merged on August 15th:

The content from the ether pad needs to be added to the shared networks FAQ.

The content for the Shared IP LA FAQs is here:
https://etherpad.rax.io/p/sharedipfaq

To be added to the BOTTOM OF the Cloud Networks FAQs page here:
https://support.rackspace.com/how-to/cloud-networks-faq/

Please let me know if you have any questions, or require anything from me to help in tracking this, etc.

Also, I will look through the contributing guide sent by Cat as well, just to help me help you in the future :-).

Thank you both for your help.

Happy Friday!
Trent

Trent Gillaspie

Rackspace | Product Manager | 303.386.6115

Strategic | Futuristic | Communication | Responsibility | Arranger

**Comment by trentgillaspie** [comment]
Any update as to when we can expect this to go live? Thanks!

**Comment by stephamon** [comment]
@trentgillaspie I'll get it up right now :)
