### ISSUE TITLE
Missing diagram in article

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1340]
Web team,
 
This article includes text indicating that there should be a diagram, which is missing when I view the page with Firefox and Safari:
 
https://support.rackspace.com/how-to/rackconnect-v20-with-cloud-networks-faq/
 
“The diagram below should help you to visualize how RackConnect and Cloud Networks work on the same cloud server. In the diagram Cloud Private Network is equivalent to the Cloud ServiceNet Network.”
 
-----
Jay Hidalgo
Windows Administrator

**Comment by DonNateR** [comment]
Found the article in the old repo. The diagram and the example listed in the article are both missing. Will have to pass this along to a SME in order to fill the gaps.

**Comment by DonNateR** [comment]
Missing example can be found under this line of text: "Below is an example of how the Network Policy should be configured to allow connectivity across your Cloud Network IP addresses. In this example, the Cloud Network is equal to 192.168.x.x/24."

**Comment by DonNateR** [comment]
Jason Hammons: 

It looks ok to me, except for the missing diagram, and I don’t know where you could find it.  Rackconnect 2.0 is all but obsoleted now though, so except for a couple of cases that they’re working on, we use RC 3.0 for everything new.  You might be able to rewrite it and just remove that example, there should be very few people with new RC2.0 configurations.
