### ISSUE TITLE
Set up communication effort for the Online Contribution class

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1342]

**Comment by DonNateR** [comment]
Emailing Jecca for reporting information and information about the Rack U email blast.

**Comment by DonNateR** [comment]
Jecca is going to give us more details on the revamped newsletter. I'm going to get an estimated time of arrival.

**Comment by ReneeRendon** [comment]
Flyers

**Comment by DonNateR** [comment]
Youtube class linked here: https://www.youtube.com/watch?v=haFooDkKr-A&feature=youtu.be

**Comment by DonNateR** [comment]
Flyer draft completed. Closing this now.
