### ISSUE TITLE
Cloud Files billing explanation is needed

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1344]
From Yesenia Ceja:
"I have the idea for a How-To article on how Cloud Files is billed. Recently came across this question and many Rackers even billing department couldn’t explain this. 
I have the breakdown now so I can explain how its billed and what we need to explain to the customer."

Further information received:
Below is the information for the billing. I’ll go over it with you tomorrow.
 
Usage records for the account#
 

 
How usage is being charged to the Customer:
1.       BRM received usages of 27836 MB (27.18 GB)on 7th Aug.
2.       Usage Quantity is derived as “Disk / Number of days in the billing cycle”. Quantity = 27836 / 31 = 897.935484 MB
3.       Customer Usages will be charged at $0.1 per GB
4.       Amount to be charged = (897.935484 / 1024) * $0.1 = 0.087689 = $0.09 (rounded to 2 decimal)
 
How estimated usage is being calculated:
Estimated usages are calculated as average of all usages in a billing period.
1.       Sum of all usages from 28-Jul to 7-Aug is 157513 MB.
2.       Number of days in the billing period 28-Jul to 27-Aug is 31 days
3.       Estimated Usage = 157513 / 31 = 5081.06 MB = 4.96 GB

**Comment by kylelaffoon** [comment]
![image003](https://cloud.githubusercontent.com/assets/5932812/17707308/6c5bf5a6-63a5-11e6-969c-b5b068cdcab4.png) For our consideration in writing only. We will replicate with a table not including customer information.

**Comment by stephamon** [comment]
@kylelaffoon @ReneeRendon I thought we wanted to avoid specific billing information in How-To because these things can change rapidly and we don't want to present incorrect pricing?

**Comment by kylelaffoon** [comment]
Good point @stephamon.  @ReneeRendon We have customers getting confused on their bills with this service. Should we reach out to the rackspace.com team for more clarification up front?

**Comment by kylelaffoon** [comment]
This pricing information cannot be supported in the How-To.
