### ISSUE TITLE
Update Myrackspace two factor authentication article

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1363]
**Due on 8/23.**

From Charles Herrin:
"Hi Kyle,
 
Thanks for your help. I am attaching the word document with the content I would like replaced in the KB next Tuesday afternoon. We are releasing a new functionality with our multi-factor authentication. 
 
We currently have this article: https://support.rackspace.com/how-to/myrackspace-two-factor-authentication/
 
I would like to remove it and replace it with the attached content and have it renamed from “two-factor” to “multi-factor” to match the wording we now use. Is it possible to have this changed and go live next Tuesday the 23rd?
 
 
Regards,
Charles Herrin
Product Manager
myrackspace"

**Comment by kylelaffoon** [comment]
Generate PR #1383 and shared preview link with Kelly for her edits.

**Comment by kmsholcomb** [comment]
Hi @kylelaffoon. The PR that I was editing is closed, so I am attaching my edits to this issue. They are in the attached Word (and PDF) file. One thing I noticed was that the content referred to the Cloud Control Panel, but the Word doc that Charles sent (and the article that this article is replacing) is for the MyRackspace portal. So, in my edits, I referred to Charles' Word doc and assumed that references should be to the MyRackspace portal instead. If I got that wrong, then ignore any suggested edits that are not relevant. If you have any questions, please let me know. Thanks!

[Multi-factor authentication from the MyRackspace Control Panel_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/427450/Multi-factor.authentication.from.the.MyRackspace.Control.Panel_editsKH.pdf)
[Multi-factor authentication from the MyRackspace Control Panel_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/427451/Multi-factor.authentication.from.the.MyRackspace.Control.Panel_editsKH.docx)

**Comment by kylelaffoon** [comment]
@kmsholcomb My apologies for the disappearing PR. I had Strider issues. I will apply your edits ASAP.
