### ISSUE TITLE
Correct typo in Name Server IP address

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1365]
Url: https://support.rackspace.com/how-to/changing-dns-settings-on-linux/
 
In our article, Change DNS settings on Linux, we are listing the  DFW name server IP addresses as:
 
nameserver 73.3.128.240 
nameserver 72.3.128.241
 
Reached out to Nicole Hairston and Joe McBride to verify if this is a typo.

Is the 73.3.128.240 correct? Or should it be 72.3… ?
We may have entered this with a typo.
 
Original Notification:
From: Alan Bush <alan.bush@RACKSPACE.COM>
Date: Tuesday, August 16, 2016 at 8:47 AM
To: "how-to@rackspace.com" <How-To@rackspace.com>
Cc: Community <Community@RACKSPACE.COM>, Carlos Camarillo <Carlos.Camarillo@rackspace.com>
Subject: FW: Change DNS settings on Linux article
 
Hey How-To friends – can you look into the question Carlos presents below? It looks like there might be a typo on the 1st DFW nameserer IP Address.
 
Thanks,
 
Alan Bush
Technical Community Manager
501-7428
 
From: Carlos Camarillo <Carlos.Camarillo@rackspace.com>
Date: Sunday, August 14, 2016 at 11:32 AM
To: Rackspace Hosting <alan.bush@RACKSPACE.COM>
Subject: Change DNS settings on Linux article
 
Hello Alan,
 
I had a customer that entered a ticket to notify us of one of our support documents from support.rackspace.com.
The customer said that there is a possible typo for the name server IP addresses at :   https://support.rackspace.com/how-to/changing-dns-settings-on-linux/ 
 
Precisely the line " Dallas/Fort Worth (DFW)          nameserver 73.3.128.240 "
 
Can we get this reviewed and tested to make sure that the name server addresses that we should be recommending to the customers?
 
This is the ticket the customer entered : https://encore.rackspace.com/ticketing/account/758870/ticket/160814-dfw-0002932​
 
 
Regards,
 
 
Carlos Camarillo
Support Tech

**Comment by kylelaffoon** [comment]
Nicole copied Jason Bratton as the person who would know this.

**Comment by stephamon** [comment]
Hey @kylelaffoon if you aren't going to assign yourself to this one, can you be sure to post whatever information you get back so the team doesn't end up stepping over each other? :)

**Comment by kylelaffoon** [comment]
Jason replied with: 
"Hi team,
 
Sorry for the delayed response.  The customer is correct that it should be 72.3.128.240 and 72.3.128.241.  Would you mind to swap the order on a few of them?  I know it may not seem like that big of a deal, but customers will typically use them in the order we provide and it makes it easier if they consistently prefer what we expect.
 
In the case of HKG, I would like 120.136.32.62 to be before 120.136.32.63.
Likewise for SYD, I would like 119.9.60.62 to be before 119.9.60.63.
 
Thanks for your help!"

**Comment by kylelaffoon** [comment]
Completed by #1380
