### ISSUE TITLE
Create rackspace email webmail and outlook web access owa login widget 

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1367]
PR #1366 submitted by Tom Mitchell. He emailed in the referenced images that need to be uploaded according to our instructions.

This article has received a full SME review and will need an editorial review next.
- [x] SME review
- [x] Editorial review

**Comment by kylelaffoon** [comment]
From: Tom Mitchell <tom.mitchell@rackspace.com>
Date: Tuesday, August 16, 2016 at 10:13 AM
To: "how-to@rackspace.com" <How-To@rackspace.com>
Subject: New How-To article: Create rackspace-email-webmail-and-outlook-web-access-owa-login-widget #1366
 
Hey team!
 
I just created a new article called rackspace-email-webmail-and-outlook-web-access-owa-login-widget (#1366). In the article, it includes a few images which are referenced in the article with comments, as per the guide. They’re attached.
 
Additionally, this article includes a few snippets of code. In the code, it references other images, which we need to include in this article, and then we can update the img sources in the code itself to the new URLs for those images. All of those are attached as well. 
 
Let me know if you have any questions, or need anything else from me.
Thanks!
Tom
 
Tom 'Muscle' Mitchell
Cloud Office at Rackspace
![bg-200x220](https://cloud.githubusercontent.com/assets/5932812/17705895/a1f55352-639f-11e6-83a0-bf1e2cd1313e.png)
![bg-200x290](https://cloud.githubusercontent.com/assets/5932812/17705899/a1feb7e4-639f-11e6-9bc7-cb07f8f50313.png)
![bg-320x150](https://cloud.githubusercontent.com/assets/5932812/17705900/a204628e-639f-11e6-8fdf-e53352e3fba8.png)
![bg-350x210](https://cloud.githubusercontent.com/assets/5932812/17705898/a1fdf7e6-639f-11e6-9a9f-0f836026d426.png)
![bg-520x70](https://cloud.githubusercontent.com/assets/5932812/17705896/a1fbb68e-639f-11e6-96ea-3f5314c74431.png)
![bg-820x50](https://cloud.githubusercontent.com/assets/5932812/17705897/a1fce0e0-639f-11e6-888c-2cd6f3ad79cf.png)
![ftrnavnarrow520x70](https://cloud.githubusercontent.com/assets/5932812/17705901/a20fe67c-639f-11e6-8842-8ef47a4e72ae.png)
![ftrnavwide820x50](https://cloud.githubusercontent.com/assets/5932812/17705904/a21524a2-639f-11e6-90aa-54202a00373b.png)
![rackspace-logo](https://cloud.githubusercontent.com/assets/5932812/17705902/a21088f2-639f-11e6-98b2-cd29be978813.png)
![stdshort320x150](https://cloud.githubusercontent.com/assets/5932812/17705907/a23204c8-639f-11e6-8a5c-a97336001f2a.png)
![stdtall350x210](https://cloud.githubusercontent.com/assets/5932812/17705903/a213d7a0-639f-11e6-81e1-6aaddfc58924.png)
![vertshort200x220](https://cloud.githubusercontent.com/assets/5932812/17705905/a21960c6-639f-11e6-84d6-e9c0adfc2656.png)
![verttall200x290](https://cloud.githubusercontent.com/assets/5932812/17705906/a223f89c-639f-11e6-80b0-220870b1b5a5.png)

**Comment by kylelaffoon** [comment]
Ready for @kmsholcomb

**Comment by kmsholcomb** [comment]
Added inline comments to https://github.com/rackerlabs/rackspace-how-to/pull/1412.

**Comment by kylelaffoon** [comment]
Applied most of @kmsholcomb 's edits. Routed 2 larger questions to Tom and Milton (Tom's ooo contact). Milton requested we discuss the questions with Tom on his return on 09/05.

**Comment by kylelaffoon** [comment]
Received further clarification on command line image references. Reopening issue to apply these directions.

**Comment by kylelaffoon** [comment]
Modified code samples to list urls for RS Email maintained image files. Shared preview with Tom Mitchell.

**Comment by kylelaffoon** [comment]
Completed through PR #1475
