### ISSUE TITLE
Scrub repo for internal links

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1369]
Can you please scrub your public docs from having private, protected URLS listed?
    
    We should not be linking to internal tools.

**Comment by DonNateR** [comment]
I'll start searching for instances where we've linked to internal sources

**Comment by DonNateR** [comment]
Here's what we've deleted:

- Personal cell phone numbers
- one wiki links
- any information that could be confidential

I think that covers it.

**Comment by DonNateR** [comment]
Kyle and I deleted all instances of internal links/personal phone numbers. There's a small chance that we might run into a few we missed in closed issues of the repo. We tried our best to catch all of them, but keep an eye out for any in case we didn't. Let's consider this closed.
