### ISSUE TITLE
Wordpress article audit and possible new CMS article 

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1423]
Todd Archer noticed a lack of articles that answers the question, "What is the best approach for Wordpress [choose your CMS] staging/production workflow?"

Because there isn't enough content on this question, a few actions need to be taken to determine whether or not new content needs to be created. 
-  [x] Make a list of any published How-To articles concerning Wordpress and CMS.
- [x] Look through our archive of unpublished KC articles to see if Todd's question was answered in an old article.
-  [ ] If we cannot find an article that answers the question, work with Todd and the cloud launch team to create a new Rackspace specific CMS article.

Whether we are creating a new article or updating an old one, these ten items need to be touched upon in the article, or accounted for by the Cloud Launch team.
1. [First Orchestration Setup](https://community.rackspace.com/developers/f/7/t/4998)
2. Non-Orchestration
3. With Config-Management/CICD there’s quite a bit but for those who have not been introduced to automation?
4. Using the same database for staging and production? Caveats? How? Why/why not?
5. Alternate Vhosts for Staging/Production? (Staging=dev.domain.com; Prod= domain.com)  vs.  Separate Staging/Production Servers?
6. How to use Cloud Images for Staging/production?
7. Load Balancers role and management?
8. Lsyncd / Gluster
9. NFS… Why/why not 
10. Cloud Files Role and benefits

This issue will act as the source of truth, but remember to email Todd on the email thread he started when you have any updates.

**Comment by cyrichardson** [comment]
@DonNateR I believe there used to be such an article but maybe it didn't move over with the migration. I don't know if you can go back and check unmigrated stuff, but if you can, you might check there.

**Comment by kylelaffoon** [comment]
Assembled list of currently published and articles not yet migrated for WordPress on the wiki. These lists have been de-duplicated. I will assemble the same for CMS on Monday and then share the results with the team.

**Comment by aaronmehar** [comment]
@DonNateR  I have been working on a new article for Wordpress and Autoscale, that might be good for this. Its called Autoscaling and Autorecovering your Wordpress site.

**Comment by DonNateR** [comment]
@aaronmehar: That would be awesome. Do you have an ETA for a draft of that article?

**Comment by DonNateR** [comment]
Have not heard back from Aaron yet.

**Comment by DonNateR** [comment]
Here's a list of Wordpress related articles, and what qualifications they fulfill on Todd's list. These do not include any cloud sites articles: 

**Non- orchestration**

- [CMS comparison](https://github.com/rackerlabs/rackspace-how-to/blob/2a455bf518c9669f60e96abfc7b00caccfc09aec/content/cloud-sites/cms-comparison-drupal-joomla-and-wordpress.md)

- [Migrating a LAMP Stack to AWS](https://github.com/rackerlabs/rackspace-how-to/blob/2a455bf518c9669f60e96abfc7b00caccfc09aec/content/cloud-servers/migrating-an-application-built-on-a-lamp-stack-from-amazon-web-services.md)

- *Audited* [Open Cloud Reference Architecture Diagram](https://github.com/rackerlabs/rackspace-how-to/blob/2a455bf518c9669f60e96abfc7b00caccfc09aec/content/cloud-servers/rackspace-open-cloud-reference-architecture.md)


**Alternate v-hosts for staging production**

- *Audited* [Serve Multiple domains using virtual hosts]https://github.com/rackerlabs/rackspace-how-to/blob/2a455bf518c9669f60e96abfc7b00caccfc09aec/content/cloud-servers/serve-multiple-domains-using-virtual-hosts.md

**Orchestration/Start-Up**

- [Quick set-up with Cloud Orchestration](https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-orchestration/quick-set-up-with-rackspace-cloud-orchestration.md)

- [Deploy Wordpress Packages using Cloud Orchestration](https://github.com/rackerlabs/rackspace-how-to/blob/2a455bf518c9669f60e96abfc7b00caccfc09aec/content/cloud-orchestration/deploy-wordpress-packages-by-using-rackspace-cloud-orchestration.md)

**Databases for staging and production** (though no mention of benefits/downsides)

-  [Add another Wordpress site to an existing Cloud Orchestration stack](https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-orchestration/add-another-wordpress-site-to-an-existing-cloud-orchestration-stack.md)

**Lsyncd** (No mention of gluster)

- [How to scale multinode Wordpress sites using orchestration](https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-orchestration/how-to-scale-multinode-wordpress-by-using-rackspace-orchestration.md)

**Cloud Files Benefits**

- [Configure w3 total cache for Wordpress with Cloud Files](https://github.com/rackerlabs/rackspace-how-to/blob/2a455bf518c9669f60e96abfc7b00caccfc09aec/content/cloud-files/configure-w3-total-cache-for-wordpress-with-rackspace-cloud-files-cdn.md)

- [Accelerating Wordpress with cloud files](https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-files/accelerating-wordpress-with-cloud-files-cdn-and-the-w3-total-cache-plugin.md)

- [Synchronize to Cloud Files with File Conveyer](https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-files/synchronizing-files-to-cloud-files-with-fileconveyor.md)


This leaves four items from the initial list that aren't covered in great detail:

- With Config-Management/CICD there’s quite a bit but for those who have not been introduced to automation?

- Using the same database for staging and production? Caveats? How? Why/why not?

- How to use Cloud Images for Staging/production?

- Load Balancers role and management?

- NFS… Why/why not

Full audits will likely need to be performed on all articles that aren't already audited (**9 articles total**). However, the question becomes is which articles can be modified to add the information above, or if a new article will need to be written addressing each. Will consult Todd.

**Comment by DonNateR** [comment]
Need to reach out to another SME.

**Comment by DonNateR** [comment]
Add article's that need audits from this list to How-To backlog. See the preceding links.
