### ISSUE TITLE
Full audit: Installing active dir domain svcs Windows 2008 r2

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1431]
Full audit needed.

https://github.com/rackerlabs/rackspace-how-to/blob/6bc35da8ac3d55cba758cd6522fb36ebc01c8a45/content/cloud-servers/installing-active-directory-domain-services-on-windows-server-2008-r2-enterprise-64-bit.md

This page ranks 21 in most viewed articles.

- [x] SME check
- [x] Editor check
- [ ] update `audit_date`

**Comment by kylelaffoon** [comment]
Shared this Issue with Esc-Echo list for SME review.

**Comment by kylelaffoon** [comment]
From Ben Temple's review I updated the heading "Enable remote registry" to read "Enable Remote Management." Title caps were used for registered product name.

**Comment by kylelaffoon** [comment]
Ready for @kmsholcomb 's review

**Comment by kmsholcomb** [comment]
Thanks @kylelaffoon. I will get to it first thing in the morning.

**Comment by kmsholcomb** [comment]
Hi @kylelaffoon. My suggested edits are in the attached Word doc (and PDF copy of it). Please let me know if you have any questions. Thanks!

[Install Active Directory Domain Services on Windows Server 2008 R2 Enterprise 64 bit_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/462420/Install.Active.Directory.Domain.Services.on.Windows.Server.2008.R2.Enterprise.64.bit_editsKH.pdf)
[Install Active Directory Domain Services on Windows Server 2008 R2 Enterprise 64 bit_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/462419/Install.Active.Directory.Domain.Services.on.Windows.Server.2008.R2.Enterprise.64.bit_editsKH.docx)
