### ISSUE TITLE
Full audit: Checking running services on Linux

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1432]
This audit needed.

https://github.com/rackerlabs/rackspace-how-to/blob/64a957cceaf308299368da8d8ebe2b78295c7428/content/cloud-servers/checking-running-services-on-linux.md

This page ranks 22 in most viewed articles.

**Comment by kylelaffoon** [comment]
Shared this Issue with Esc-Echo list for SME review.

**Comment by kylelaffoon** [comment]
Sent second request to Esc-Echo list, since #1431 was adopted yesterday, but not this one.

**Comment by kylelaffoon** [comment]
Will meet with Mitch Armistead on Wednesday, September 14th to discuss specific commands to list.

**Comment by DonNateR** [comment]
@kylelaffoon: How was the meeting with Mitch?
