### ISSUE TITLE
Full audit: Connecting to a server using SSH on Linux or Mac OS

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1433]
Full audit needed.

https://github.com/rackerlabs/rackspace-how-to/blob/3a1798e3176cb5f98dd53154ec38a9de95d74f06/content/cloud-servers/connecting-to-a-server-using-ssh-on-linux-or-mac-os.md

This article ranks 23 in most viewed articles.

**Comment by stephamon** [comment]
- [ ] SME check
- [ ] Editor check
- [ ] Update `audit_date`

**Comment by stephamon** [comment]
@kmsholcomb Can you add this one to your list for an edit? I'm sure you've looked at it before, but it's been at *least* six months :)

**Comment by kmsholcomb** [comment]
Will do, @stephamon

**Comment by kmsholcomb** [comment]
Hi @stephamon. The attached file (Word or PDF) contains some suggested edits and comments. Please let me know if you have any questions. Thanks!

[Connect to a server using SSH on Linux or Mac OS_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/475054/Connect.to.a.server.using.SSH.on.Linux.or.Mac.OS_editsKH.pdf)
[Connect to a server using SSH on Linux or Mac OS_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/475055/Connect.to.a.server.using.SSH.on.Linux.or.Mac.OS_editsKH.docx)
