### ISSUE TITLE
Full audit: How to serve multiple domains using virtual hosts

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1434]
Full audit needed.

https://github.com/rackerlabs/rackspace-how-to/blob/3a1798e3176cb5f98dd53154ec38a9de95d74f06/content/cloud-servers/how-to-serve-multiple-domains-using-virtual-hosts.md

This article ranks 25 in most viewed articles.

**Comment by DonNateR** [comment]
Emailed Nicole Hariston to see if she will act as a SME for this article.

**Comment by kmsholcomb** [comment]
Hi @DonNateR. The attached Word doc (and PDF copy of it) contains my suggested markup. I really tried to cut out as much verbiage as I could, and I have a suggestion in the doc for cutting out even more. It all depends on who the audience is. Additionally, we could also consider dividing this into two articles, one that explains how to set up multiple virtual hosts and one that explains how to troubleshoot multiple virtual hosts (and linking them to one another). However, if this is a top-25 viewed article, perhaps having the information all together has proved useful? Well, the article has a ton of edits, so please let me know if you have any questions. Thanks!

[Serve Multiple Domains By Using Virtual Hosts_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/483026/Serve.Multiple.Domains.By.Using.Virtual.Hosts_editsKH.pdf)
[Serve Multiple Domains By Using Virtual Hosts_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/483027/Serve.Multiple.Domains.By.Using.Virtual.Hosts_editsKH.docx)
