### ISSUE TITLE
Full audit: Test and send mail using PHP

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1435]
Full audit needed.

https://github.com/rackerlabs/rackspace-how-to/blob/d178f40de688032c0e52055d04bea5fb9dfa7aa8/content/cloud-sites/test-and-send-mail-using-php.md

This article ranks 26 in most viewed articles.

**Comment by DonNateR** [comment]
Cloud Sites articles will undergo their own transformation separate from the audits we are doing here. As a result, I am closing this issue.
