### ISSUE TITLE
Metrics - Create getting started guide for Graphite user 

### ISSUE THREAD

**Issue by wolfdancer** [rackerlabs/rackspace-how-to#1471]
Metrics team will provide initial content for this.  We are getting Graphite users looking at the metrics service and would like to provide a guide for these users.

**Comment by stephamon** [comment]
Emailed Shane to follow up.

**Comment by stephamon** [comment]
Talked to Shane about this, and it's still more of a concept rather than a concrete article. Am labeling with blocked and will check in with Shane again next week.

**Comment by stephamon** [comment]
Shane's team plans to get this added to an upcoming sprint, so I anticipate an article in the next month or so.

**Comment by wolfdancer** [comment]
Hi I am very sorry of the extra work if this issue has caused.  Would it be better to close this for now and you should either see an issue to work with you on this further or a PR submitted?

**Comment by stephamon** [comment]
@wolfdancer I don't mind keeping the issue around until it's ready to be worked on :)

**Comment by stephamon** [comment]
I'm going to go ahead and close this for now, since there's not a clear idea of when this will be worked on.
