### ISSUE TITLE
Organize Cloud Office Control Panel content to be easier to locate and navigate through

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-how-to#1486]
Audit Control Panel content, both product and non-product specific.

**Comment by ReneeRendon** [comment]
Need to come to a conclusion regarding the CP section during sprint 17.

**Comment by ReneeRendon** [comment]
How many articles are CP related in Cloud Office?

**Comment by stephamon** [comment]
@ReneeRendon I'll pull together a list today or tomorrow that we can use.

**Comment by stephamon** [comment]
Cloud Office Control Panel articles are listed here: https://docs.google.com/spreadsheets/d/1UX-Z7EOp0eJIvPGbGg1GVZTNwcE1RAC9K30p9l3PFVg/edit#gid=0

**Comment by stephamon** [comment]
Pull out articles that are common to more than one product from above list.
