### ISSUE TITLE
python-novaclient: OS_AUTH_SYSTEM=rackspace is deprecated

### ISSUE THREAD

**Issue by joeashcraft** [rackerlabs/rackspace-how-to#1509]
It seems that the "OS_AUTH_SYSTEM" env variable is deprecated. As such, the instructions in [this article](https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-servers/installing-python-novaclient-on-linux-and-mac-os.md) no longer work.
I would expect [this article](https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-servers/installing-python-novaclient-on-windows.md) to be broken, too, for the same reason; though I can't test on Windows to confirm.

**Expected Result**: `nova image-list` should return a list of server images.

**Actual Result**:
```bash
$ nova image-list
./lib/python2.7/site-packages/novaclient/shell.py:696: UserWarning: novaclient auth plugins that are not keystone are deprecated. Auth plugins should now be done as plugins to keystoneauth and selected with --os-auth-type or OS_AUTH_TYPE
  'novaclient auth plugins that are not keystone are deprecated.'
ERROR (AuthSystemNotFound): AuthSystemNotFound: 'rackspace'
```

**Comment by joeashcraft** [comment]
I missed the requirements for `rackspace-auth-openstack` (or metapackage `rackspace-novaclient`) when I read thru the instructions.

**Installing the dependencies causes this all to work as expected!**

**Comment by DonNateR** [comment]
@joeashcraft: Thanks for staying on top of this!
