### ISSUE TITLE
Update RPC how-to page with v13

### ISSUE THREAD

**Issue by klevenstein** [rackerlabs/rackspace-how-to#1513]
Need to add a v13 section to the RPC OpenStack How-To page:

https://support.rackspace.com/how-to/rpc-openstack/

**Comment by DonNateR** [comment]
Check the RPC v13 release notes.

**Comment by catlook** [comment]
release notes: https://developer.rackspace.com/docs/private-cloud/rpc/v13/rpc-releasenotes/
