### ISSUE TITLE
Redirect white paper

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1519]
These two redirects need to be corrected.

1. Redirect support.rackspace.com/white-paper/systems-management-simplified-in-the-cloud-0/ URL to how-to/systems-management-simplified-in-the-cloud/

2. Redirect support.rackspace.com/white-paper/systems-management-simplified-in-the-cloud/ URL to how-to/systems-management-simplified-in-the-cloud/

*This whitepaper is listed twice in the populated list of articles here on page 10. https://support.rackspace.com/white-paper/white-paper-all-articles/#

https://github.com/rackerlabs/nexus-control/blob/master/config/rewrites.d/support.rackspace.com.json

**Comment by catlook** [comment]
Phase one:  deleted following redirects:

      {
        "description": "Redirect support.rackspace.com/white-paper/systems-management-simplified-in-the-cloud-0/ URL to how-to/systems-management-simplified-in-the-cloud/ ",
        "from": "^\\/white-paper\\/systems-management-simplified-in-the-cloud-0(.*)$",
        "to": "/how-to/systems-management-simplified-in-the-cloud/",
        "rewrite": false,
        "status": 301
      },
      {
        "description": "Redirect support.rackspace.com/white-paper/systems-management-simplified-in-the-cloud/ URL to how-to/systems-management-simplified-in-the-cloud/ ",
        "from": "^\\/white-paper\\/systems-management-simplified-in-the-cloud(.*)$",
        "to": "/how-to/systems-management-simplified-in-the-cloud/",
        "rewrite": false,
        "status": 301
      },

If using original links after this is done is too ugly, I'll put them back in redirecting to our article doesn't exist bucket.

**Comment by catlook** [comment]
Well, the article does exist, but is defunct.  So..deleting paper and redirecting to retired bucket.

**Comment by catlook** [comment]
deletes are https://github.com/rackerlabs/rackspace-white-paper/pull/28 and https://github.com/rackerlabs/rackspace-white-paper/pull/29

**Comment by catlook** [comment]
Associated nexus and whitepaper PRs are merged!
