### ISSUE TITLE
Correct support landing page items

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1524]
Any items in this list that require CDN access should be transferred to issue #1523

- [x] Remove “Get Started with Cloud Sites”

- [x] Fix link on top navigation bar: API Documentation needs to go to Developer doc (https://developer.rackspace.com/docs/)

- [ ] Getting Started Using the Rackspace Managed Cloud needs to be changed to our newest priorities and most looked for documentation. (We need to discuss our new priorities for this section.)

- [x] In Getting Started Using the Rackspace Managed Cloud, need to remove “Get Started with Cloud Sites”.

- [x] “Secure your server” points to a KC article. Needs to point to How-To.

- [x] “Create an image of your server” points to a KC article. Needs to point to How-To.

- [x] “Configure Cloud Backup” points to KC articles. Needs to point to How-To.

- [x] “Upload content to Cloud Files” points to a KC article. Needs to point to How-To.

- [x] Word Press points to a KC article. Needs to point to How-To.

- [x] The product icons in the carousel point to KC. Need to point to How-To.

- [x] Cloud servers image icon missing in product carousel

**Comment by DonNateR** [comment]
Move any that can't be fixed to issue #1423

**Comment by catlook** [comment]
I assume this is the support landing page: https://support.rackspace.com/.
In what repo does it live?

**Comment by DonNateR** [comment]
@catlook: That is correct!

**Comment by catlook** [comment]
What do you mean, cloud servers image is missing from carousel?  Maybe this one was already fixed but not checked off from the list?

**Comment by catlook** [comment]
Do we have the new priorities from the checklist above?

**Comment by stephamon** [comment]
@catlook I don't think we've talked about what articles to link instead yet. Also, I had thought the carousel was something that was tied into the CDN thing? 

If this is the carousel, it appears to be all there:
![screen shot 2016-10-25 at 12 34 09 pm](https://cloud.githubusercontent.com/assets/12717324/19697038/5fdd6968-9aaf-11e6-8c5f-ecb18487a1ce.png)

**Comment by DonNateR** [comment]
@catlook: The carousel is tied to CDN. We won't be able to update the carousel's links do I wouldn't worry about them. 

That being said, the Cloud Server's icon is appearing for me as well (though it hasn't in the past).

**Comment by catlook** [comment]
hmm...i made changes to carousel from teh support page repo...let me commit and see what builds :)  Thanks y'all!!

**Comment by DonNateR** [comment]
It;s worth a shot. Didn't work I  when tried though. I suspect that the carousel may be it's own separate container or apart of the footer-as-service-containers.

**Comment by catlook** [comment]
Support PR https://github.com/rackerlabs/docs-support-network/pull/24

**Comment by catlook** [comment]
Adding blocked label while we work out details for Getting Started Using the Rackspace Managed Cloud needs to be changed to our newest priorities and most looked for documentation. (We need to discuss our new priorities for this section.)   Leaving it milestone 18 though.
