### ISSUE TITLE
Full audit: Configuring MS SQL server for remote access

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1525]
https://github.com/rackerlabs/rackspace-how-to/blob/2a455bf518c9669f60e96abfc7b00caccfc09aec/content/cloud-servers/configuring-ms-sql-server-for-remote-access.md
- [x] SME check
- [x]  Editor check
- [ ] Quality checklist
- [ ]  update audit_date

**Comment by stephamon** [comment]
Emailed Sameer for review.

**Comment by stephamon** [comment]
Got confirmation that this is still up-to-date. @kmsholcomb Can you add it to your list to edit, please?

**Comment by kmsholcomb** [comment]
Will do, @stephamon. I'll probably get to it tomorrow.

**Comment by kmsholcomb** [comment]
Hi @stephamon. My suggested edits are in the attached Word doc (and PDF copy of it). I suggested quite a few changes. It might be worth running by a SME again, just to ensure that the changes don't change the technical accuracy! Let me know if you have any questions. Thanks!

[Troubleshoot remote access to SQL Server_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/586384/Troubleshoot.remote.access.to.SQL.Server_editsKH.pdf)
[Troubleshoot remote access to SQL Server_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/586385/Troubleshoot.remote.access.to.SQL.Server_editsKH.docx)
