### ISSUE TITLE
Full audit: RPC-MS FAQ

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1527]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/rpc-microsoft/rpc-microsoft-faq.md
- [x] SME check
- [x]  Editor check
- [x] Quality checklist
- [x]  update audit_date

**Comment by meker12** [comment]
10/19 Sent e-mail to Gerry Le Canu requesting SME review.
