### ISSUE TITLE
Full audit: Install MySQL on Windows server 2008 r2 and 2012

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1528]
https://github.com/rackerlabs/rackspace-how-to/blob/2a455bf518c9669f60e96abfc7b00caccfc09aec/content/cloud-servers/install-mysql-on-windows-server-2008-r2-and-2012.md
- [x] SME check
- [x]  Editor check
- [x] Quality checklist
- [x]  update audit_date

**Comment by catlook** [comment]
Ok, I ran through all the steps and they went swimmingly.  I can't actually start MySQL, but that may be the c=fact that it's a new server.  maybe missing something.  Still need to find a SME

**Comment by catlook** [comment]
Sent SME email to Jimmy Rudley.

**Comment by catlook** [comment]
Per Jimmy:
Hi Cat,
 
Using the web platform installer is a pretty straight forward process, so I can tell you it is safe to say that it will work. The content is sort of straight and to the point. So, if a person is looking quickly how to get mysql running in windows, this will do the trick. If they are trying to understand the process in detail, this could use some more content.
 
Thanks,
Jimmy

**Comment by kmsholcomb** [comment]
Hi @catlook. True to form, I had a few nitpicky edits. See the attached Word doc (or its PDF copy). Thanks!

[Install MySQL on Windows Server 2008 R2 and 2012_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/607004/Install.MySQL.on.Windows.Server.2008.R2.and.2012_editsKH.pdf)
[Install MySQL on Windows Server 2008 R2 and 2012_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/607005/Install.MySQL.on.Windows.Server.2008.R2.and.2012_editsKH.docx)

**Comment by catlook** [comment]
Closed with pr #1640
