### ISSUE TITLE
Full audit: Cloud Servers with managed operations support for windows

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1529]
https://github.com/rackerlabs/rackspace-how-to/blob/2a455bf518c9669f60e96abfc7b00caccfc09aec/content/managed-operations/cloud-servers-with-managed-operations-support-for-windows.md
- [ ] SME check
- [ ] Editor check
- [ ] Quality checklist
- [ ] Update audit_date

**Comment by stephamon** [comment]
Emailed Dusty for SME review.

**Comment by stephamon** [comment]
The SOS for both Linux and Windows are being refreshed, which should be concluded in Q1 2017. We should reach back out about these articles then.

**Comment by stephamon** [comment]
Revive email conversation to get a more specific date on when this article can be updated.

**Comment by catlook** [comment]
From: Scot Stine <scot.stine@RACKSPACE.COM>
Date: Tuesday, January 10, 2017 at 3:49 PM
To: Jen Williams <jennifer.williams@rackspace.com>, Cat Lookabaugh <cat.lookabaugh@RACKSPACE.COM>
Cc: Rick Hernandez <rick.hernandez@rackspace.com>, Hounsou Dansou <hounsou.dansou@RACKSPACE.COM>
Subject: RE: Response requested by 1/11/2017: How-to article review request
 
Thanks Jen!
 
Hey Cat!
 
  Rick Hernandez is one of our Process Standardization experts. Hounsou Dansou is our resident Cloud Expert. I will have these guys review the articles you noted and see if they should be modified in any way.

Hounsou gets back from PTO on Monday and will need a few days to review. Probably next Friday (1/20) would be a better deadline.
 
Thanks,

Scot

**Comment by catlook** [comment]
closed with https://github.com/rackerlabs/rackspace-how-to/pull/1791
