### ISSUE TITLE
Full audit: Cloud Servers with managed operations support for linux

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1530]
https://github.com/rackerlabs/rackspace-how-to/blob/2a455bf518c9669f60e96abfc7b00caccfc09aec/content/managed-operations/cloud-servers-with-managed-operations-support-for-windows.md
- [ ] SME check
- [ ] Editor check
- [ ] Quality checklist
- [ ] Update audit_date

**Comment by stephamon** [comment]
Emailed Dusty for SME review.

**Comment by stephamon** [comment]
The SOS for both Linux and Windows are being refreshed, which should be concluded in Q1 2017. We should reach back out about these articles then.

**Comment by DonNateR** [comment]
Now on issue #1631
