### ISSUE TITLE
Full audit: Architecture reqs for RPC powered by MS

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1531]
https://github.com/rackerlabs/rackspace-how-to/blob/2a455bf518c9669f60e96abfc7b00caccfc09aec/content/rpc-microsoft/architecture-requirements-for-rackspace-private-cloud-powered-by-microsoft.md

- [x] SME check
- [ ] Editor check
- [x] Quality checklist
- [x] update audit_date

**Comment by RobinJoe** [comment]
10/14 - Audit date updated. One edit completed, ready for other reviewers to check. SME check still pending.

**Comment by RobinJoe** [comment]
SME contact emails sent - Author **Gerry Le Canu** and **DevEx mailing list**.

**Comment by meker12** [comment]
@RobinJoe  Since you have already contacted the SME, it makes sense for you to take the FAQ article as well.   It's issue #1527.   I sent an e-mail requesting audit. I'll follow up on that to ask that the FAQ be added to your initial request.

**Comment by RobinJoe** [comment]
@meker12 Okay, we've had a response from the SME, and I've added the FAQ edits into the sections where suggested. 

21/10 SME additions on FAQ complete. Editor and Quality checklist still pending.

**Comment by RobinJoe** [comment]
24/10 Quality checklist completed.
