### ISSUE TITLE
Full audit: Windows server security best practices

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1535]
https://github.com/rackerlabs/rackspace-how-to/blob/2a455bf518c9669f60e96abfc7b00caccfc09aec/content/cloud-servers/windows-server-security-best-practices.md
- [x] SME check
- [x] Editor check
- [ ] Quality checklist
- [x] Update audit_date

**Comment by DonNateR** [comment]
Managed security team might be a good place to start.

**Comment by kmsholcomb** [comment]
Hi @DonNateR. My suggested edits for the article are in the attached Word doc (and PDF copy of it). I tried to tighten up the language a bit and break up the paragraphs into smaller ones. Please let me know if you have any questions. Thanks!

[Windows Server security best practices_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/595183/Windows.Server.security.best.practices_editsKH.pdf)
[Windows Server security best practices_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/595184/Windows.Server.security.best.practices_editsKH.docx)
