### ISSUE TITLE
Full audit: Troubleshooting alarms

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1536]
https://github.com/rackerlabs/rackspace-how-to/blob/2a455bf518c9669f60e96abfc7b00caccfc09aec/content/rackspace-monitoring/troubleshooting-alarms.md
- [x] SME check
- [x] Editor check
- [x] Quality checklist
- [x] Update audit_date

**Comment by DonNateR** [comment]
Complete
