### ISSUE TITLE
Retire article (First Gen)

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1537]
https://github.com/rackerlabs/rackspace-how-to/blob/2a455bf518c9669f60e96abfc7b00caccfc09aec/content/cloud-servers/next-generation-cloud-servers-migration-considerations-and-options.md

I believe this article should have been retired with all of the other First Gen articles. May want to double check with Trey Hoehne first.

**Comment by catlook** [comment]
It is already redirected, so deleting it!
