### ISSUE TITLE
Create "Cloud server imaging steps & FAQ" article

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1546]
Reese McJunkin authored the word document attached to this issue.

The articles needs to be converted to markdown, edited, and published.

[Cloud Server Imaging Steps & Info.docx](https://github.com/rackerlabs/rackspace-how-to/files/527689/Cloud.Server.Imaging.Steps.Info.docx)

**Comment by catlook** [comment]
PR https://github.com/rackerlabs/rackspace-how-to/pull/1557

**Comment by catlook** [comment]
done!
