### ISSUE TITLE
Possibly duplicate articles about email archiving

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-how-to#1559]
I'm pretty sure the following articles are duplicates, although one is probably more correct than the other. We need to reach out to the Cloud Office team to find out which one is most valid and make sure it's up to date.
- https://github.com/rackerlabs/rackspace-how-to/blob/2a455bf518c9669f60e96abfc7b00caccfc09aec/content/rackspace-email/enable-email-archiving-cloud-office-control-panel.md
- https://github.com/rackerlabs/rackspace-how-to/blob/2a455bf518c9669f60e96abfc7b00caccfc09aec/content/rackspace-email-archiving/enable-email-archiving.md

**Comment by catlook** [comment]
I'm taking Friday off, but I'll see if we can  get the question asked and answered (if not acted on) this week!

**Comment by catlook** [comment]
Does the duplicate label refer to duplicate issues or duplicate articles?

**Comment by stephamon** [comment]
@catlook I put it on there to refer to duplicate articles, but it's my first time using it, so it's possible that it was intended for duplicate issues.

**Comment by catlook** [comment]
Hey..it's our repo!! We can use it however we want.  We can discuss at team meet on Wed.  Will leave it for now!

**Comment by catlook** [comment]
cody jobson ?   cloud office contact.

**Comment by stephamon** [comment]
@catlook Yes Cody would be a good starting point for this :)

**Comment by catlook** [comment]
email to Cody sent...awaiting response.  I recommended keeping the non-screenshot version if it is clear, complete, and correct.

**Comment by catlook** [comment]
from austin miller and ea_content@rackspace.com (coe content list):

Looking over both articles 
https://github.com/rackerlabs/rackspace-how-to/blob/2a455bf518c9669f60e96abfc7b00caccfc09aec/content/rackspace-email/enable-email-archiving-cloud-office-control-panel.md would give the customer that fast track and most accurate way to enable archiving. 

If you have an further questions please feel free to reach out!
---------
will fix monday

**Comment by catlook** [comment]
pretty sure i closed by accident...verifying

**Comment by catlook** [comment]
Done!  (tried a redirect of old article but it did bad things and so got reverted).
