### ISSUE TITLE
Full audit: CMS comparison

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1572]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-sites/cms-comparison-drupal-joomla-and-wordpress.md

Each step must be performed in order for an article to be considered audited:

- [x] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [ ] Editor check: Incorporate edits from Kelly Holcomb
- [ ] Quality Checklist: Perform a quality audit of the article using the quality checklist 
- [ ] Update audit_date: Update the `audit_date` metadata in the article with the date of the full audit's completion

See issue #1423  for more information.

**Comment by DonNateR** [comment]
Received SME review from members of Cloud Office team.

**Comment by kmsholcomb** [comment]
Hi @DonNateR. My suggested edits are attached. Mainly I just tried to get rid of excessive verbiage! Please let me know if you have any questions. Thanks!

[CMS comparison Drupal Joomla Wordpress_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/619835/CMS.comparison.Drupal.Joomla.Wordpress_editsKH.pdf)
[CMS comparison Drupal Joomla Wordpress_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/619834/CMS.comparison.Drupal.Joomla.Wordpress_editsKH.docx)

**Comment by DonNateR** [comment]
Closed since this is a Cloud Sites article
