### ISSUE TITLE
Full audit: Migrate a LAMP stack from AWS

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1573]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-servers/migrating-an-application-built-on-a-lamp-stack-from-amazon-web-services.md

Each step must be performed in order for an article to be considered audited:

- [ ] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [ ] Editor check: Incorporate edits from Kelly Holcomb
- [ ] Quality Checklist: Perform a quality audit of the article using the quality checklist
- [ ] Update audit_date: Update the `audit_date` metadata in the article with the date of the full audit's completion

See issue #1423  for more information.

**Comment by ReneeRendon** [comment]
Let's wait to see the migration situation before we move forward with this audit.

**Comment by DonNateR** [comment]
The article has been retired. However, it remains in the repo until we determine how to archive retired articles.
