### ISSUE TITLE
Full audit: Quick set-up with Cloud Orchestration

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1574]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-orchestration/quick-set-up-with-rackspace-cloud-orchestration.md

Each step must be performed in order for an article to be considered audited:

- [x] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [x] Editor check: Incorporate edits from Kelly Holcomb
- [x] Quality Checklist: Perform a quality audit of the article using the quality checklist
- [x] Update audit_date: Update the `audit_date` metadata in the article with the date of the full audit's completion

See issue #1423  for more information.

**Comment by catlook** [comment]
email sent to chris hultin asking for SME assistance.

**Comment by catlook** [comment]
You reached the Cloud Orchestration SME :slightly_smiling_face:  Looking at the article now

Cat Lookabaugh	[4:08 PM]  
Ha...got lucky on that one...sweet!!  :lollipop: Thanks..i promise not to abuse you ... too much!

Chris Hultin	[4:08 PM]  
Eh, just know that between now and January Heat/Orchestration is NOT my priority, so you’ll get attention while automated things run.

[4:09]  
That article seems pretty solid.  As long as the buttons haven’t changed, it looks OK to me.

Cat Lookabaugh	[4:09 PM]  
no sweat...if you can just give me an ETA when I pop on on your radar, I'll deal with it :slightly_smiling_face:

[4:10]  
Great, will you confirm the buttons or can I see that for myself?

Chris Hultin	[4:10 PM]  
You should be able to just walk through those steps yourself in MyCloud.

**Comment by catlook** [comment]
I'll walk through steps and compare screenshots.

**Comment by catlook** [comment]
Made my edits based on walk trough and applied Kelly's edits.
