### ISSUE TITLE
Full audit: Scale multinode Wordpress sites using orchestration 

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1577]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-orchestration/how-to-scale-multinode-wordpress-by-using-rackspace-orchestration.md

Each step must be performed in order for an article to be considered audited:

- [x] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [x] Editor check: Incorporate edits from Kelly Holcomb
- [x] Quality Checklist: Perform a quality audit of the article using the quality checklist 
- [x] Update audit_date: Update the `audit_date` metadata in the article with the date of the full audit's completion

See issue #1423  for more information.

**Comment by catlook** [comment]
My focus has shifted to whitepapers, so I surrender this one.

**Comment by nimbinatus** [comment]
Email sent to Arun

**Comment by nimbinatus** [comment]
reminder email out to Arun

**Comment by nimbinatus** [comment]
Reached out to Aaron to find another SME

**Comment by nimbinatus** [comment]
rec'd ok from Aaron! Moving along :)

**Comment by nimbinatus** [comment]
Edit and QC complete; posting for merge
