### ISSUE TITLE
Full audit: Configure w3 total cache for Wordpress with Cloud Files

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1578]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-files/configure-w3-total-cache-for-wordpress-with-rackspace-cloud-files-cdn.md

Each step must be performed in order for an article to be considered audited:

- [x] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [ ] Editor check: Incorporate edits from Kelly Holcomb
- [ ] Quality Checklist: Perform a quality audit of the article using the quality checklist
- [ ] Update audit_date: Update the `audit_date` metadata in the article with the date of the full audit's completion

See issue #1423  for more information.

**Comment by stephamon** [comment]
Melissa is looking around for a SME for me.

**Comment by stephamon** [comment]
Melissa doesn't have anyone on her team that uses this tool. I've asked if she thinks we should retire it, but I'll check with Joe's contact as well.

**Comment by stephamon** [comment]
Sent an email to Eric C., who wrote the article originally, to see if he's still available to work with us on keeping the article up-to-date. 

If he's not able or uninterested, I'll pass on to Stuart to see if he wants to put it in Community instead.

**Comment by stephamon** [comment]
Sent a follow up email to James L. and Eric C. on Monday, but still no response from either about this one. I'll send another email on Thursday, and if that doesn't produce a result, I'll pass to Community and retire it.

**Comment by stephamon** [comment]
James L. suggested trying the LInux techs list to find someone who has more practical experience with the w3TC tool.

**Comment by stephamon** [comment]
Remove reference and link to Cloud Sites.
