### ISSUE TITLE
Full audit: Synchronize to Cloud Files with File Conveyer

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1580]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-files/synchronizing-files-to-cloud-files-with-fileconveyor.md

Each step must be performed in order for an article to be considered audited:

- [ ] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [ ] Editor check: Incorporate edits from Kelly Holcomb
- [ ] Quality Checklist: Perform a quality audit of the article using the quality checklist
- [ ] Update audit_date: Update the `audit_date` metadata in the article with the date of the full audit's completion

See issue #1423  for more information.

**Comment by stephamon** [comment]
Melissa is checking for a SME for me.

**Comment by stephamon** [comment]
Melissa doesn't have anyone on her team that uses this tool. Asking if she recommends that we retire it.
