### ISSUE TITLE
Update RPC doc article to include v13

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-how-to#1583]
https://support.rackspace.com/how-to/rackspace-private-cloud-documentation/

Should include links to v13. 

Should we alternatively consider nixing the article and redirecting to https://developer.rackspace.com/docs/#docs-private-cloud to avoid having to maintain it?

**Comment by asettle** [comment]
@catlook @stephamon - completely agree with nixing the article and redirecting. 
My only other suggestion would be maintaining a simple "this is what RPCO is" (real basic) and then a link to the page.

**Comment by catlook** [comment]
Deal :)  Mini article pointing to docs resource!

**Comment by catlook** [comment]
done
