### ISSUE TITLE
GlusterFS through CTDB - out of date links and recommendations

### ISSUE THREAD

**Issue by albush** [rackerlabs/rackspace-how-to#1607]
Please review recommended changes submitted in Rackspace Community Article: [https://community.rackspace.com/feedback/f/68/t/7974](https://community.rackspace.com/feedback/f/68/t/7974)

> Some of the information at https://support.rackspace.com/how-to/glusterfs-high-availability-through-ctdb/ is out-of-date:
> 
> Point (6) in the "Install CTDB" section is out-of-date.  Setting the "private dir" option has not been required for a long time.
> In "References" the link to http://ctdb.samba.org/testing.html is stale.  We're in the process of moving documentation to the wiki, which means that out-of-date documentation like this page has gone.  Better off linking to https://wiki.samba.org/index.php/CTDB_and_Clustered_Samba

**Comment by stephamon** [comment]
@albush Thanks for letting us know! We'll get right on it!

**Comment by stephamon** [comment]
I've talked to Alan, who recommended that I reply to the feedback post to get more information on whether to delete the `private dir` option step or mark it as *(Optional)*, but I haven't got a response yet.

**Comment by stephamon** [comment]
I think I'll go ahead and remove the step entirely, and we can always add it back in later as an optional step if we need to.
