### ISSUE TITLE
Need Website Metrics

### ISSUE THREAD

**Issue by sbankey** [rackerlabs/rackspace-how-to#1623]
Hello How-To team,

I'm helping another team with metrics on a project. Can you please email me the previous month's page view numbers for the following URLs?

https://support.rackspace.com/how-to/rackspace-cloud-backup-vs-cloud-server-image-backups/
https://support.rackspace.com/how-to/cloud-backup/
https://support.rackspace.com/how-to/rackspace-cloud-backup-backing-up-databases/
https://support.rackspace.com/how-to/create-an-image-of-a-server-and-restore-a-server-from-a-saved-image/

Thanks,
Stuart Bankey

**Comment by stephamon** [comment]
@sbankey I'm on it!

**Comment by DonNateR** [comment]
@sbankey: Closing this issue, since Stephanie emailed you the metrics. Feel free to make another issue if you need anything else from the How-To team.
