### ISSUE TITLE
Update rpc-openstack/rpc-openstack-faq.md

### ISSUE THREAD

**Issue by darrenchan** [rackerlabs/rackspace-how-to#1645]
There are a number of references to v11. Update to v13.

Ccing @robb-romans @erikmwilson @asettle @cyrichardson

**Comment by catlook** [comment]
We'll look into this on the how-to, this morning!

**Comment by catlook** [comment]
Thanks Darren.  To avoid future conflicts like this, I pointed readers to the main How-to section to find the latest release notes.  That section will be maintained and current (or should be).

**Comment by catlook** [comment]
closed with
https://github.com/rackerlabs/rackspace-how-to/pull/1654
