### ISSUE TITLE
Edit to "Manage Public Folders in the Control Panel For Hosted Exchange 2013"

### ISSUE THREAD

**Issue by aldrichcory1** [rackerlabs/rackspace-how-to#1646]
https://github.com/rackerlabs/rackspace-how-to/edit/master/content/exchange/manage-public-folders-in-the-control-panel-for-hosted-exchange-2013.md

**Original Section:**

Authorization to add, delete, or modify content
Unlike Exchange 2007 and 2010, individual permissions are not managed through Outlook for Exchange 2013 or 2016.  We are working on a release that will allow you to assign different levels of permissions for each user.  For the current release, your users have the following permission levels:

- Any user on the domain can create and delete their own items only, but they cannot modify any items.
- Public folder administrators can add, delete, and modify any content by any user.

**Proposed Changes:**

Authorization to add, delete, or modify content

Unlike Exchange 2007 and 2010, individual permissions are not managed through Outlook for Exchange 2013 or 2016.  For these versions, your users have the following permission levels:

Reviewer (Read): By Default, all users on the domain are given this permission level. It allows the users to view all Public Folders. 

Publishing Author (Read, Create, Edit, Delete): This permission level is automatically given to administrators who create Public Folders in the Control Panel. Each action specified only applies to the folders this user creates.

**Comment by catlook** [comment]
Thanks, we'll look into this today!

**Comment by aldrichcory1** [comment]
Thanks guys!

**Comment by DonNateR** [comment]
Merged and completed
