### ISSUE TITLE
Edit to "Email access options during an email migration"

### ISSUE THREAD

**Issue by ruben-contreras** [rackerlabs/rackspace-how-to#1647]

**Comment by ruben-contreras** [comment]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/rackspace-email/email-access-options-during-an-email-migration.md

Current Section Without Changes: (Article Title) "Email access options during an email migration"
**Title does not make clear that it is referring to Assisted Migrations only.**

*Proposed Changes:* (New Article Title) "Email access options when migrating to Rackspace"

Current Section Without Changes: Although it is common to set up email clients such as Outlook after a migration, Rackspace mailboxes can be accessed at any time after they are created. Accessing the mailbox does not interrupt a migration in process.  
**This statement does not make clear that it is referring to Assisted Migrations only.**

*Proposed Changes:* When migrating from your current email host to Rackspace, it is common to set up email clients such as Outlook after a migration is completed. Rackspace mailboxes, however, can be accessed at any time after they are created. Accessing the mailbox does not interrupt a migration in process.

**Comment by ruben-contreras** [comment]
Proposed changes to article title and one paragraph change to help prevent confusion regarding internal and assisted migration options.

**Comment by catlook** [comment]
Ruben,
Thanks, we'll look into this today!
