### ISSUE TITLE
Full audit: RPC spheres of support

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1660]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/rpc-openstack/rackspace-private-cloud-spheres-of-support.md

- [ ] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [ ] Editor check: Incorporate edits from Kelly Holcomb
- [ ] Quality Checklist: Perform a quality audit of the article using the quality checklist
- [ ] Update audit_date: Update the audit_date metadata in the article with the date of the full audit's completion

**Comment by nimbinatus** [comment]
Email sent to Bernardo for SME reference

**Comment by asettle** [comment]
Hey @nimbinatus - this document is the equivalent of 3 years old and was initially written by @robb-romans and @RobinJoe 
As far as things go, the content is very, very out of date and this document should be retired if there is no intention to update. However, I think this would solely be up to the RPCO documentation team if we decide there is a necessity to write another updated version (to hopefully keep updated).

**Comment by asettle** [comment]
@robb-romans has stated this is on the kill list. DIE SPHERE, DIE.

**Comment by nimbinatus** [comment]
@asettle , ha, ok. So this should be retired?

**Comment by robb-romans** [comment]
Cheers.
