### ISSUE TITLE
Full audit: Security for RPC by OS

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1661]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/rpc-openstack/security-for-rackspace-private-cloud-powered-by-openstack.md
- [x] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [x] Editor check: Incorporate edits from Kelly Holcomb
- [x] Quality Checklist: Perform a quality audit of the article using the quality checklist
- [x] Update audit_date: Update the audit_date metadata in the article with the date of the full audit's completion

**Comment by nimbinatus** [comment]
Email sent to SME (Major Hayden).

**Comment by nimbinatus** [comment]
Incorporated SME feedback. @kmsholcomb , can you add this one to your editing queue? The updated doc is in PR #1680. Thanks!

**Comment by kmsholcomb** [comment]
I'll look at it today. Thanks!

**Comment by nimbinatus** [comment]
no rush; I'm offline from after work tonight until Friday afternoon
