### ISSUE TITLE
Full audit: Use annotation metrics

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1662]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/rackspace-metrics/use-annotation-metrics.md

**Comment by stephamon** [comment]
Reached out to Shane.

**Comment by stephamon** [comment]
@kmsholcomb can you add this article to your editing queue? Shane's already submitted a PR with his review.

https://support.rackspace.com/how-to/use-annotation-metrics/

**Comment by kmsholcomb** [comment]
Hi, @stephamon. My edits are attached. Please let me know if you have any questions. Thanks!

[Using annotation metrics_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/664758/Using.annotation.metrics_editsKH.pdf)
[Using annotation metrics_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/664759/Using.annotation.metrics_editsKH.docx)
