### ISSUE TITLE
Full audit: Use enum metrics

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1663]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/rackspace-metrics/use-enum-metrics.md

**Comment by stephamon** [comment]
Reached out to Shane.

**Comment by stephamon** [comment]
This feature is no longer available due to lack of usage. It's being replaced with something else, but Shane said to go ahead and remove this one now. I'll move it to the `retired-articles` folder and redirect.
