### ISSUE TITLE
Full audit: Upgrade to managed operations services level

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1664]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/managed-operations/upgrade-to-managed-operations-service-level.md
- [x] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [x] Editor check: Incorporate edits from Kelly Holcomb
- [x] Quality Checklist: Perform a quality audit of the article using the quality checklist
- [x] Update audit_date: Update the audit_date metadata in the article with the date of the full audit's completion

**Comment by nimbinatus** [comment]
Picking this one up to get edits done and prep it for emailing out. Not going to send it until after the holidays when people are back in the office so it doesn't get lost in inbox swamping.

**Comment by nimbinatus** [comment]
Sent an email to Dusty to find a SME.

**Comment by nimbinatus** [comment]
Got an email from Sameer. Here's his feedback:
99% accurate. Some very minor feedback here - I saw slightly different screen/options. Let me clarify those in screenshots/comments below
·         https://support.rackspace.com/how-to/upgrade-to-managed-operations-service-level/
 
Step 5: To upgrade your service level to Managed Ops: SysOps or Managed Ops: DevOps, click Select at the bottom of the appropriate column. Instead I had to click “Learn More” which then opens a popup window to click “Request Upgrade”
 
Step 7: Read the Managed Operations Terms of Service, select the I agree to the Cloud Terms of Service. I didn’t see a “I agree to Cloud Terms of Service” check box. Here’s what I saw. [image that shows "Request Upgrade" button instead.

**Comment by nimbinatus** [comment]
Sending to editing.

**Comment by nimbinatus** [comment]
Adding in second SME (Christine) feedback: "Where it says: '5. To upgrade your service level to Managed Ops: SysOps or Managed Ops: DevOps, click Select at the bottom of the appropriate column.' It should be: '5. To upgrade your service level to Managed Ops: SysOps click Learn More under Managed Operations.' I do not believe there is a devops service level anymore as it moved to Professional Services."
