### ISSUE TITLE
Full audit: managed cloud service levels FAQ

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1665]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/managed-operations/managed-cloud-service-levels-faq.md
- [x] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [x] Editor check: Incorporate edits from Kelly Holcomb
- [x] Quality Checklist: Perform a quality audit of the article using the quality checklist
- [x] Update audit_date: Update the audit_date metadata in the article with the date of the full audit's completion

**Comment by nimbinatus** [comment]
Picking this one up to get edits done and prep it for emailing out. Not going to send it until after the holidays when people are back in the office so it doesn't get lost in inbox swamping.

**Comment by nimbinatus** [comment]
Sent an email to Dusty to find a SME.

**Comment by nimbinatus** [comment]
Email out to Keith (identified SME)

**Comment by nimbinatus** [comment]
Email out to Keith, part 2

**Comment by nimbinatus** [comment]
Two SMEs reviewing; not sure who will get back to me first :)

**Comment by nimbinatus** [comment]
rec'd +1 from Steve and Ryan. Moving forward!

**Comment by nimbinatus** [comment]
Stopping here; need to review some things higher up

**Comment by nimbinatus** [comment]
Waiting for word about legal references from Trent per Renee and Laura

**Comment by nimbinatus** [comment]
Email sent to Trent

**Comment by nimbinatus** [comment]
Legal request sent.

**Comment by nimbinatus** [comment]
rec'd response from legal

**Comment by nimbinatus** [comment]
sent to editing
