### ISSUE TITLE
Full audit: linux patching for cloud servers managed operations service level

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1666]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/managed-operations/linux-patching-for-cloud-servers-managed-operations-service-level.md

- [x] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [x] Editor check: Incorporate edits from Kelly Holcomb
- [x] Quality Checklist: Perform a quality audit of the article using the quality checklist
- [x] Update audit_date: Update the audit_date metadata in the article with the date of the full audit's completion

**Comment by nimbinatus** [comment]
Email sent to Dusty for review; he's OOO for the rest of the year. Searching for another SME.

**Comment by nimbinatus** [comment]
Email sent to Ryan for review per Stephanie's suggestion

**Comment by nimbinatus** [comment]
Sent an email to Dusty to find a SME.

**Comment by nimbinatus** [comment]
Ryan Stark gave this a +1. Moving to editorial.

**Comment by nimbinatus** [comment]
Quality checklist complete. Posting for merge.
