### ISSUE TITLE
Convert Server-side monitoring configuration to how-to article

### ISSUE THREAD

**Issue by wolfdancer** [rackerlabs/rackspace-how-to#1689]
## What do you want us to know about?  
*(Check all that apply.)*

**Report a documentation issue**
- [x] Missing information

**Product**
- [ ] Product bug 
- [ ] Product feedback

**Tell us more about your issue**
I thought we converted the blog post to documentation but I cannot find it anywhere.  We should have a how-to article on the Server-side Monitoring Configuration feature so that we can keep it up-to-date.

http://blog.rackspace.com/monitor-like-a-pro-with-server-side-configuration

**Comment by DonNateR** [comment]
Article published.
