### ISSUE TITLE
 Full audit: Permissions matrix for Cloud Big Data v2

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1706]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-big-data/detailed-permissions-matrix-for-cloud-big-data-v2.md

- [x] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [x] Editor check: Incorporate edits from Kelly Holcomb
- [x] Quality Checklist: Perform a quality audit of the article using the quality checklist
- [x] Update audit_date: Update the audit_date metadata in the article with the date of the full audit's completion

**Comment by nimbinatus** [comment]
sent email to SME

**Comment by nimbinatus** [comment]
SME gave it a +1; sending to editing

**Comment by nimbinatus** [comment]
Editing feedback incorporated and QC checklist finished
