### ISSUE TITLE
Update How-to article with new information about Debian/Ubuntu agent installation

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/rackspace-how-to#1710]
From backup slack channel:

Catherine Richardson
2:16 PM
@temporalbeing Do you think an update to an article in the How-To center, or API docs, will be needed?
Ben Meyer
2:16 PM
@catherine probably just the How-To center docs; wherever we have the Debian/Ubuntu agent installation documented
Catherine Richardson
2:28 PM
@temporalbeing  Do you think this is the article to update? https://support.rackspace.com/how-to/rackspace-cloud-backup-install-the-agent-on-linux/
2:29
Or this one: https://support.rackspace.com/how-to/update-the-rackspace-cloud-backup-agent/
Ben Meyer
2:29 PM
@catherine yes that's the article...just add my new steps per the new package to it
Catherine Richardson
2:29 PM
Or both?
Ben Meyer
2:30 PM
both need the information
Catherine Richardson
2:31 PM
kk - I'll add both links to the issue.
Ben Meyer
2:31 PM
@catherine thanks for tracking those down; hopefully they're the only ones we have for installation stuff any more outside of the one-line updater stuff we do in the RCBU CP

Ben's 1st email:

Date: Wednesday, December 14, 2016 at 2:10 PM

Subject: Cloud Backup Debian Repository Update

All,
The Cloud Backup Team discovered a couple weeks ago that the Debian Repository supporting the Cloud Backup Agent for installation on customer systems has a GPG Key that expires on 2016-12-26 - the day *after* Christmas. If the GPG Key is not updated by that date then the system will not be able to get updates to the Cloud Backup Agent until a new active GPG key is installed.
On Tuesday, December 13th, 2016 we released a new set of packages to production - a new version of Cloud Backup Updater for Debian Linux and a new Debian Package - cloudbackup-keyring.deb - to our Debian APT repository supporting Debian and derivative Linux distributions (f.e Ubuntu). Any system that has the Cloud Backup Updater installed *and* enabled should then get the new packages in the next few days at latest.
The change to the Cloud Backup Updater for Debian was simply updating the package to be dependent on the new Cloud Backup Keyring package. The new package dynamically downloads the new GPG key and installs it on the system. This change *only* affected Debian systems.
If a system does not have the Cloud Backup Updater installed *or* running, or for some other reason fails to perform the update, then the following steps can be used to re-enable updates for the Cloud Backup Agent on Debian-based systems:
1.	Download the new Cloud Backup Keyring package - http://agentrepo.drivesrvr.com/debian/pool/main/c/cloudbackup-keyring/cloudbackup-keyring_2016.12.02-1_all.deb - onto the target system
2.	Install the package manually using `dpkg`: dpkg -i cloudbackup-keyring_2016.12.02-1_all.deb 
3.	Update the APT repositories: apt-get update 
4.	Either start the Cloud Backup Updater or do an upgrade via APT directly: apt-get upgrade 
It would be best for customers to do this upgrade before 2016-12-26 since just the last two steps above (#3 and #4) will cause the upgrade to happen; however, the above steps should be simple enough for anyone to run should updates fail.
Also, please be aware that the procedures for installing the Cloud Backup Agent on Debian and derived systems (f.e Ubuntu) need to be updated for this process as well.
Ben Meyer
Software Dev III
Rackspace Cloud Backup

**Comment by BenjamenMeyer** [comment]
Previous directions would have had instructions around to download the file http://agentrepo.drivesrvr.com/debian/agentrepo.key and add it, probably something like:

> \# wget http://agentrepo.drivesrvr.com/debian/agentrepo.key | apt-key add -

This should get updated to be:
> \# wget http://agentrepo.drivesrvr.com/debian/pool/main/c/cloudbackup-keyring/cloudbackup-keyring_2016.12.02-1_all.deb
> \# dpkg -i cloudbackup-keyring_2016.12.02-1_all.deb

This only affects the directions for Linux systems using Debian APT - namely Debian and Ubuntu.

**Comment by Catherine** [comment]
I think you might have meant to tag @cyrichardson instead of @catherine (me) in the PR description.

**Comment by cyrichardson** [comment]
Thank you! Got it. And adding to the How-To issue.

**Comment by catlook** [comment]
https://github.com/rackerlabs/rackspace-how-to/pull/1718

**Comment by catlook** [comment]
Steph helped to fix spacing numbering issues
