### ISSUE TITLE
Remove unnecessary RPC articles and update the remaining few

### ISSUE THREAD

**Issue by asettle** [rackerlabs/rackspace-how-to#1713]
I have reviewed all the articles on the RPC-O How-To website and this is a list of each article that should be remove or kept.

All articles that have ‘remove' are out-of-date for either hardware and software requirements and should not be kept (that, and some of the original authors are no longer at Rackspace).

I recommend removing the titles from the Index files as well as they are misleading in what we support and do not support. It is important that we do not have incorrect public facing content.

The articles I have suggested to keep have a recommended SME contact who will be able to point you in the right direction, at the very least. One of two of these articles will point directly to the RPC-O docs team. This is simply because we wish to orchestrate the updating of content with the IA team and ensure that this fits in with our content model.

1. _Using Apache Hadoop on Rackspace Private Cloud_, 2012: Keep and update - How-To team to edit. Product team SMEs (for this document): Bryan Thompson (current manager), Philip Williams (Principal Architect)
2. _Deploy Rackspace Private Cloud to bare metal using Razor and Chef_, 2012: Remove, Chef is no longer a part of RPC.
3. _Building a Rackspace Private Cloud with Linux iSCSI Volumes_, 2013: Remove, outdated hardware and Chef content.
4. _Compute Cloud (Nova) using SeaMicro SM15000_, 2016 (last update): Remove, very out of date hardware and software.
5. _Install and test Cinder in your Rackspace Private Cloud lab environment_, 2106 (last update): Remove, Chef is no longer a part of RPC. 
6. _Object Storage (Swift) in a Rack with AMD's SeaMicro SM15000_, 2013: Remove, very out of date hardware and software.
7. _OpenStack Glossary of Terms_, 2015: Keep, but update considerably. Most terms can be duplicated from here: https://github.com/openstack/openstack-manuals/blob/master/doc/common/glossary.rst
8. _Private Cloud Certified Devices - Compute_, 2014: Remove, super updated. However, this type of content has potential to be written in an updated context.
9. SECTION: _Private Cloud Tech Resources_, 2016 (last update): Remove. Although this type of context SHOULD be rewritten with updated content.
10. _Rackspace Private Cloud Documentation_, 2016 (last update): I think we should update this with more contextual information about what is RPCO.
11. _Rackspace Private Cloud - Partner Devices_, 2016 (last update): Remove. This should however be considered to be updated. Speak to Bryan Thompson (product manager). 
12. _Rackspace Private Cloud Software and sosreport_, 2016 (last update): Ubuntu-specific tool for gathering info. Support may or may not still use it. SMEs: Bjoern Teipel, 
13. Update the index at https://support.rackspace.com/how-to/rpc-openstack-all-articles/ to remove link to _Rackspace Private Cloud Software Package Update - 20 March 2013_
14. _Rackspace Private Cloud Software - VM Block Migration_, 2016 (last update): Remove, this is a v2.0 document from Folsom. This is so old it's a dino.
15. Update the index at https://support.rackspace.com/how-to/rpc-openstack-all-articles/ to remove link to _Rackspace Private Cloud Spheres of Support_
16. _Rackspace Private Cloud FAQ_: Keep! Yay! RPC-O team to work with Support team to update this document. SMEs: Robb Romans, Erik Wilson, Alexandra Settle, Margaret Eker, Catherine Richardson, Bjoern Teipel, Ethan Cohen, Steve Ribble
17. _Security for Rackspace Private Cloud Powered By OpenStack_, 2016: Keep. SME: Major Hayden (but this has already been dealt with)
18. _Using CommVault to Backup Data in Rackspace Private Cloud_, 2013: FLAMES. THROW IT IN THE FIREEEE.

**Comment by robb-romans** [comment]
@asettle awesome. thank you!

Notes:
- Brian Thompson is now RPC General Manager. Recommend you start instead with technical marketing (Ken Hui; Tony Campbell), sales engineering (Vinson Rogers) or RPC architects (Phil Williams, Hugh Blemings). For general RPC product management questions or to help you find appropriate SMEs, contact Jorge Miramontes.
- RPC FAQ source is here: https://github.com/rackerlabs/docs-rpc/tree/master/doc/rpc-faq-external
- For the glossary, would we be better off just pointing to the upstream version, rather than duplicating it?

**Comment by asettle** [comment]
@robb-romans my only concern with pointing upstream is that we do not share all the same terms. There are a lot of stuff we can use from upstream, but there are definitely some Rackspace specific terms that would be good to include. I appreciate we are trying to minimise upstream duplication though.

**Comment by darrenchan** [comment]
Partially addresses https://github.com/rackerlabs/docs-workstream/issues/163

**Comment by DonNateR** [comment]
Added requested full audits as different issues.

**Comment by asettle** [comment]
Reopening for number 10 in the above list. The following updates should occur:

- Rackspace Private Cloud Powered by OpenStack - The "By" is with a capital B.
- OpenStack-Ansible - should be capitalised as such.
- Instead of "Documentation for Rackspace Private Cloud is available here and here." Instead of the "here and here", I would recommend saying that "we have these docs available... " and list "operations guide, swift  guide" - all the external stuff. Note that the link for the second "here" in that sentence goes to a 404. 
- And for the OpenStack-Ansible stuff you've linked to the launchpad page (?!). This should be linked to https://github.com/openstack/openstack-ansible for the first link
- I would recommend linking specifically to the Deployment Guide here: http://docs.openstack.org/project-deploy-guide/draft/

**Comment by DonNateR** [comment]
Made issue #1749  to address #10 and added the issue to the RPC full audit project (issue will be reopened when in progress).
