### ISSUE TITLE
Republish Old KC article

### ISSUE THREAD

**Issue by sbankey** [rackerlabs/rackspace-how-to#1724]
Hello How-To Team,

One of the community threads (https://community.rackspace.com/products/f/25/t/197) references a few articles from the KC. I was contacted by a technician that needs one of them republished into the How-To so he can help a customer this morning.

http://www.rackspace.com/knowledge_center/article/adding-disk-space-after-resizing-a-windows-2008-cloud-server

Please let me know once that has been completed. Thanks!

**Comment by stephamon** [comment]
Hi @sbankey we didn't migrate that article into the How-To site because it isn't specific to Rackspace Cloud Servers.

For this kind of content (useful to customers, but not specific to us), we recommend that it go into Community instead of the How-To site.

**Comment by sbankey** [comment]
Hi Stephanie,

Does the article exist somewhere that I can pull it? Also, a little confused by what you said since the same article exists in the How-To for windows server 2012. Do I need to migrate that one into our platform too?

Sent from my iPhone

On Dec 20, 2016, at 9:42 AM, Stephanie Fillmon <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @sbankey<https://github.com/sbankey> we didn't migrate that article into the How-To site because it isn't specific to Rackspace Cloud Servers.

For this kind of content (useful to customers, but not specific to us), we recommend that it go into Community instead of the How-To site.

-

**Comment by stephamon** [comment]
Hm. Probably we kept the Windows Server 2012 article because it was highly viewed on the old platform. We kept all of the top 100 viewed articles, regardless of whether they were Rackspace-specific. 

I'll email you the 2008 article. Can we put it in Community for now, and then when @ReneeRendon is back, we can revisit whether we pull it back into How-To?

**Comment by stephamon** [comment]
All good here.
