### ISSUE TITLE
article filenames ending in dash-0

### ISSUE THREAD

**Issue by steveortiz** [rackerlabs/rackspace-how-to#173]
I noticed there are 18 files with filenames ending in "-0.md"

- cloud-backup/rackspace-cloud-backup-backup-actions-0.md
- cloud-backup/rackspace-cloud-backup-create-a-backup-0.md
- cloud-backup/rackspace-cloud-backup-preferences-0.md
- cloud-dns/create-a-reverse-dns-record-0.md
- cloud-files/getting-started-with-cloud-files-and-cdn-0.md
- cloud-files/protect-your-cloud-files-cdn-bill-from-unexpected-usage-0.md
- cloud-images/creating-an-ubuntu-1310-image-for-the-rackspace-open-cloud-0.md
- cloud-monitoring/alarm-language-generic-thresholds-made-easy-0.md
- cloud-servers/configuring-basic-security-0.md
- cloud-servers/getting-started-with-role-based-access-control-rbac-0.md
- cloud-servers/removing-networks-from-a-cloud-server-0.md
- cloud-sites/information-for-mysql-users-mariadb-100-0.md
- cloud-sites/information-for-new-php-56-apache-version-0.md
- exchange/adding-microsoft-exchange-mailboxes-0.md
- rackconnect/rackconnect-release-notes-0.md
- rackspace-email/cloud-office-control-panel-0.md
- rackspace-email/spam-preferences-safe-lists-and-black-list-in-rackspace-email-0.md
- rackspace-email-archiving/set-access-rules-for-archive-end-users-0.md

And a couple others ending in -1 or -2:
- cloud-servers/migrating-a-linux-server-from-the-command-line-1.md
- cloud-servers/migrating-a-linux-server-from-the-command-line-2.md

Should these filenames be changed?  Should `rackspace-cloud-backup-backup-actions-0.md` become `rackspace-cloud-backup-backup-actions.md`?

**Comment by steveortiz** [comment]
@robin-norwood: Your input on the above would be helpful too... I don't want to break all the links and redirects work you've been doing.  We could try to handle this post-launch if you want to keep URLs from changing.

**Comment by stephamon** [comment]
We would need to double check that there isn't a file with the same name minus the 0. Drupal did that automatically when new articles had titles that would generate the same URL as existing articles (even if those existing articles now had different titles).

**Comment by steveortiz** [comment]
Good idea.  Let's do this after things have settled down a bit.

**Comment by robin-norwood** [comment]
There are two:

'''
[robin.norwood@localhost rackspace-how-to]$ find -iname "*-0.md" | sed "s/\(.*\)-0.md/\1-0.md \1.md/g" | xargs -L 1 git mv
fatal: destination exists, source=content/rackspace-email/cloud-office-control-panel-0.md, destination=content/rackspace-email/cloud-office-control-panel.md
fatal: destination exists, source=content/cloud-servers/removing-networks-from-a-cloud-server-0.md, destination=content/cloud-servers/removing-networks-from-a-cloud-server.md
[robin.norwood@localhost rackspace-how-to]$ find -iname "*.md" | xargs sed -i "s/\(\/how-to\/.*\)-0/\1/g"
'''

**Comment by robin-norwood** [comment]
And yes, let's wait to do this. :)

**Comment by DonNateR** [comment]
I believe that @ktbartholomew fixed this already. Closing issue.
