### ISSUE TITLE
Edit to "Cloud Office Control Panel"

### ISSUE THREAD

**Issue by misskristenbrown** [rackerlabs/rackspace-how-to#1731]
Current Section without Changes: 
"Cloud Office management - Manage Rackspace Email and Microsoft Exchange settings:
    Rackspace Email overview
    Microsoft Exchange overview"
- Clicking on "Rackspace Email overview" links to article, "Cloud Office Control Panel overview," which includes directions for both Rackspace Email and Microsoft Exchange. 
- Clicking on "Microsoft Exchange overview" is a broken link. 

*Proposed Changes:* Either consolidate the two "overview" links into one "Cloud Office Control Panel overview" OR link "Microsoft Exchange overview" to open at the Microsoft Exchange section of the article "Cloud Office Control Panel overview"
https://support.rackspace.com/how-to/cloud-office-control-panel-overview/

**Comment by nimbinatus** [comment]
Thanks, @misskristenbrown! We will pull this update into our next sprint.

**Comment by stephamon** [comment]
https://support.rackspace.com/how-to/cloud-office-control-panel/

**Comment by misskristenbrown** [comment]
Let me review this again and I will follow up with you today or tomorrow

**Comment by misskristenbrown** [comment]
Not sure how this email popped up again today, but I do see that the broken link for the Microsoft Exchange Control Panel overview was removed. Looks good now.
