### ISSUE TITLE
Update OpenStack glossary of terms

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1739]
Update OpenStack glossary of terms article (https://support.rackspace.com/how-to/openstack-glossary-of-terms/)  with the latest definitions from this page: https://github.com/openstack/openstack-manuals/blob/master/doc/common/glossary.rst .

**Comment by nimbinatus** [comment]
reopening after pulling in from the RPC audit project

**Comment by nimbinatus** [comment]
ref: number 7 in #1713 
"OpenStack Glossary of Terms, 2015: Keep, but update considerably. Most terms can be duplicated from here: https://github.com/openstack/openstack-manuals/blob/master/doc/common/glossary.rst"

**Comment by nimbinatus** [comment]
@asettle, @robb-romans, @ReneeRendon, should we pull in any other terms from the glossary for the how-to's glossary? I was thinking about adding the few core services that aren't there, at the very least (cinder, neuron, and swift). Also, I'm going to split it out with OpenStack specific terms at the top and basic terms at the bottom, with headings and alphanumeric order. Any objections?

**Comment by ReneeRendon** [comment]
That sounds good to me. However, @robb-romans and @asettle are the experts with RPC and OS.

**Comment by robb-romans** [comment]
Hmm. I'm not aware of many things that are only in RPC (that are not in upstream OpenStack). The only one that comes to mind is MaaS (Monitoring as a Service).

Looking over the existing glossary, those are all common industry definitions that someone could find with a quick Google and are not at all unique to Rackspace. What's the need/reason/use case for us spending time to maintain our own glossary of common terms?

**Comment by nimbinatus** [comment]
@ReneeRendon or @asettle, do either of you have thoughts on @robb-romans question? I honestly don't have enough information to answer that.

**Comment by nimbinatus** [comment]
Per @ReneeRendon, this article is no longer needed
