### ISSUE TITLE
Edit/Correction Request for CBS article

### ISSUE THREAD

**Issue by sbankey** [rackerlabs/rackspace-how-to#1746]
Hello How-To Team,

A user came into the Community and posted this thread regarding one of the articles published in the How-To:

Community Thread: https://community.rackspace.com/feedback/f/68/t/8037
Article: https://support.rackspace.com/how-to/detach-and-delete-cloud-block-storage-volumes/

Can you please have the article changed to correct the steps?

Thanks,
Stu

**Comment by nimbinatus** [comment]
Thanks, @sbankey! We'll pull this issue into our next sprint.

**Comment by nimbinatus** [comment]
email sent out to find an SME for assistance

**Comment by nimbinatus** [comment]
Working with Jake C. on this one

**Comment by nimbinatus** [comment]
Adding @catlook for more details

**Comment by nimbinatus** [comment]
Sent adjustments to Jake C. to confirm accuracy one more time.

**Comment by ReneeRendon** [comment]
@nimbinatus sent email today asking for Larry H. to check the accuracy since Jake has not responded.

**Comment by nimbinatus** [comment]
rec'd +1 from Jake. Moving forward
