### ISSUE TITLE
Add info to Cloud Office migration article

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-how-to#1747]
In addition to the picture (*Deanna says the image is not clear in both IE and Firefox*), we were hoping to add one more line in the bullet list under “Items that are not migrated”:
 
Color categories for calendars. The default colors will be maintained during migration. However, if additional color categories have been defined at the Source, other than those supported at the Destination, then these will not be migrated. Instead, they will be converted to the default calendar color at the Destination.

**Comment by DonNateR** [comment]
@stephamon: Have a link to the article handy?

**Comment by stephamon** [comment]
https://support.rackspace.com/how-to/items-migrated-during-an-cloud-office-migration/
