### ISSUE TITLE
Research and document Microsoft SQL Server 2014 and 2016

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-how-to#1760]
The product bulletin announcing the EOL of Microsoft SQL 2008 (end of support: 7/9/2019, end of life: 7/11/2021) mentioned that customers will have the option to use MS SQL Server 2012, 2014, and 2016. 

As far as I am aware, we do not have any documentation for MS SQL Server 2014 and 2016.

We should investigate the differences and update existing MS SQL Server articles, and create any new articles for the newer server versions.

**Comment by stephamon** [comment]
Does not go beyond MS SQL Server 2012: https://support.rackspace.com/how-to/troubleshoot-remote-access-to-sql-server/

Does not specify version: https://support.rackspace.com/how-to/creating-and-configuring-a-user-in-mssql/

The rest of the MS SQL articles have to do with Cloud Sites. @ReneeRendon should we bother with those?

**Comment by stephamon** [comment]
I've sent out an email to Thomas D. and JP to start getting info about this issue.

**Comment by ReneeRendon** [comment]
I apologize @stephamon . I just saw your question above. We do not need to update the Sites articles.

**Comment by stephamon** [comment]
Confirmed that I can just add the 2014 and 2016 versions to the section for 2012. There haven't been any changes that would affect the process.
