### ISSUE TITLE
Dead URLs in Rackspace Monitoring How-To's

### ISSUE THREAD

**Issue by lukedammers** [rackerlabs/rackspace-how-to#1764]
Hi there,

I found that there are several dead links to Rackspace Monitoring "Getting Started" how to's and others as below - I hope that this is the correct place to report this however please let me know if not.

Page:
https://support.rackspace.com/how-to/rackspace-monitoring-faq/

Dead links:
Getting Started > What are the various terms I need to know when using Rackspace Monitoring? > Concepts: https://developer.rackspace.com/docs/cloud-monitoring/v1/developer-guide/?&_ga=1.187986344.1636762704.1464772734#document-concepts

General > Is there a good tutorial for customers unfamiliar with monitoring in general? >  Rackspace Monitoring Getting Started Guide: https://developer.rackspace.com/docs/cloud-monitoring/v1/developer-guide/?&_ga=1.191134122.1636762704.1464772734#document-getting-started
(This URL is referenced in many different locations and so is showing a "page not found" when clicked through to from various other articles.

**Comment by ReneeRendon** [comment]
Hi @lukedammers .

Yes, this is the place to report it! Thank you for pointing this out. We will get these corrected.

**Comment by DonNateR** [comment]
@lukedammers: Getting those links updated on the page for you right now. I'm providing the correct links here so you can reference them later:

Concepts: https://developer.rackspace.com/docs/rackspace-monitoring/quickstart/#concepts 

Getting Started: https://developer.rackspace.com/docs/rackspace-monitoring/v1/getting-started/ 

Let me know if you run into anymore of these links.
