### ISSUE TITLE
Full Audit: Permissions Matrix for Cloud Load Balancers

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1783]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-load-balancers/permissions-matrix-for-cloud-load-balancers.md
- [x] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [x] Editor check: Incorporate edits from Kelly Holcomb
- [ ] Quality Checklist: Perform a quality audit of the article using the quality checklist
- [ ] Update audit_date: Update the audit_date metadata in the article with the date of the full audit's completion

**Comment by nimbinatus** [comment]
email sent to potential SME (Jorge)

**Comment by nimbinatus** [comment]
Email sent to Trent, who was recommended by Jorge

**Comment by nimbinatus** [comment]
Trent said he'd get back to me with someone.

**Comment by nimbinatus** [comment]
SME review received and done! @kmsholcomb, can you add this one to your editing queue? Thanks!
