### ISSUE TITLE
Outdated release notes for RackConnect?

### ISSUE THREAD

**Issue by nimbinatus** [rackerlabs/rackspace-how-to#1789]
These release notes last date from 2014. Has the project been updated since then?

https://github.com/rackerlabs/rackspace-how-to/blob/master/content/rackconnect/rackconnect-release-notes.md

**Comment by nimbinatus** [comment]
Email out to Russell for SME

**Comment by nimbinatus** [comment]
Reached out to Cody and Eric for a SME via email

**Comment by stephamon** [comment]
Retiring due to lack of views and response from team
