### ISSUE TITLE
Full Audit: Migrating your drupal database to cloud servers

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1807]
This article describes the process for migrating your Drupal database from **Cloud Sites** to Cloud Servers. Should this article be retired?

https://support.rackspace.com/how-to/migrating-your-drupal-database-to-cloud-servers/

**Comment by stephamon** [comment]
176 views since July, 2016

**Comment by stephamon** [comment]
Emailed Thomas H.

**Comment by stephamon** [comment]
Thomas says that this can be retired. It was kind of an edge case from a few years ago that was kept during our platform migration.
