### ISSUE TITLE
Full Audit:  Importing data into cloud databases

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1808]
Checking this content for accuracy due to an internal bulletin. I have emailed Steve and Matt and will update this issue with their reply.

https://support.rackspace.com/how-to/importing-data-into-cloud-databases/

- [x] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [x]  Editor check: Incorporate edits from Kelly Holcomb
- [ ]  Quality Checklist: Perform a quality audit of the article using the quality checklist
- [ ]  Update audit_date: Update the audit_date metadata in the article with the date of the full audit's completion

**Comment by stephamon** [comment]
@ReneeRendon It's only been viewed 13 times since July, so it should be safe to retire it if we need to.

**Comment by ReneeRendon** [comment]
Thanks for the info @stephamon!
I just heard back from Steve. The content in the article still holds true and is accurate.  We can continue with a full audit and check off the SME box. We will add it to our next sprint and discuss the page views at that time.

**Comment by nimbinatus** [comment]
sent to editing
