### ISSUE TITLE
[MVP] Rackspace Migration Manager: Add a new section under Cloud Hosting for Rackspace Migration Manager

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/rackspace-how-to#1832]
Release coming up March 7, 2017. Will have 3-6 How-To articles, yet to be developed. Working with Trent Gillaspie, the PM. He notes that the tab should be Fanatical Support for AWS and not FAWS.

**Comment by stephamon** [comment]
Launch in May

**Comment by stephamon** [comment]
When the tab is live, move https://github.com/rackerlabs/rackspace-how-to/pull/1861 to it

**Comment by stephamon** [comment]
Release now mid-to-late June

**Comment by cyrichardson** [comment]
Release now mid to late July. Official name is Rackspace Migration Manager

**Comment by cyrichardson** [comment]
Closing in favor of https://jira.rax.io/browse/INFODEV-424
