### ISSUE TITLE
[MVP] Rackspace Migration Manager: Create index.md for landing page

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/rackspace-how-to#1834]
Something similar to https://support.rackspace.com/how-to/dedicated-hosting/

**Comment by stephamon** [comment]
Launch in May

**Comment by stephamon** [comment]
Release now mid-to-late June

**Comment by cyrichardson** [comment]
Release now mid to late July

Official name is now Rackspace Migration Manager

**Comment by cyrichardson** [comment]
Ready for MVP launch

**Comment by cyrichardson** [comment]
Closing in favor of https://jira.rax.io/browse/INFODEV-424
