### ISSUE TITLE
[MVP] Rackspace Migration Manager: Create FAQ article

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/rackspace-how-to#1839]
Use information from doc audit to create FAQ article - Internally Documented

Provide link to the PR for this issue to the PM, Trent Gillaspie, for review/additions.

**Comment by stephamon** [comment]
Launch in May

**Comment by stephamon** [comment]
Release now mid-to-late June

**Comment by cyrichardson** [comment]
Closing in favor of https://jira.rax.io/browse/INFODEV-424
