### ISSUE TITLE
Dedicated: New SOS article

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-how-to#1841]
I'd like to start the process to get this article published in the dedicated how-to section:

https://github.com/mralexjuarez/rackspace-how-to/blob/master/content/dedicated-hosting/linux-spheres-of-support.md

As part of the publishing process, I'd also like to remove the article linked below and instead redirect visitors to the new article above which it is designed to supersede:

https://github.com/rackerlabs/rackspace-how-to/blob/master/content/managed-operations/cloud-servers-with-managed-operations-support-for-linux.md

The end goal of this operation is to have one single 'spheres of support' document on the how-to site that applies to both Dedicated & Managed Operations cloud customers.

In addition to the content changes above, I was advised by legal to include a disclaimer, like to what is found at the end of this document (page 5):

http://www.associatedsalesgroup.com/pdf/RS-Fanatical-Support-for-365-Spheres-of-Support.pdf

Is it possible to have a disclaimer page that the article links out to like the current usage/license terms, or is something that would need to be inline? I'd prefer a link if possible, as that would make it easy for Windows or other groups publishing SOS type content can all link to the same, consistent disclaimer verbiage.

**Comment by stephamon** [comment]
Investigate how many articles may link to the disclaimer and if other input about the existing Managed Ops SOS article is necessary.

**Comment by rax-rstark** [comment]
I just wanted to check in on this request. Are there any updates you can provide on when to expect this article to be published? I did not think it would take this long.
