### ISSUE TITLE
New article needed for migration from CentOS5/RHEL5?

### ISSUE THREAD

**Issue by nimbinatus** [rackerlabs/rackspace-how-to#1850]
Due to the Product bulletin from Feb 15, these articles may need a full audit. The bulletin offers a few POCs.

- [x] https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-servers/configuring-a-software-raid-on-a-linux-general-purpose-cloud-server.md (seems like a very basic mention; it _is_ an older article, though)
- [x] https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-servers/hidden-base-images.md
- [x] https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-servers/linux-server-security-best-practices.md
- [x] https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-servers/provisioning-cloud-resources-when-migrating-from-amazon-web-services.md
- [x] https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-servers/rackspace-cloud-essentials-centos-installing-vsftpd.md
- [x] https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-servers/updating-servicenet-routes-on-cloud-servers-created-before-june-3-2013.md
- [x] https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-servers/use-a-custom-kernel-with-pv-grub.md
- [x] https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-servers/vnc-install.md

Update only:

- [x] https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-servers/install-epel-and-additional-repositories-on-centos-and-red-hat.md

New:
- [ ] Maybe create migration how-to?

**Comment by nimbinatus** [comment]
Need to send an email to a SME regarding the possible need for a migration article

**Comment by nimbinatus** [comment]
Email needed to be sent to a SME from the bulletin to ask if we need a migration article around the CentOS/RHEL 5 change

**Comment by ReneeRendon** [comment]
I sent an email to the RHELCent5EOL team. 3/14/17

**Comment by ReneeRendon** [comment]
Our customers who are affected by this have been contacted and given instruction, so I'm closing this issue.
