### ISSUE TITLE
Full Audit: Linux server security best practices

### ISSUE THREAD

**Issue by nimbinatus** [rackerlabs/rackspace-how-to#1855]
Due to the Product bulletin from 15 February 2017, this article may need a full audit. The bulletin offers a few POCs.

https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-servers/linux-server-security-best-practices.md

- [x] SME review
- [ ] Editing review
- [ ] Quality Checklist
- [ ] Audit date update

Ref issue #1850

**Comment by DonNateR** [comment]
Emailed original author of the article
