### ISSUE TITLE
[MVP] Rackspace Migration Manager: Add all.md file

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/rackspace-how-to#1868]
FAWS tab on How-To landing page will not to live until release currently scheduled on 3/7

**Comment by stephamon** [comment]
Launch in May

**Comment by stephamon** [comment]
Release now mid-to-late June

**Comment by cyrichardson** [comment]
Closing in favor of https://jira.rax.io/browse/INFODEV-424
