### ISSUE TITLE
[MVP] Rackspace Migration Manager: Create draft overview article for migration from Rackspace to AWS

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/rackspace-how-to#1870]
FAWS articles will not go live on the How-To landing page until the release currently scheduled for 3/7.

Something for Trent to then edit and add to.

**Comment by stephamon** [comment]
Release now mid-to-late June

**Comment by cyrichardson** [comment]
Closing in favor of https://jira.rax.io/browse/INFODEV-424
