### ISSUE TITLE
FAWS: New article: Connect to an RDS instance using Putty (ExCon)

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1880]
External contribution: new article by gfa.

Article needs to be triaged and placed into the review process.

**Comment by DonNateR** [comment]
Will move this to Milestone 27 after sprint.

**Comment by DonNateR** [comment]
Met with Gustavo. Found details needed to update article.

**Comment by stephamon** [comment]
FAWS release now mid-to-late June
