### ISSUE TITLE
FAWS: Backend set up for new FAWS articles

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1881]
- [ ] Lowercase FAWS directory and metadata
- [ ] Add FAWS product info to products.csv and the other needed backend files.

**Comment by stephamon** [comment]
Launch in May

**Comment by stephamon** [comment]
Release now mid-to-late June

**Comment by cyrichardson** [comment]
This issue is now truly for FAWS articles and not for Rackspace Migration Manager articles. A new content folder, rackspace-migration-manager, is available for the latter.

Rackspace Migration Manager is now scheduled for mid to late July release.
