### ISSUE TITLE
add-rackspace-email-mailboxes.md

### ISSUE THREAD

**Issue by misskristenbrown** [rackerlabs/rackspace-how-to#1920]
1. Add Licenses 
Current Section without Changes: Includes instructions for how to add licenses at the bottom of the list of instructions to add mailboxes. 
Proposed Changes: 
Please see the attached Word document for the revision suggestion.
Reason: If a customer has exhausted their licenses, the Add Mailbox button is greyed out; therefore, in many cases, adding licenses is step one.

[Add Rackspace Email mailboxes.docx](https://github.com/rackerlabs/rackspace-how-to/files/851244/Add.Rackspace.Email.mailboxes.docx)
![addmailbox](https://cloud.githubusercontent.com/assets/24738359/24053837/45cdc3be-0b08-11e7-94d8-dc3465051924.png)
![addmailbox_greyedout](https://cloud.githubusercontent.com/assets/24738359/24053840/471be7c8-0b08-11e7-8aac-f1912f6bda4c.png)
![addmailboxes](https://cloud.githubusercontent.com/assets/24738359/24053841/48728f6e-0b08-11e7-8a1d-adcf8f745197.png)

**Comment by stephamon** [comment]
Hi @misskristenbrown thanks for the update! We'll pull this into our next sprint and get it taken care of.
