### ISSUE TITLE
Broken links on RPC page

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/rackspace-how-to#1936]
Hi,

The Product Management team notified me that several links are broken on this page: https://support.rackspace.com/how-to/rpc-openstack/

Broken:
General resources, most links in this section do not resolve

All links titled Rackspace Private Cloud Support are broken

v11 (Kilo) OpenStack Ansible Installation Guide - 404

**Comment by ReneeRendon** [comment]
Thank you for reporting this to us @robb-romans. We will get on this today.
