### ISSUE TITLE
Top Articles Report

### ISSUE THREAD

**Issue by aldrichcory1** [rackerlabs/rackspace-how-to#1950]
Hello All!

I am currently looking for a report of top 15 viewed articles for the How-To Cloud Office database (in the last 3 months or so should be good). I am going to be using this for a presentation. Thank you in advance!

Cory Aldrich

**Comment by stephamon** [comment]
Hi @aldrichcory1 I've pulled together a list for you. I'll send it to you through email :)

**Comment by aldrichcory1** [comment]
Thank you so much!
