### ISSUE TITLE
Full audit: Getting started with Cloud Files and CDN

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-how-to#1970]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-files/getting-started-with-cloud-files-and-cdn.md

**Comment by stephamon** [comment]
Confirmed from SME that content is still up-to-date.

@kmsholcomb Can you edit this please?

**Comment by kmsholcomb** [comment]
will tackle it tomorrow

**Comment by kmsholcomb** [comment]
Hi @stephamon. Goodness, this article had a ton of marketing content in it! You might not be surprised to hear that I suggest taking all that out and streamlining the article to truly just get users started with Cloud Files and CDN. Let me know if you have any questions. Thanks!

[Getting started with Cloud Files and CDN_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1029885/Getting.started.with.Cloud.Files.and.CDN_editsKH.pdf)
[Getting started with Cloud Files and CDN_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1029884/Getting.started.with.Cloud.Files.and.CDN_editsKH.docx)
