### ISSUE TITLE
Internal Issue: CBD

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1976]
This issue is documented internally.

**Comment by catlook** [comment]
I know how to archive H2 articles.  Researching how to retire API docs.

**Comment by catlook** [comment]
So H2 articles are gone.  Here is API PR: https://github.com/rackerlabs/nexus-control/pull/734

I think there may be more to be done to wrap this up.  I'm working on it.

**Comment by ReneeRendon** [comment]
This has been completed.

**Comment by catlook** [comment]
Here's the rest, courtesy of Catherine with assist from Laura S:

https://github.com/rackerlabs/nexus-control/pull/735
https://github.com/rackerlabs/docs-quickstart/pull/144
