### ISSUE TITLE
Make sure "General Purpose" server articles are technically accurate

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#1982]
There's a possibility that all instances of "Performance" server may have been replaced with "General Purpose". This is technically inaccurate because the requirements for a Performance server are different from that of a General Purpose server. 

We need to make sure that all instances of General Purpose within the How-To are technically accurate. @reydelarack will assist with ensuring the technical accuracy of the following articles:

**Note**: The list only includes articles where General Purpose servers are mentioned in relation to Performance, work optimized, and i/o servers.

- [x] https://support.rackspace.com/how-to/rackspace-cloud-backup-vs-cloud-server-image-backups/ (Line 48)

- [x] https://support.rackspace.com/how-to/cloud-image-creation-format-and-process/ (Line 81)

- [x] https://support.rackspace.com/how-to/before-you-move-to-general-purpose-or-io-cloud-server-checklist/ (Lines 4 - 46)

- [x] https://support.rackspace.com/how-to/cloud-server-image-limitations/ (Line 43)

- [x] https://support.rackspace.com/how-to/cloud-server-name-transitions/ (Lines 25 - 46) 

- [x] https://support.rackspace.com/how-to/cloud-servers-faq/ (Lines 269, 357, 437)

- [ ] https://support.rackspace.com/how-to/list-cloud-servers-and-cloud-server-information/ (Lines 38, 49, 51, 70, 100)

- [x] https://support.rackspace.com/how-to/new-features-in-general-purpose-and-work-optimized-cloud-servers/ (whole article)

- [ ] https://support.rackspace.com/how-to/rackspace-cloud-essentials-choosing-the-right-size-cloud-server/ (Lines 28 - 38)

- [x] https://support.rackspace.com/how-to/upgrading-resources-for-general-purpose-or-io-optimized-cloud-servers/  (whole article)

- [x] https://support.rackspace.com/how-to/rackspace-auto-scale-tips-and-how-tos/ (Lines 393 - 402)

**Comment by DonNateR** [comment]
@reydelarack: I've switched the list of articles I made to a checklist so we can keep track of which articles we have already addressed.

**Comment by reydelarack** [comment]
@DonNateR I'm in favor of retiring https://support.rackspace.com/how-to/cloud-server-name-transitions/ completely. It's been 3 years since the rebranding and it's less confusing to get rid of it as opposed to correcting it.

**Comment by DonNateR** [comment]
@reydelarack: Do any of the other articles on this list need to be updated?

**Comment by reydelarack** [comment]
@DonNateR I think there is still a little work left. Let me check with another member of my team who was also working on this documentation project.

**Comment by DonNateR** [comment]
@reydelarack: Have you heard back from that other team member?

**Comment by DonNateR** [comment]
Final two articles moved to new issues.
