### ISSUE TITLE
Access slow query and general logs for Cloud Databases, 'log_queries_not_using_indexes' description misleading.

### ISSUE THREAD

**Issue by arthibald** [rackerlabs/rackspace-how-to#1986]
On the [access-slow-query-and-general-logs-for-cloud-databases how-to page](https://support.rackspace.com/how-to/access-slow-query-and-general-logs-for-cloud-databases/) the description for the configuration parameter _log_queries_not_using_indexes_ is listed as: 

> Whether or not to log slow queries that use indexes.  Default is 0 (off)

This isn't quite correct. From [the relevant MySQL docs](https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_log_queries_not_using_indexes) the description is:

> Whether queries that do not use indexes are logged to the slow query log.

A more useful description is available from [the relevant MariaDB docs](https://mariadb.com/kb/en/mariadb/server-system-variables/#log_queries_not_using_indexes) and is 

> Queries that don't use an index, or that perform a full index scan where the index doesn't limit the number of rows, will be logged to the slow query log (regardless of time taken). The slow query log needs to be enabled for this to have an effect.

**Comment by nimbinatus** [comment]
Thanks for the informatin, @arthibald! We will pull this into our next sprint.
