### ISSUE TITLE
Update How-to articles that refer to **Account Settings* to point to the "View and reset your API key" article

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/rackspace-how-to#2025]
Pointing to the one article will hopefully require changes only in 1 location for any Control Panel changes in the future. 

I used the Atom editor to find these occurrences of **Account Settings** in the Content folder that might need to be changed based on the updates to the Cloud Control Panel (I did not include files for email or rackconnect which seems to be ok as is):

cloud-big-data/getting-data-into-your-big-data-cluster.md: line 45
cloud-files/configuring-rackspace-cloud-files-with-cyberduck.md: lines 26, 30, 54, 58
cloud-servers/configure-cloud-feeds-archiving-in-the-cloud-control-panel.md: line 49
cloud-servers/faw-for-seamless-sign-on-between-myrackspace-and-the-cloud-control-panel.md: line 154
cloud-servers/multi-factor-authentication-from-the-cloud-control-panel.md: lines 100, 133, 175, 180, 200, 262, 268, 274, 281, 298, 316, 326
cloud-servers/using-onmetal-cloud-servers-through-api.md: line 54
general/change-account-information.md: line 33, 58, 63
general/rackspace-billing-faq-md: line 126, 127
general/viewing-and-editing-user-information-for-your-account.md: lines 15, 19, 21

**Comment by ReneeRendon** [comment]
We don't need to mess with the Big Data articles. That is going away in two weeks.
