### ISSUE TITLE
Full audit: support-ticket-statuses

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#2026]
Ticketing has gone through some changes recently. We need to ensure that the information in this article has kept up with the changes.

https://support.rackspace.com/how-to/support-ticket-statuses/

**Comment by stephamon** [comment]
Melissa U. might be a good starting point for tracking down a SME.

**Comment by DonNateR** [comment]
Emailed Reach team for SME review. I'll email other support techs if I don't hear back by Monday.
