### ISSUE TITLE
Remove Example sites  cms-comparison-drupal-joomla-and-wordpress

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#2027]
Remove Example sites from the table in this article. 

https://github.com/rackerlabs/rackspace-how-to/blob/master/content/general/cms-comparison-drupal-joomla-and-wordpress.md

**Comment by ReneeRendon** [comment]
We can perform a full audit later. A ticket has been created in the Backlog Projects, but it is a lower priority than others in the backlog.

**Comment by catlook** [comment]
I'm assuming this is the line you want removed: 
| **Caching plug-ins** | [Pressflow](http://pressflow.org/) is a downloadable version of Drupal that comes bundled with popular enhancements in key areas, including performance and scalability. | [JotCache](http://extensions.joomla.org/extension/jotcache) offers page caching in the Joomla 1.5 search framework, resulting in fast page downloads. It also provides control over what content is cached and what is not. In addition, page caching is supported by the System Cache Plugin that comes with Joomla. | The [WP-SuperCache](http://wordpress.org/extend/plugins/wp-super-cache/) plug-in optimizes performance by generating static HTML files from database-driven content for faster load times. |

**Comment by catlook** [comment]
done

**Comment by ReneeRendon** [comment]
I am talking about the section in the table that is specifically called Example sites.
