### ISSUE TITLE
NEW Article: Create an article that focuses on the sign up process at Rackspace

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#2034]
Here is some information to get started. This blog is very out-dated but is a great starting point for the How-To article. 

https://blog.rackspace.com/signing-up-for-cloud-servers

Additional information is located on an email sent to the How-To team from Renée on May 17, 2017 around 8:25 PM.

**Comment by ReneeRendon** [comment]
Contact Tracy H with the blog team when the article has been published.

**Comment by DonNateR** [comment]
PR #2118 is awaiting a technical review. I've tested these steps myself, but I want to make sure that the information surrounding those steps is written accurately.
