### ISSUE TITLE
Views for Article - Fix Outlook synchronization errors

### ISSUE THREAD

**Issue by aldrichcory1** [rackerlabs/rackspace-how-to#2038]
Hey!

Can you guys please provide me the views on this article for the last 30 days? Here it is:

Fix Outlook synchronization errors

https://github.com/rackerlabs/rackspace-how-to/blob/master/content/rackspace-email/rackspace-email-mailbox-features.md

Thank you!

Cory Aldrich

**Comment by ReneeRendon** [comment]
Hi @aldrichcory1 
I sent you the pageviews for two different articles. Let me know if that is what you needed.
