### ISSUE TITLE
Page visit statistics request

### ISSUE THREAD

**Issue by WilliamLoy** [rackerlabs/rackspace-how-to#2042]
Hello How-to team!

I would appreciate the stats for page visits from 04/01/2017-04/30/2017 for the following pages:

https://support.rackspace.com/how-to/rackspace-email/
https://support.rackspace.com/how-to/set-up-dns-records-for-cloud-office-email-and-skype-for-business/
https://support.rackspace.com/how-to/best-practices-for-sending-emails-to-many-recipients/
https://support.rackspace.com/how-to/best-practices-for-sending-person-to-person-email/
https://support.rackspace.com/how-to/rackspace-email-and-hosted-exchange-settings/

Thank you, Will

**Comment by stephamon** [comment]
@WilliamLoy here are the pageviews from 04/01 - 04/30:

Rackspace Email - 6,442
Set up DNS records for Cloud Office email and Skype for Business - 6,159
Best practices for sending emails to many recipients - 493
Best practices for sending person-to-person email - 225
Rackspace Email and Hosted Exchange settings - 9,718

**Comment by stephamon** [comment]
Hey @WilliamLoy was there anything else you needed, or can I close this issue?

**Comment by WilliamLoy** [comment]
That is great for now! I will open a new issue when I am ready for new stats.
