### ISSUE TITLE
Create sections in Rackspace Email and Exchange intro pages for new article links

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-how-to#2045]
Link new articles created by William to the Rackspace Email and Exchange intro pages

**Comment by WilliamLoy** [comment]
Please place links in the Exchange product folder that link back to the following articles:
Best practices for sending person to person email
Best practices for sending emails to many recipients 
Cloud Office blocked attachment files
Cloud Office terms
Common email bounces
Find DNS host
Set up DNS records for Cloud Office email

Thanks @stephamon!

**Comment by stephamon** [comment]
Hey @WilliamLoy do you want me to go ahead and add these articles to the intro pages, or wait until y'all figure out the overall content strategy?

**Comment by WilliamLoy** [comment]
@stephamon I am so sorry I did not see this. I think the latter would be best. We want to reorganize the intro pages so may be best to wait until we have a solidified plan for that.

**Comment by stephamon** [comment]
@WilliamLoy No worries! I'm going to go ahead and close out this issue for now, and we can address it later :)
