### ISSUE TITLE
Changes to Article "Add a Signature to Rackspace Email"

### ISSUE THREAD

**Issue by aldrichcory1** [rackerlabs/rackspace-how-to#2050]
Article Link: https://github.com/rackerlabs/rackspace-how-to/blob/master/content/rackspace-email/adding-a-signature-to-rackspace-email.md

For this article, we will just be replacing all of the screenshots. Here they are, in order:

![image](https://cloud.githubusercontent.com/assets/21182797/26512613/f4b4546e-422c-11e7-9d5e-a70d69ae6d49.png)

![image](https://cloud.githubusercontent.com/assets/21182797/26512619/fa6e1e1c-422c-11e7-8c3b-0209eeab8518.png)

![image](https://cloud.githubusercontent.com/assets/21182797/26512630/052c9d60-422d-11e7-8c3a-4f08876ba827.png)

![image](https://cloud.githubusercontent.com/assets/21182797/26512633/09ec283e-422d-11e7-9a08-f27858e9e60e.png)

![image](https://cloud.githubusercontent.com/assets/21182797/26512638/0eb02442-422d-11e7-8dd8-0ce536d95c49.png)

**Comment by aldrichcory1** [comment]
Let me know if y'all have any questions. Thank you!

**Comment by ReneeRendon** [comment]
We may not need to use all of the screenshots for this article.

**Comment by stephamon** [comment]
Yeah, I think we could probably just use descriptive text for some of them :)
