### ISSUE TITLE
Please Update Article - Rackspace Email Mailbox Features

### ISSUE THREAD

**Issue by aldrichcory1** [rackerlabs/rackspace-how-to#2051]
Article Link: https://github.com/rackerlabs/rackspace-how-to/blob/master/content/rackspace-email/rackspace-email-mailbox-features.md

In the "Webmail" section (the last bold section), please add a bullet point with the following:

- To see more about Webmail, please visit: https://support.rackspace.com/how-to/rackspace-webmail/

**Comment by aldrichcory1** [comment]
thanks guys!

**Comment by DonNateR** [comment]
@aldrichcory1: Having looked over the articles, I would suggest that we retire this article. All of the features for each subject (Group lists, Aliases and Webmail) should just be added to the intro of their respective articles. 

There isn't a need for a "middle man" article like this one, especially considering that we can link to these articles in [Rackspace Email Control Panel Overview](https://support.rackspace.com/how-to/rackspace-email-control-panel-overview/) article.

Let me know your thoughts. 

@WilliamLoy: I would like to get your thoughts on this as well.

**Comment by aldrichcory1** [comment]
I agree. There are separate articles for each of these, and I can look at the content there. If anything is missing I can use what's in this article. What do you think, @WilliamLoy ?

**Comment by WilliamLoy** [comment]
@DonNateR  We are in agreement that these functions are feature rich enough to fill out their respective articles and retire this one. 

 I suggest for the time being we close this issue and table retiring the article until we have had time to cut and paste the relevant information from it.   We will create a new PR when we are ready to retire it.

**Comment by DonNateR** [comment]
@WilliamLoy: Actually, it might be easier to retire the article now. We archive all of our retired articles inside the repo, just in case. So, it will be easy to refer back to the article should it be needed. 

I'll leave the decision up to you though.

**Comment by WilliamLoy** [comment]
@DonNateR My only concern is that there are some instructions in that article that do not yet exist in other articles.  Even if the information is poorly placed it is still accessible for customers at the moment. I unfortunately cannot make the necessary updates to the standalone articles at the moment and likely will not be able to for at least a couple of weeks.

**Comment by DonNateR** [comment]
@WilliamLoy: I can bring over the info from this article into the applicable articles, then submit to you guys for review?

**Comment by WilliamLoy** [comment]
@DonNateR sorry I missed this. That sounds fantastic. Thank you!
