### ISSUE TITLE
Updates to Use pivot tables with your Cloud billing invoice

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-how-to#2089]
1. Text updates in section “View billing data in pivot tables” –  due to changes to the Billing UI, a few steps need to be updated and a new step #5 added which will require you to renumber the steps that come after it:

**EXISTING TEXT:**
3. In the top-right corner, click your user name and then select Billing and Payments.
4. Under Billing History, click the ID number for the invoice that you want to view.
5. On the Account Invoice page, export the CSV file.

**NEW TEXT:**
3. In the top-right corner, click your user name and then select Billing Overview.
4. Under Billing History, click Invoice Details.
5. In the Filter Invoice drop-down field, select the invoice that you want to view.
6. On the Invoice Details page, export the CSV file.
 
2. Text updates in section “About the CSV file” – an additional column header needs to be added to accurately describe columns in the CSV file:

**EXISTING LIST** (excerpt only):
RATE: The cost per chargeable unit
AMOUNT: The number of chargeable units

**NEW LIST:**
RATE: The cost per chargeable unit
CURRENCY:  The medium of exchange in which charges accrued are billed (for example, USD, AUD, GBP, EUR)
AMOUNT: The number of chargeable units
 
3. File updates in section “View billing data in pivot tables” – In instruction #1, there are three link options to download a spreadsheet based on the user’s application.  Each file needs to be updated by modifying a worksheet labeled "Invoice CSV Data" to include a missing column:

**EXISTING COLUMNS:**
Column L: RATE
Column M: AMOUNT

**NEW COLUMN BETWEEN EXISTING COLUMNS:**
Column L: RATE
Column M: CURRENCY
Column N: AMOUNT

**Comment by stephamon** [comment]
@nimbinatus by chance, do you know where the downloadable files in this article live? If you hover-over the text, they appear to be in a Cloud Files container somewhere.

**Comment by nimbinatus** [comment]
@stephamon, looks like they're in the `billing` container on mycloud under the how-to cloud account
