### ISSUE TITLE
Remove Article "Introduction to Mailgun Email Automation"

### ISSUE THREAD

**Issue by aldrichcory1** [rackerlabs/rackspace-how-to#2103]
Article Link: https://github.com/rackerlabs/rackspace-how-to/blob/master/content/rackspace-email/introduction-to-mailgun-email-automation.md

Please remove article from repository - we are no longer affiliated with Mailgun. Thank you!

**Comment by stephamon** [comment]
Move this article from Rackspace Email folder to General.
