### ISSUE TITLE
Regionalize UK support phone number

### ISSUE THREAD

**Issue by addi7054** [rackerlabs/rackspace-how-to#2114]
The UK team would like the support number at the top of support.rackspace.com to display the UK support number (0800-988-0300) if the visitor has a UK geo IP. 

Do you support regionalization on support.rackspace.com?

**Comment by ReneeRendon** [comment]
@addi7054 
Presently, we do not support regionalization on the support site, but we can still add the UK number.

**Comment by ReneeRendon** [comment]
I updated the file and will close this issue when the UK number appears in the header.

**Comment by addi7054** [comment]
Thank you! That would be great.

**Comment by ReneeRendon** [comment]
Number appears! Closing issue.
