### ISSUE TITLE
Shared IP creation URL missing tenant_id

### ISSUE THREAD

**Issue by xroot88** [rackerlabs/rackspace-how-to#2136]
The shared ip docs are wrong (something specific to servers).

https://developer.rackspace.com/docs/cloud-networks/v2/api-reference/shared-ip-address-operations/#retrieve-list-of-ip-addresses-explicitly-associated-with-a-server

"GET /v2/servers/{serverID}/ip_associations"

that's missing the tenant id, ie "/v2/{tenantID}/servers/{serverID}/ip_associations".

**Comment by cyrichardson** [comment]
@catlook It was noted by @nimbinatus that this API guide issue is reported against the How-To Center rather than the API docs. Because this is Cloud Servers, I added it to your queue.

**Comment by catlook** [comment]
Actually Cloud networks...though this op is servers.... https://github.com/rackerlabs/docs-cloud-networks/pull/131.  review requested.

**Comment by catlook** [comment]
networks PR merged, so this issue is closed :)
