### ISSUE TITLE
os:scheduler_hints wrong nesting in create server

### ISSUE THREAD

**Issue by xroot88** [rackerlabs/rackspace-how-to#2137]
The API docs for servers on this page is incorrect. I’m not sure if this page is deprecated or still in use:

https://developer.rackspace.com/docs/cloud-servers/v2/api-reference/svr-basic-operations/#post-create-server-with-sched-hint-servers

So, in the table describing the different key-value pairs describing the json body, it says that os:scheduler_hints should be nested under server, like so:

server.os:scheduler_hints

Which transforms to this:

{“server”:{… “os:scheduler_hints:{…}”}}

But this is how it actually should be:

server
os:scheduler_hints

Which transforms to this:

{“server”:{…}, “os:scheduler_hints:{…}"}

With respect to “nesting”, ‘server’ and ‘os:scheduler_hints’ should both be at the ‘top-level’ of the json request body.

If it helps for visualization, the example request body has it correct. The only thing wrong is the table.

**Comment by cyrichardson** [comment]
@catlook It was noted by @nimbinatus that this API guide issue is reported against the How-To Center rather than the API docs. Because this is Cloud Servers, I added it to your queue.

**Comment by catlook** [comment]
https://github.com/rackerlabs/docs-cloud-servers/pull/188

**Comment by catlook** [comment]
Scheduler hints is required for shared IP....so as long as shared IP is in play, this functionality is too.  I know it never got fleshed out as far as the team wanted, but I do believe basic functionality is there.

**Comment by catlook** [comment]
and done :)
