### ISSUE TITLE
Page visit stats for June

### ISSUE THREAD

**Issue by WilliamLoy** [rackerlabs/rackspace-how-to#2143]
Hello how-to team! 

May I trouble you for the page visit stats for the following articles in June?

Rackspace Email 
Set up DNS records for Cloud Office email and Skype for Business 
Best practices for sending emails to many recipients
Best practices for sending person-to-person email 

Thank you, Will

**Comment by WilliamLoy** [comment]
Can I also get the visits for the same articles for May? 

Thank you

**Comment by stephamon** [comment]
May 1-31 pageviews
- Rackspace Email - 6,718
- Set up DNS records for Cloud Office email and Skype for Business - 6,177
- Best practices for sending emails to many recipients - 511
- Best practices for sending person-to-person email - 168

June 1-30 pageviews
- Rackspace Email - 7.093
- Set up DNS records for Cloud Office email and Skype for Business - 141
- Best practices for sending emails to many recipients - 618
- Best practices for sending person-to-person email - 178

The Set up DNS records article is the one that we split in to two articles and redirected, so here are the stats for the new articles:
- Set up DNS records for Cloud Office email - (June) 5,728
- Set up DNS records for Cloud Office Skype for Business - (June) 132
