### ISSUE TITLE
page visits for all articles listed on https://support.rackspace.com/how-to/rackspace-email/ for Jan 2017- July 2017

### ISSUE THREAD

**Issue by WilliamLoy** [rackerlabs/rackspace-how-to#2167]
I would like the individual page visits for all articles linked on this page for Jan 2017 - July 2017

Thanks again!

**Comment by stephamon** [comment]
Jan - July 2017

Cloud Office Control Panel overview - 2,932
Account information in the Cloud Office Control Panel - 723
General information in the Cloud Office Control Panel - 309
Administrator management: Cloud Office Control Panel - 733
View administrator activity in the Cloud Office Control Panel - 355
Upgrades in the Cloud Office Control Panel - 231
Domains in the Cloud Office Control Panel - 855
View invoice history in the Cloud Office Control Panel - 153
View and pay unpaid invoices in the Cloud Office Control Panel - 98
Set up an API key in the Cloud Office Control Panel - 391
Email migration services - 4,015
Help tool for hosted email and Skype for Business - 3,326
Rackspace Email and Hosted Exchange settings - 637
Set up DNS records for Cloud Office email and Skype for Business - 33,724

We should probably change out that Set up DNS records link to the new, separate versions. Also, the "Access your mail" section takes you to apps.rackspace.com and the Email Help Tool.

**Comment by stephamon** [comment]
@WilliamLoy ^^

**Comment by stephamon** [comment]
Emailed the metrics.
