### ISSUE TITLE
Rackspace Email Archiving landing page views

### ISSUE THREAD

**Issue by WilliamLoy** [rackerlabs/rackspace-how-to#2269]
Can I please get the total page visits to https://support.rackspace.com/how-to/rackspace-email-archiving/ for January 2017- July 2017 as well as the click count for each listed link on this page?

Thank you!

**Comment by ReneeRendon** [comment]
JIRA ticket 459 has been created for this.

**Comment by ReneeRendon** [comment]
Completed.
