### ISSUE TITLE
Pageviews for Add self-service password recovery to your Rackspace Email Webmail site

### ISSUE THREAD

**Issue by WilliamLoy** [rackerlabs/rackspace-how-to#2399]
Hello how-to folks, 

Would you please provide the pageviews for https://support.rackspace.com/how-to/add-self-service-password-recovery-to-your-rackspace-email-webmail-site/ for 2017?

Thank you!

**Comment by catlook** [comment]
Added to Jira card: https://jira.rax.io/browse/INFODEV-990

**Comment by stephamon** [comment]
Hey @WilliamLoy, for Jan - Dec 2017, that article got 296 unique pageviews, and 340 total pageviews.
