### ISSUE TITLE
Cyberduck documentation needs clarity

### ISSUE THREAD

**Issue by 0x91** [rackerlabs/rackspace-how-to#2455]
1. The different instructions for US/UK customers don't make sense. I was able to authenticate against the supposed US only Rackspace Cloud Files built in connection with a UK account. Additionally the UK account steps tell you to use identity.api.rackspacecloud.com but the screenshot shows the actual LON keystone endpoint

2. The screenshots are for OS X but the latest Cyberduck version on windows has a different UI for adding a new bookmark.

3. There should be an example section for downloading an exported image similar to https://support.rackspace.com/how-to/use-swiftly-to-download-an-exported-image/

**Comment by catlook** [comment]
@0x91 Which article has the unclear documentation?  I'm guessing this one (https://support.rackspace.com/how-to/configuring-rackspace-cloud-files-with-cyberduck/), but will you confirm?

**Comment by catlook** [comment]
jira ticket ID 1004

**Comment by 0x91** [comment]
That's the article yes 👍

**Comment by catlook** [comment]
Ok, after much discussion, we plan to retire this article from the How-To.  Jackie Campbell will likely put up something similar in the Community, so the good info is not lost.  I'll make sure she's aware of the concerns you raised :)

**Comment by catlook** [comment]
Ok closing this.  The article was retired in #2504
