### ISSUE TITLE
Common Network Troubleshooting misleading for windows devices

### ISSUE THREAD

**Issue by 0x91** [rackerlabs/rackspace-how-to#2538]
While this is generally a very useful article the layout is wrong for windows devices.

It is split up into Tools installed by default and Other networking tools. The default section includes the following "The following tools are installed on all Windows, Mac, and Linux operating systems and servers by default.", only ping and traceroute - but as tracert - are installed by default on windows.

This should perhaps be further broken down into a Windows, Mac and Linux section and then a Mac and Linux section that includes telnet and netcat.

**Comment by catlook** [comment]
created JIRA card: INFODEV-1275.  Thanks!!

**Comment by catlook** [comment]
https://github.com/rackerlabs/rackspace-how-to/pull/2590
