### ISSUE TITLE
Fedora not Federa

### ISSUE THREAD

**Issue by toddarcher** [rackerlabs/rackspace-how-to#2556]
content/cloud-servers/supported-operating-systems.md

Shouldn't it be Fedora.. not Federa. 

Todd Archer 
Rackspace OPC
TAM II

**Comment by catlook** [comment]
ahem.  yes.  fixing ...

**Comment by catlook** [comment]
fixed - thanks for catching this and reporting it!

**Comment by toddarcher** [comment]
Thanks Cat.. now I can breathe better.


Todd Archer
Openstack Public Cloud
TAM II
[cid:image001.png@01D38D35.FD45CEB0]<https://www.certmetrics.com/amazon/public/badge.aspx?i=1&t=c&d=2018-01-12&ci=AWS00339546>
