### ISSUE TITLE
\\$ should be \$

### ISSUE THREAD

**Issue by catlook** [rackerlabs/rackspace-how-to#267]
here: https://github.com/rackerlabs/rackspace-how-to/blob/master/content/rackspace-cdn/create-a-rackspace-cdn-service.md
1. Click Create Service. A popup dialog box is displayed. (Pricing information is displayed under the drop down menu in the following figure. To get pricing information, click the dollar sign (\\$) icon.)

**Comment by cyrichardson** [comment]
Closed by PR #276
