### ISSUE TITLE
typo https://github.com/rackerlabs/rackspace-how-to/blob/master/content/skype-for-business/hosted-microsoft-lync-at-rackspace-deployment-guide.md

### ISSUE THREAD

**Issue by catlook** [rackerlabs/rackspace-how-to#268]
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/skype-for-business/hosted-microsoft-lync-at-rackspace-deployment-guide.md

**Comment by cyrichardson** [comment]
Fixed by PR #279
