### ISSUE TITLE
list not formatted https://github.com/rackerlabs/rackspace-how-to/blob/master/content/rackspace-email-archiving/create-an-archive-audit-report.md

### ISSUE THREAD

**Issue by catlook** [rackerlabs/rackspace-how-to#273]
list is wrapping around here: 

4. From the Choose report dropdown menu, select one of the following report types: - Activity by User—This report lists all users, their actions, the date of the actions, and the number of times that the actions were performed. - Activity by UI Action—This report lists all actions in alphabetical order, the users that performed the actions, the date, and the number of times that the actions were performed. - Activity by Date—This report lists by date the users who performed actions, the action performed, and the number of times that the actions were performed. - Collection by Mailbox—A collection indexes gathered email data and makes it searchable. This occurs automatically nightly. This report lists mailboxes, the number of email messages collected, the data size, and the date collected. These mailboxes are not your user mailboxes; they are collection points, and there is usually just one per account. - Collection by Date—A collection indexes gathered email data and makes it searchable. This occurs automatically nightly. This report lists the dates of collections, the number of email messages collected, the data size, and the mailbox collection point.

**Comment by cyrichardson** [comment]
Fixed by PR #280

**Comment by cyrichardson** [comment]
Re-opened as my fix does not fix this although it looks ok in the Atom editor preview. Cat reported this list wrapping as an issue. I will add it to the KC migration spreadsheet and assign to Steve.

**Comment by cyrichardson** [comment]
Made another run at this with success. PR #299
