### ISSUE TITLE
another malformed list https://github.com/rackerlabs/rackspace-how-to/blob/master/content/rackspace-email-archiving/create-an-archive-search.md

### ISSUE THREAD

**Issue by catlook** [rackerlabs/rackspace-how-to#274]
here:
5. Click the tab for the type of search and choose from four different search types: - Simple—Search for text in messages or attachments. - Wizard—Add conditions to the search query and inspect all parts of the message, including sender, recipient, subject, body, and attachment. - Advanced—Search by sender, recipient, subject, body, and attachment with greater fine-tuning control. For more information, see “Advanced Search” after these steps.

and here:
9. You now can chose any optional parameters for the search. - Dates allows you to select when dates you want the search to include. - Tags assist in categorizing searches.Tags can be predefined under the Settings tab. To access predefined tags, click Tags on the New Search page. - Legal hold allows you to sort out results on legal hold. - Note allows you to describe the search.

**Comment by cyrichardson** [comment]
Fixed by PR #280

**Comment by cyrichardson** [comment]
Re-opened and adding to the KC migrations issues list as my changes did not fix the problem although the Atom editor preview showed that it should have.

**Comment by cyrichardson** [comment]
Made another run at this with success. PR #299
