### ISSUE TITLE
How to discover the OS_IMAGE_URL?

### ISSUE THREAD

**Issue by jaraco** [rackerlabs/rackspace-how-to#3595]
I'm trying to follow [these directions](https://support.rackspace.com/how-to/transferring-images-between-regions-of-the-rackspace-open-cloud/), but they require setting an `OS_IMAGE_URL` variable, and it's not at all obvious what that URL is or how one would go about discovering it. How would one do that? Can the docs provide or link to guidance on discovering these settings?

Additionally, it's confusing that these variables are set in an "optional" section, given that they're required in subsequent, non-optional steps.

**Comment by jaraco** [comment]
It looks like maybe [configuring environment variables](https://developer.rackspace.com/docs/cloud-images/v2/getting-started/authenticate/#configure-environment-variables) provides some hints.

**Comment by catlook** [comment]
Hey, Jason, let me track down one of our Cloud Image experts.  When I get an answer, I'll post here and update the doc!

**Comment by catlook** [comment]
Ok, I got this additional information for you. Let me know if you got the answer you needed. 

The OS_IMAGE_URL in the example is the same URL provided by authenticating to Cloud Identity: 
https://iad.images.api.rackspacecloud.com/v2

Where "iad" is the region.

Export Image:  https://developer.rackspace.com/docs/cloud-images/v2/api-reference/image-task-operations/#task-to-export-image

Import Image: https://developer.rackspace.com/docs/cloud-images/v2/api-reference/image-task-operations/#task-to-import-image

Get Task: (see details about task):  https://developer.rackspace.com/docs/cloud-images/v2/api-reference/image-task-operations/#get-task-details

**Comment by jaraco** [comment]
Thanks Catlook. That really helps. Please consider updating the instructions with a similar hint, so the next person doesn't encounter this issue. Thanks.
