### ISSUE TITLE
Where is "the migration plan provided"?

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/rackspace-how-to#391]
Both 
https://www.rackspace.com/knowledge_center/article/upgrading-to-exchange-2016
&
https://www.rackspace.com/knowledge_center/article/upgrading-to-exchange-2013
advise readers to "review the migration plan provided". Where is this plan provided? It's not explained and no link is offered.

**Comment by stephamon** [comment]
Emailed ea_content@rackspace.com
