### ISSUE TITLE
Maintain one list of role-based public folder permissions

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/rackspace-how-to#393]
Public folder permissions are explained identically, other than formatting, in at least 2 articles:

- /how-to/microsoft-exchange-public-folders/ formats it as a table

- /how-to/working-with-public-folders-through-outlook-for-exchange-2007-and-2010/ formats it as a list

Pulling the permissions matrix into its own article, then linking to it from these articles rather than reproducing the content in them, will make it easier to read those articles, and easier to find tand maintain the permissions matrix.

**Comment by stephamon** [comment]
Fixed by #520

**Comment by stephamon** [comment]
Connect to #520
