### ISSUE TITLE
Confirm references to Cloud Drive in Exchange Control Panel doc

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/rackspace-how-to#404]
Cloud Drive is mentioned in text and shown in several screenshots at https://support.rackspace.com/how-to/microsoft-exchange-cloud-office-control-panel-overview/. Is Cloud Drive still available in this way?

**Comment by stephamon** [comment]
Emailed ea_content@rackspace.com

**Comment by stephamon** [comment]
Beau's going to get the edits to me by EOD today.
