### ISSUE TITLE
Delete note about SiteScope upgrade if that work is complete

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/rackspace-how-to#405]
At https://support.rackspace.com/how-to/getting-started-with-rackspace-intelligence-for-dedicated-accounts/, a note says "The effort to upgrade devices from Sitescope to Rackspace Monitoring starts on October 15, 2015 and is expected to be completed before the end of the 2015." It's now February 2016. Can the note be deleted?

**Comment by DonNateR** [comment]
Investigated this issue, and confirmed that the note can be deleted.

**Comment by DonNateR** [comment]
https://github.com/rackerlabs/rackspace-how-to/pull/580
