### ISSUE TITLE
Clarify status of Rackspace Intelligence for dedicated accounts

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/rackspace-how-to#407]
The Rackspace Intelligence FAQ at https://support.rackspace.com/how-to/rackspace-intelligence-faq/ states that Rackspace Intelligence is not available for dedicated **resources**:

_Q: Can I use Rackspace Intelligence for both Cloud and Dedicated resources?

A: Currently you can use Rackspace Intelligence for your Cloud resources only. The Rackspace Intelligence development team is working to enable you to use it for your Dedicated resources also. We expect this to be available soon and will keep you updated._

However, Rackspace Intelligence for dedicated **accounts** is discussed in several articles; the Introduction article at https://support.rackspace.com/how-to/rackspace-intelligence/ links to them. (It only does that because I made it so, after finding some articles focused on Cloud and others on Dedicated; when we began the post-migration audit, there was no separate Introduction article and /rackspace-intelligence/ completely duplicated the content of /differences-between-rackspace-intelligence-for-cloud-accounts-and-dedicated-accounts/.)

The difference intended by  **resources** versus **accounts** is unclear, and it's easy to miss that one-word difference. Is it a real difference, or is the FAQ statement outdated?

**Comment by rose-coste** [comment]
In the same FAQ, "Access to Rackspace Intelligence for Rackspace Dedicated customers" is listed under _What features will be available in the future?_

**Comment by ReneeRendon** [comment]
We should address this issue when we start working on #597.

**Comment by stephamon** [comment]
Not sure who to contact on this one, so I've reached out to Shane Duan to see if he can point me in the right direction.

**Comment by stephamon** [comment]
Kapil Kansal is the PM for Rackspace Intelligence, with whom Shane has put me in contact. My general sense so far is that the "resources" language is out of date.
