### ISSUE TITLE
Check status of "in the future" references

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/rackspace-how-to#409]
For example, the FAQ for Rackspace Intelligence lists several items under "What features will be available in the future?". One of those, about adding Dedicated capabilities, is mentioned in issue #407 as requiring a factcheck; there are many others. Searching this repo for the word "future" (https://github.com/rackerlabs/rackspace-how-to/search?utf8=%E2%9C%93&q=future) returns 65 results. I suggest investigating all of them and perhaps, for any that remain "in the future", adding an as-of date so it's easier to notice where the future may have slipped quietly into the past.

**Comment by ReneeRendon** [comment]
Address this issue when working on issue #597

**Comment by ReneeRendon** [comment]
Audit for references of "future" and correct any that need fixing. As of February 2, Rose found 65 references.

**Comment by ReneeRendon** [comment]
Waiting on Dedicated.
