### ISSUE TITLE
Link to API doc in its current location

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/rackspace-how-to#411]
Most API doc is now at developer.rackspace.com/docs/, moved from docs.rackspace.com in late 2015. During this migration audit we corrected many links to API doc, pointing them to the new location, but many uncorrected links remain. Searching this repo for **"(http://docs.rackspace.com/"** (how-to/search?utf8=✓&q="(http%3A%2F%2Fdocs.rackspace.com%2F"&type=Code) returned 40 results. Some of those remaining links are correct, since Private Cloud did not move to developer.rackspace.com; others should be updated to get human and robotic readers directly to the right place.

**Comment by stephamon** [comment]
Fixed by #517
