### ISSUE TITLE
Add detail that monitoring agent may be pre-installed; show how to check.

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/rackspace-how-to#413]
https://support.rackspace.com/how-to/set-up-a-server-to-work-with-rackspace-intelligence/ and related articles identify a requirement to manually install a monitoring agent on servers that will be used with Rackspace Intelligence. However, as of July 2015 this installation can be automated when a server is created if the customer chose that option. To prevent customers from attempting to manually install what was already automatically installed, update doc that refers to installing the agent to add (link to?) instructions on checking whether the agent is already present.

**Comment by DonNateR** [comment]
This is already covered by the statements "chose the type of installation instructions you prefer". I updated the formatting and wording to make it more clear the installation can be automated.
