### ISSUE TITLE
Use consistent 'how-to' form in article titles

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/rackspace-how-to#416]
Inconsistency in article titles is most obvious in the "All Articles" view. For example, at https://support.rackspace.com/how-to/rackspace-intelligence-all-articles/:

- _Log in_ to Rackspace Intelligence for dedicated accounts
- _Logging in_ to the Rackspace Intelligence dashboard
- _Set up_ a server to work with Rackspace Intelligence
- _Setting up_ a database to work with Rackspace Intelligence

**Comment by kmsholcomb** [comment]
We've got guidelines at https://one.rackspace.com/display/devdoc/Titles+and+headings#Titlesandheadings-KCarticletitlesandheadings.

**Comment by stephamon** [comment]
This is a pretty major undertaking. What needs to be done here, by product:
1. Standardize article titles as per style guidelines
2. Update links to reflect changed article titles
3. Update any redirects that pointed to old article title (may need to bring Keith in for this one)

I'll crawl through the repo and compile a list of which articles would be affected by this effort, so we'll have an idea of how big a project this is.

**Comment by stephamon** [comment]
https://docs.google.com/spreadsheets/d/1Fmt66NZ4S-lP_b0vFYC1kqwrfqKVIc8jTHyXxUEeIS4/edit#gid=0

**Comment by catlook** [comment]
PR #740 DNS
PR #741 IMAGES

**Comment by catlook** [comment]
Ok, all done.  Check the spreadsheet for all the PRs.  Note:  I only checked the articles (best candidates) in the spreadsheet, so other titles may need to change.  Also, I didn't change titles of articles that were split from books.  We need to revisit how to handle and name those (or recombine them).
