### ISSUE TITLE
Update "Cloud User Guide" link in top blue/gray nav to link directly to User Guide

### ISSUE THREAD

**Issue by trentgillaspie** [rackerlabs/rackspace-how-to#463]
The "Cloud User Guide" link at the top blue/gray nav should directly link to the User Guide (https://developer.rackspace.com/docs/user-guides/infrastructure/) instead of adding the interstitial linked page of https://support.rackspace.com/how-to/#core-user-guide. Saves the user a step in the process.

**Comment by stephamon** [comment]
@ktbartholomew or @smashwilson do you know how to go about doing this?
