### ISSUE TITLE
Update Rackspace Open Cloud Reference Architecture

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#521]
From: Tawney Carter tawney.carter@RACKSPACE.COM
Date: Wednesday, January 13, 2016 at 9:51 AM
To: Knowledge Center KB_center@rackspace.com
Cc: Christine Sawtelle christine.sawtelle@RACKSPACE.COM
Subject: Question about updating an article

Good Morning,

I recently had a customer ask me for a diagram of a cloud architecture that I had recommended.to him. This knowledge center article shows a very good image for a Basic Cloud Architecture but, I noticed that some of the labels are in odd places and there are a few labels that it would be nice to add. I have attached a power point slide with some notes that might help to clarify this image. I have made all changes in red.

https://www.rackspace.com/knowledge_center/article/rackspace-open-cloud-reference-architecture

Let me know if you have questions.

Most Sincerely,

Tawney Carter
Launch Manager II

tawney.carter@rackspace.com
phone: 210-312-2835
toll free: 1-855-348-9057

**Comment by DonNateR** [comment]
Powerpoint attached with Tawney's request.
[Knowledge_center_recommendation.pptx](https://github.com/rackerlabs/rackspace-how-to/files/144974/Knowledge_center_recommendation.pptx)

**Comment by DonNateR** [comment]
The reference architecture project has been abandoned in favor of deployment architectures using Carina. This mean's that I need to update the graphs personally.

**Comment by ReneeRendon** [comment]
@DonNateR How long will it take to update the diagrams in this article?
