### ISSUE TITLE
Suggestion for Cloud server Security article

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#523]
Everett Toews recommended incorporating his script into this article: https://support.rackspace.com/how-to/basic-cloud-server-security/

His script is located here: https://github.com/everett-toews/rackspace-developer-doubleplusgood/blob/gh-pages/scripts/secure.sh

-Need to determine if this article should be broken down into more than one article.

-Needs to be reviewed by the Managed Security folks.

**Comment by DonNateR** [comment]
Renee: Here is more detail from the Slack conversation.

@renee: this sounds like something we need a kc article for. and it's something that should be reviewed by the managed security folks.
[1:34 PM]
Stephanie Fillmon We've got this for server security: https://support.rackspace.com/how-to/basic-cloud-server-security/
[1:35 PM]
But it doesn't look like it includes what Everett linked
[1:36 PM]
Renee Rendon @everett: @stephamon Got it. I'll create a story for this.
[1:38 PM]
Everett Toews so it kinda includes some of the stuff i have in my script.
[1:40 PM]
since that how-to is "Basic" i'd argue that having iptables in there is anything but basic.
[1:40 PM]
Stephanie Fillmon Hah, yeah it could probably use a little work
[1:40 PM]
It was first created in 2011, so it's kind of... organic
[1:41 PM]
Everett Toews and you can avoid a lot of monkeying with ssh keys by just creating the server with an key pair.

**Comment by kylelaffoon** [comment]
Checked with Everett on his preferred presentation of the script. His thought is to have a separate file for the script linked within the article with a basic introductory statement. He is discussing with Keith tomorrow.

**Comment by kylelaffoon** [comment]
Posted question to Keith and included Everett to usher the discussion of Nexus options on this.
