### ISSUE TITLE
Remove outdated DNS records from DNS articles

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#524]

**Comment by DonNateR** [comment]
From: Jason Bratton jbratton@rackspace.com
Date: Monday, February 15, 2016 at 7:27 PM
To: Joe Mcbride jmcbride@rackspace.com, Cat Lookabaugh cat.lookabaugh@RACKSPACE.COM, Nicole Hairston nicole.hairston@RACKSPACE.COM
Subject: RE: KC article possible bug

Was DNRaaS a subtle reference to how the last meeting went today? J

We actually have two businesses within Rackspace that offer registrar services, and those are Email & Apps (Rackspace Email) and Cloud Sites. They resell different registrars, and for some reason, we’ve never made a company-wide effort to offer registrar services to any type of customer. Back when all we offered was dedicated servers, it was a more complicated issue because customer contracts could expire but yet we would still be required to continue managing their domain. Now, that obstacle really doesn’t exist. There’s a decent opportunity in front of us, but I don’t know what the business case would end up looking like.

I would definitely like to see the stabletransit records go away, but I think there needs to be communications sent out at the same time as the docs start being updated. Otherwise, it could cause some serious confusion and miscommunication. At the very least, all of our customer-facing rackers in support, netsec, cloud escalations, and possibly others need to be notified.

Also, do zones being created through Reach and/or the DNSaaS API still receive stabletransit NS records? If so, that would also need to be changed. And I know DCX defaults to stabletransit, although I’d imagine that is a fairly easy change. I’d try to line up comms and changing defaults with changing the docs to avoid any confusion. But it would definitely be nice to see this done.

Thanks!

Jason Bratton
Manager, Systems Engineering

**Comment by DonNateR** [comment]
From: Joe Mcbride
Sent: Monday, February 15, 2016 4:57 PM
To: Cat Lookabaugh cat.lookabaugh@RACKSPACE.COM; Nicole Hairston nicole.hairston@RACKSPACE.COM; Jason Bratton jbratton@rackspace.com
Subject: Re: KC article possible bug

Cat: Cloud Sites offers domain name registration, although the service is tightly integrated with their product and is not offered to other parts of the business as a DNRaaS. I believe the statement, "“We are not a domain registrar,”" can be considered accurate. That said, Cloud sites is a domain name registration reseller, not a "registrar" in the formal sense.

In the article, I see one glaring issue that we (the DNS team) would like to address: discontinue the use of dns1.stabletransit.com & dns2.stabletransit.com.

Jason and Nicole - do you think we are at a point in which we can begin updating our docs and policies to reflect this direction?

Joe McBride
Rackspace Cloud DNS

**Comment by DonNateR** [comment]
From: Christie Quaranto christie.quaranto@RACKSPACE.COM
Date: Monday, February 15, 2016 at 3:31 PM
To: Renee renee.rendon@rackspace.com
Subject: KC article possible bug

Hi Renee,

Just saw this KC article, and I think some of the info is incorrect. Under “We are not a domain registrar,” unless something has changed, I believe we do offer domain registration services.

https://support.rackspace.com/how-to/rackspace-cloud-essentials-transferring-your-domain-to-be-served-from-rackspace-cloud/

Christie Quaranto
Manager, User Experience
Rackspace Experience Design (RED)

**Comment by DonNateR** [comment]
Placing Blocked on this one, until we get a better idea of how we plan on addressing the quality of all of our old articles moving forward.

**Comment by DonNateR** [comment]
According to the above email thread, the DNS team has requested that we discontinue the use of **dns1.stabletransit.com** and **dns2.stabletransit.com** from the article listed in the thread above. 

The following search catalogues every instance of **dns.stabletransit.com**:

https://github.com/rackerlabs/rackspace-how-to/search?p=1&q=dns1.stabletransit.com&utf8=%E2%9C%93

Following the logic of the email thread, it stands to reason that all of the articles containing **dns.stabletransit.com** need to be updated.

However, this effort needs to be aligned with the DNS team, to make sure we line up communications and ensure that Reach and the DNS API are still not using stabletransit records.

**Comment by DonNateR** [comment]
Nate,

Greetings! Thanks for bringing this back up. As you probably noticed, Jason is on vacation until the 25th.

While I have been handling a measure of his outstanding technical items while he's on out, this is one I would prefer to leave for him when he gets back. I don't think the world is going to burn down in the next three weeks if we don't purge those names from everywhere.

I'd like to make sure it stays on the radar, though, so we can pick it up after he returns. I absolutely agree, those names need to go away.

Since you asked, and as a point of reference, there are 42,404 zones with dns1.stabletransit.com listed as an NS record.

Please let me know if you have any questions. Thanks!

Trumpy

**Comment by DonNateR** [comment]
Because we'll have to wait for Jason's return, we'll reopen this issue April 25th.

**Comment by ReneeRendon** [comment]
We'll reach out on this again.

**Comment by DonNateR** [comment]
New email from the same thread:

From: Nicole Hairston <nicole.hairston@RACKSPACE.COM>
Date: Wednesday, April 6, 2016 at 1:44 PM
To: Rackspace Hosting <Nate.Archer@rackspace.com>, Franklin Trumpy <franklin.trumpy@rackspace.com>, Jason Bratton <jbratton@rackspace.com>, Joe Mcbride <jmcbride@rackspace.com>, DNS Internal <dns_internal@rackspace.com>
Cc: Cat Lookabaugh <cat.lookabaugh@RACKSPACE.COM>, Hans Huberland <hans.huberland@RACKSPACE.COM>
Subject: RE: "Stabletransit" DNS records in How-To support documentation

All,
 
We had discussions about this recently during prep for the EA launch of Managed DNS, which (unlike Cloud DNS) defaults to ns/ns2 when provisioning zones. Hereis what we added to our Managed DNS docs:
 
Set up name servers with your domain registrar
Configure the name servers for your domain to ensure that your domain resolves properly. You can do this through your domain name registrar or by delegating a subzone from another zone.
Following are the authoritative Rackspace Managed DNS name servers:
·         ns.rackspace.com
·         ns2.rackspace.com
Domains provisioned by using Rackspace Cloud DNS default to the dns1.stabletransit.com and dns2.stabletransit.com name servers for the Rackspace public cloud. Because all Rackspace DNS has been consolidated under ns.rackspace.com and ns2.rackspace.com, the stabletransit names now also resolve to these name servers.
When Rackspace Managed DNS domains are provisioned, the system, by default, adds name server records for ns.rackspace.com and ns2.rackspace.com to phase out the stabletransit name servers. Although not required, customers can update their older Rackspace Cloud DNS domain delegation and name server records to specify ns.rackspace.com and ns2.rackspace.com.
 
We could probably modify this wording a bit and apply it as an update to current How-To articles that specify stabletransit as name servers for public cloud. Thoughts?
 
 
Thank you, 
Nicole
