### ISSUE TITLE
Delete the URL after a How-To article is deleted

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#526]
This is a two-part story.
1. Document the steps required to use Google webmaster tools to delete an article URL after the article has been removed from the repo. This will temporarily block it from search results.
2. Remove this URL using the steps that have been documented because this article has been deleted from the repo.
https://support.rackspace.com/how-to/configuring-openstack-block-storage/

**Comment by DonNateR** [comment]
Another URL needs to be removed. 

https://support.rackspace.com/how-to/manage-domains-cloud-office-control-panel/

**Comment by stephamon** [comment]
Update via Keith: the custom Google search created for the How-To search bar is from a dev-owned account that we currently don't have access to. 

From what I understand, they're working on getting access to it.

**Comment by DonNateR** [comment]
Here's another URL:

https://support.rackspace.com/how-to/migrating-from-a-pop-server-to-rackspace-email-imap-using-outlook-2010-drag-and-drop-method/

**Comment by ReneeRendon** [comment]
I have removed the above mentioned URLs and have documented the process on the wiki here. https://one.rackspace.com/display/devdoc/Delete+article+from+search+results

At this time, I have access to the Webmaster tools. @stephamon is the backup for this account.
