### ISSUE TITLE
Images FAQs update

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#528]
From: Rackspace Hosting catherine.richardson@RACKSPACE.COM
Date: Wednesday, September 30, 2015 at 10:01 AM
To: Cat Lookabaugh cat.lookabaugh@rackspace.com, Rackspace Hosting catherine.richardson@RACKSPACE.COM, Renee Rendon renee.rendon@rackspace.com
Cc: Brian Rosmaita brian.rosmaita@RACKSPACE.COM, Laura Clymer laura.clymer@rackspace.com
Subject: FW: Intermittent problem creating servers in REACH

Cat and Renee,

See the information below about an update to FAQs in the KC for Images.

I’ll open a Trello for this and put it in the KC Backlog.

Brian, Could you please make sure the information comes our way for this update?

Many thanks,
—Catherine
Devdocs: Senior Information Developer
Office: 506-1156
Cell: 512-750-0666

On 9/30/15, 9:49 AM, "Brian Rosmaita" brian.rosmaita@RACKSPACE.COM wrote:

Yannett,

James is correct, the reason this is occurring is that the image was
imported.
We only put a limited number of properties on imported images because we
have no way of knowing what's actually being imported [1]. It's up to the
customer to update the image in Cloud Images so that it's got accurate
metadata. However, since we use these properties for billing: org.openstack1os_distro
org.openstack1os_version

A customer can't create them; they'd have to ask support to do it.

So, the key point here is that as long as the customer calls support to
set the correct metadata on the imported image, volumes created from that
image will have the correct metadata, and then the Control Panel will be
happy.

Jigar and Bill, it would be good if you could provide a list of what
essential metadata you look for on both images and volumes. Then we'll
send it on to support so that they know what to do.

It would probably be a good idea to update the Cloud Images and Cloud
Block Storage FAQs with some information about "What do I need to do if I
want to create a bootable volume from an imported image?".

By the way, here's the metadata from that deleted image:

mysql> select name, value from image_properties where image_id =
'd3e3b6dd-b84b-4feb-ae81-f605d28126e1';
+---------------------------------------+----------------------------------
+
| name | value
|
+---------------------------------------+----------------------------------
+
| auto_disk_config | False
|
| com.rackspace1build_core | 1
|
| com.rackspace1build_managed | 1
|
| com.rackspace1build_rackconnect | 1
|
| com.rackspace1options | 0
|
| com.rackspace1source | import
|
| com.rackspace1visible_core | 1
|
| com.rackspace1visible_managed | 1
|
| com.rackspace1visible_rackconnect | 1
|
| image_type | import
|
| org.openstack1architecture | x64
|
| os_type | linux
|
| user_id | e9226d5c4df6403ea30b9b952595591b
|
+---------------------------------------+----------------------------------
+
13 rows in set (0.31 sec)

cheers,
brian

**Comment by DonNateR** [comment]
Emailed Brian to receive clarification on this issue.

**Comment by ostackbrian** [comment]
You'll need to verify this with reach, as the info is 6 months old.
The metadata that Reach expects to see in ‘volume_image_metadata’ on the volume is:
image_id
image_name
com.rackspace__1__options
os_type
org.openstack__1__os_version
org.openstack__1__os_distro

Except for the two org.openstack properties, these are all put onto the image by the import task.  So nothing for users to do there.  The two org.openstack properties are protected so that users can't mess modify them, they'd have to be put on an image by support.  BUT ... Reach may have been modified so that it doesn't need those values in order to display volumes generated from images.  So please check before updating the docs.

**Comment by DonNateR** [comment]
Checked in REACH. This feature has been automated. Closing issue.
