### ISSUE TITLE
Automation Documentation for Chef and Ansible

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#530]
Date: May 12, 2015

Michael just pushed the new chef cookbook that takes advantage of the best monitoring has to offer. I am not sure where in the documentation we can update but there should be places we can do it (and add reference to Ansible too)

Chef (KC article exists)

- www.rackspace.com/knowledge_center/article/cloud-monitoring-automation-integrate-monitoring-with-chef

- https://supermarket.chef.io/cookbooks/rackspace_monitoring

Ansible (Convert blog post to KC article):

- https://developer.rackspace.com/blog/automate-deploying-rackspace-cloud-monitoring-agent/

- https://galaxy.ansible.com/list#/roles/855

**Comment by stephamon** [comment]
Emailed Shane, who CC'd Mike Burns to get the article updated.

**Comment by stephamon** [comment]
Reached back out to Mike Burns, since I hadn't heard anything since Thursday.

**Comment by stephamon** [comment]
@ReneeRendon I reached back out to Mike Burns last week on Monday, and I still haven't heard anything back from him. I'm not really sure what to do about this one now.
