### ISSUE TITLE
How-to article? which IP ranges Rackspace uses for Cloud Monitoring?

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#531]
Hi,

This is to gauge your thoughts based on Jacob's feedback. No action other
than your opinion is needed at this time.

I looked at the available articles under Cloud Monitoring, and cannot
think of a good place for this information.

http://www.rackspace.com/knowledge_center/product-articles/cloud-monitoring

"Available checks for Cloud Monitoring" is sort of related, but it feels
more like a stretch.

I am thinking an article about how remote check works would be good. What
do you think? I feel that I have enough materials (diagram and internal
wiki pages) available.
https://one.rackspace.com/display/monitoring/Private+Network+Monitoring 
https://one.rackspace.com/display/monitoring/Cloud+Monitoring+Firewall+Requ
irements

Is there a search report in KC to see what people are searching for when
it comes to Cloud Monitoring?

Thanks ahead for your inputs.

Shane Duan
Product Manager, Monitoring Intelligence
Know your infrastructure through agents
MMI Office Hour: Thursday 2pm – 3 pm (Pacific Time) - Vidyo Room 7061

On 3/30/15, 3:18 PM, "Jacob Beeson" jacob.beeson@RACKSPACE.COM wrote:

Thank you team! That is something that should probably live in a customer
facing KB article but I have bookmarked it for future reference!

jacob

-----Original Message-----
From: Shane Duan
Sent: Thursday, March 26, 2015 12:09 PM
To: Jacob Beeson
Cc: Monitoring Integration
Subject: Re: confirmation of which IP ranges Rackspace uses for Cloud
Monitoring?

Hi Jacob,

The answer for the firewall requirement is here. It also has the
information about the monitoring API to call to pull the data.

https://one.rackspace.com/display/monitoring/Cloud+Monitoring+Firewall+Requirements

For future references, please send questions to
monitoring.integration@lists (copied). Often we get questions mixed
between cloud and dedicated customers, so this email address is a good
place to start.

cloudmonitoring@rackspace.com is an old email address that is outdated
and hard to update.

Cheers

Shane Duan
Product Manager, Monitoring Intelligence Know your infrastructure through
agents MMI Office Hour: Thursday 2pm ­ 3 pm (Pacific Time) - Vidyo Room
7061

On 3/26/15, 5:56 AM, "Jacob Beeson" jacob.beeson@RACKSPACE.COM wrote:

Hi Cloud Monitoring Team,

Can you help me locate this information? CloudFlare needs to add all of
our Rackspace Monitoring IPS to their global whitelist to ensure our
customers are able to effectively monitor their sites while also using
CloudFlare.

Also ... is this information that can be pulled via API so that
CloudFlare (and other companies with similar needs) can automate the
process of updating their database of cloud monitoring IP ranges?

jacob

-----Original Message-----
From: Jacob Beeson
Sent: Tuesday, March 24, 2015 5:02 PM
To: John Roberts
Subject: Re: confirmation of which IP ranges Rackspace uses for Cloud
Monitoring?

Thank you‹I of course assumed as much but know better than to assume.
I'll get the data and see if there is a way for you to poll the list
hopefully via API to automate it.

Jacob

Sent from my iPhone

On Mar 24, 2015, at 4:56 PM, John Roberts john@cloudflare.com wrote:

That's right. Global = everyone.

Individual customers can, of course, override the global settings.

But on the global whitelist means that security settings won't block
these requests under almost all circumstances.

Which is appropriate for valid monitoring and we do for Pingdom, New
Relic, and many others... so definitely want Rackspace treated
right... but ONLY for the ranges used for monitoring.

On Tue, Mar 24, 2015 at 2:52 PM, Jacob Beeson
jacob.beeson@rackspace.com wrote:

Let me check with the monitoring folks. If I understand you correctly
the Global Whitelist will be in effect for all CloudFlare customers not
just this one who has made the request‹correct?

Jacob

Sent from my iPhone

On Mar 24, 2015, at 4:15 PM, John Roberts john@cloudflare.com
wrote:

Jacob,

A joint customer was asking about whitelisting Cloud Monitoring IPs
from Rackspace in their CloudFlare control panel.

They gave me a list, but I wanted to confirm with someone in the
know at Rackspace before proceeding, because we are very careful
about adding to our global whitelist.

https://community.rackspace.com/products/f/25/t/3268 is 15 months
old, and the list the customer gave me has more ranges. And we don't
have an API key to check.

Help, please?

Thanks!

John Roberts
Platform lead
CloudFlare
john@cloudflare.com
+1-415-329-4000
Skype/Twitter: pencoyd

**Comment by DonNateR** [comment]
@wolfdancer: Is this issue still relevant/needed?

**Comment by wolfdancer** [comment]
@DonNateR do you have thoughts on the questions I posed in the email?

This is not something that I need you to deliver in the form of documentation.  So we can close this issue.  I still would like to hear your thoughts.

I did a bit more research and thought the right way would be to create a "Troubleshooting Remote Checks" how-to article (when I get around to it) that is similar to the agent trouble shooting guide (https://support.rackspace.com/how-to/troubleshooting-the-rackspace-monitoring-agent/) but applies to the remote checks.  The content would have:

* Move the content from here (https://developer.rackspace.com/docs/rackspace-monitoring/v1/developer-guide/#check-status-codes). They don't belong to an API doc.
* Add a section about the case when connection is refused and list several potential cases. In the case of firewall rule, mention the Monitoring Zones API (https://developer.rackspace.com/docs/rackspace-monitoring/v1/developer-guide/#listing-monitoring-zones) with an example of the 
* Update the monitoring zones API with the latest values.

**Comment by DonNateR** [comment]
@wolfdancer: Sorry for getting back to you so late. I like the idea of a new article for this subject. The more we consolidate content the better.

Out of curiosity, why would you like to remove the *check status codes* section from the API guide? I could be wrong, but can't those status codes be given through working with the Monitoring API as well? 

If you did wish to remove them, we can link to the new article within the developer guide or vice verse from the how-to article to the dev guide. Another idea would be to make the focus of the How-to article on *troubleshooting* when those status codes are received, and keeping the *status codes* table in the Dev Guide. 

Also, does monitoring zones API section in the documentation have the latest values as of right now?

**Comment by wolfdancer** [comment]
@DonNateR thanks for the comment.  The new documentation repo structure has made consolidation easier. Thanks to you and the team who made the change!

I didn't mean remove it. I just meant that they should be moved to a how-to article about troubleshooting the checks.  In my mind, the API documentation should be about the kind of API inputs and response you will get.  Everything else should go to how-to article by default.  More specifically, the check error code are not something you see when calling the API.  They are something you see through the content of the notifications (email, sms, etc.) It seems that the error codes are more suited to be in a how-to article titled "How to troubleshoot upon remote check alerts"

The zones in API section is not updated. Don't worry about that. I can update them down the road.
