### ISSUE TITLE
How-to article for DevOps Automation Services - Spheres of Support Linux 

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#533]
On Oct 15, 2015, at 1:41 PM, Jose Plans Jose.Plans@rackspace.co.uk wrote:

Adding Iskandar (who helped with SOS recently) and Charlie (who owns our support)

From: Rob Freeman
Date: Thursday, 15 October 2015 at 13:38
To: Joe Gardiner, David Hendler
Cc: Jose Plans - work
Subject: RE: DevOps spheres of support

Hi Joe,

Sorry for not getting back to you. I’ve discussed this with our team and we’re aligning our Spheres of Support with the AE/DSE team. Responsibilities of each aspect (e.g. installation, configuration etc) will be divided between our teams however this will be seamless from the customers perspective.

As for getting the SoS being public-facing – to be honest, I drew a blank on this. I’ve looked at our knowledge centre [1] where I believe this would be best places, however I cannot seem to find a DevOps section where this could be placed.

To help us progress, I’ve looped in David Hendler to ask for his advice on how we can get a summarised version of our wiki page [2] on the Knowledge Centre so we can make it public and continue to keep it updated.
@David, your help here will be greatly appreciated

Many thanks
Rob

Side-note: During my researching I did find this blog post: http://blog.rackspace.com/get-to-know-the-devops-tools-supported-by-rackspace-specialists/ which is the closest to an actual public SoS – perhaps this can help in the interim? I tried looking up Tarun in the corp directory but his name wasn’t found so I wonder if he’s still a Racker. His LinkedIn says so however I’m considering this a dead-end for now.

[1] http://www.rackspace.com/knowledge_center/
[2] https://one.rackspace.com/display/~jose7294/DevOps+Automation+Services+-+Linux+spheres+of+support

From: Joe Gardiner
Sent: 12 October 2015 09:41
To: Rob Freeman
Cc: Jose Plans
Subject: Re: DevOps spheres of support

Hey Rob,

Sorry to resurrect a dead thread, but did you get anywhere with this?

Thanks,
Joe

On Sep 15, 2015, at 9:30 AM, Joe Gardiner Joe.Gardiner@rackspace.co.uk wrote:

Hi Rob,

Thanks a lot. This will assist with two challenges:

Onboarding
Since other parts of the business have become involved with DevOps customers, we’ve been working through communication and handover challenges. A major pain point is setting customer expectations and keeping that aligned with pre-sales discussions. We believe that having a publicly accessible spheres of support document will reduce internal comms and give the customer something to refer to.

Post production
An ongoing challenge is educating DevOps customers in how to request support from Rackspace. We hope that by providing them with an easily accessible and centrally updated document clearly showing the technologies we support, they will have a more positive experience which will assist the DevOps team in meeting their targets of NPS-r 80, NPS-i 80, NPS-r 55.

Anything to add, Jose?
Joe

From: Rob Freeman
Date: Monday, September 14, 2015 at 2:44 PM
To: Joe Gardiner
Cc: Jose Plans
Subject: RE: DevOps spheres of support

Hi Joe,

Apologies for not getting back to you sooner. I’ll take a look at this this week and get back to you as soon as I can.

Can I ask what the business impact is for this (it may help me prioritise more effectively)?

Many thanks
Rob

From: Joe Gardiner
Date: Tuesday, September 8, 2015 at 5:21 PM
To: Rob Freeman
Cc: Jose Plans
Subject: DevOps spheres of support

Hi Rob,

I rely heavily on the Linux and Windows spheres of support pages in the Knowledge centre to set customer expectations. As I work on more DevOps accounts I’m struggling to explain what we support as part of the service. Jose shared his SOS doc with me (https://one.rackspace.com/pages/viewpage.action?title=DevOps+Automation+Services+-+Linux+spheres+of+support&spaceKey=~jose7294) which is really helpful, but it would be good if we could put this in the Knowledge centre alongside the other SOS docs so that it’s public facing.

Is this something you can help with?

Thanks,

Joe

**Comment by DonNateR** [comment]
From: Stephen Waller
Sent: Friday, November 20, 2015 11:52 AM
To: David Hendler david.hendler@RACKSPACE.COM; Ryan Stark rstark@rackspace.com
Subject: Linux Spheres of Support

Hi There

I’m dropping you a line as you are the authors/owners of the following SoS documents:

· http://www.rackspace.com/knowledge_center/article/cloud-servers-with-managed-operations-support-for-linux

· https://one.rackspace.com/pages/viewpage.action?title=Linux+Spheres+of+Support+-+Global&spaceKey=Linux

I was just wondering if there is a plan or even a desire to combine the 2 and have one unified SOS document across both dedicated and cloud?

Kind regards

Stephen

______________________________

This has been something we have looked at a few times, however, because of the requirements that have been established for Support of technologies on dedicated equipment varies from the requirements for something to be supported on a Cloud platform, there will always be inconsistency.

i.e. For an OS to be supported on Dedicated it must have interoperability with all the dedicated hardware we sell such as servers, storage, and backup. While for an OS to be Supported in Cloud, we just need a majority of the Support Techs to have sufficient knowledge to answer the majority of customer questions and for the OS to have a working image.

For other technologies that are not hardware dependent, it is simply a matter of having a sufficient amount of the Support floor appropriately trained and able to support the technology. (I.e. Percona is not Supported in Managed Operations but is in Dedicated)

Thank you.

Dusty Simoni
Product Manager - Cloud Service Levels

**Comment by stephamon** [comment]
I think based on Dusty's response in November, the consensus is not to touch the Dedicated SOS, and the need for an article based on the non-Dedicated SOS seems to be kind of uncertain. I'm closing this one out and we can readdress it if it comes up again.
