### ISSUE TITLE
Annotation article for Rackspace Metrics is still missing

### ISSUE THREAD

**Issue by wolfdancer** [rackerlabs/rackspace-how-to#555]
The link to "Use annotation metrics" is not working in this article: https://support.rackspace.com/how-to/create-a-grafana-dashboard-for-rackspace-metrics/

I tried to fix it through this PR but maybe I didn't understand how this works? 

* https://github.com/rackerlabs/rackspace-how-to/pull/552

**Comment by stephamon** [comment]
@wolfdancer It looks like the "Use annotation metrics" article wasn't published properly. The metadata has some errors in it. I'll fix and publish, so as soon as it is live, the link should be working.

**Comment by stephamon** [comment]
@wolfdancer this appears to be working now :)

**Comment by wolfdancer** [comment]
@stephamon thanks!
