### ISSUE TITLE
Reconcile images between Cloud Files and GitHub

### ISSUE THREAD

**Issue by kenperkins** [rackerlabs/rackspace-how-to#560]
We need to figure out if we can reconcile the images from Cloud Files into this repository and switching to a jekyll-preparer or if we need to keep the system as is. I know @ktbartholomew has done some looking at this.

**Comment by ktbartholomew** [comment]
@kenperkins I just opened #561 which is (almost) all it would take to use the jekyll preparer. We would still need to do just a little config-wrangling to make sure everything is getting published correctly.
