### ISSUE TITLE
NTP Article does not cover disabling monitor for avoiding relfection attacks

### ISSUE THREAD

**Issue by richardforth** [rackerlabs/rackspace-how-to#589]
https://support.rackspace.com/how-to/using-ntp-to-sync-time/

This article should at least have a section on NTP Security in relation to NTP Reflection attacks

https://isc.sans.edu/forums/diary/NTP+reflection+attack/17300/

Kind Regards Richard

**Comment by DonNateR** [comment]
Completed.
