### ISSUE TITLE
Build out the Dedicated section of the How-To site

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#597]
1. JP and his team are reviewing our current Dedicated articles and will give us guidance on where they should be located.
2. Work with JP and his team to create a new Dedicated section of the How To.
3. Have JP and his team build out a list of needed articles for Dedicated (could repurpose existing Wiki content).

**Comment by ReneeRendon** [comment]
This is the Process and Outreach portion:
1. Train selected SMEs from Dedicated support on how to contribute to the How To
2. Monitor and engage with the team on creating the content.

**Comment by kylelaffoon** [comment]
List of current related How To articles for Dedicated are at https://docs.google.com/a/gapps.rackspace.com/spreadsheets/d/1GEd-UHWEQUIBgOBg7-qHWSz-ecnuoaKmW3-XTxgaXHs/edit?usp=sharing

**Comment by kylelaffoon** [comment]
Met with Dedicated team on 3/25/2016. They are discussing needed topics and development of these with leadership for sign off and allocation. Following this, they will assemble a list of needed articles and assign to agents as part of period goals. Each article will undergo a peer review before submission to the How To team.

**Comment by ReneeRendon** [comment]
Dedicated folks are not ready yet.

**Comment by stephamon** [comment]
Meeting with Dedicated team today (8/23) to discuss content needs.

**Comment by DonNateR** [comment]
Waiting for direction from SLT

**Comment by stephamon** [comment]
Done and done!
