### ISSUE TITLE
Update Cloud Files FAQ to include eventual consistency piece

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/rackspace-how-to#631]
from Matt Barker.

Hey Catherine,

Hope you're doing well. I have had a request from support to have an explanation of 'eventual consistency' for Cloud Files available to customers. I have created the text, and as I know that we've now moved to more of a self-serve model, I'm checking with you on how to do this (sorry I'm sure that you have explained it to me before :)

This is the text by the way:

Cloud Files Eventual Consistency
One of the key characteristics of Cloud Files is that it is "eventually consistent".  In computing, the CAP theorem states that distributed systems must choose two out of consistency, availability, and tolerating network failure. For example, a system can be consistent (i.e. all reads get the most current data) and handle network failures, but it must sacrifice availability to do so. Or a system can choose to handle network failures and have perfect availability, but it must sacrifice consistency to do so. Distributed systems must always handle network failures, so they must choose to sacrifice either availability or consistency.

Storage systems become distributed as they grow. OpenStack Swift (the basis for Rackspace’s Cloud Files product) chooses to sacrifice consistency for availability and network failure tolerance. This choice allows the system to scale to enormous levels and provide massive uptime, but it also means that in certain scenarios, some data may not be updated throughout the entire system. For example, a container listing may not be up-to-date immediately after writing an object. Swift will queue the container listing update and allow the object write to succeed. This sort of consistency model is called “eventual consistency”.
​
Thanks,

- Matt

Matthew Barker
Product Manager - Rackspace
cell: 210.286.0453
matthew.barker@rackspace.com

**Comment by DonNateR** [comment]
Addressed by Catherine. Closing issue
