### ISSUE TITLE
Remove references of ‘Managed Operations: DevOps’ service level

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#640]
In regards to the related articles I can see that the following articles still reference the ‘Managed Operations: DevOps’ service level which as far as I’m aware is no longer on offer:
 
https://support.rackspace.com/how-to/upgrade-to-managed-operations-service-level/
https://support.rackspace.com/how-to/managed-cloud-service-levels-faq/
 
Thank you,
Kostas

**Comment by kylelaffoon** [comment]
Created PRs 665 and 666 for this adjustment.
