### ISSUE TITLE
Delete "VMware vRealize Operations 6.1 Permissions List" KC Article

### ISSUE THREAD

**Issue by bhpurswell** [rackerlabs/rackspace-how-to#650]
The article "VMware vRealize Operations 6.1 Permissions List" (rackspace-how-to/content/managed-vmware-services/vmware-vrealize-operations-61-permissions-list.md) contains an outdated version of information already in the vCenter and vCloud manuals (https://developer.rackspace.com/docs/private-cloud/dedicated-vcloud/vcenter-handbook/common/vmware-vrealize-permissions-list/ and https://developer.rackspace.com/docs/private-cloud/dedicated-vcloud/vcloud-handbook-v1.5/common/vmware-vrealize-permissions-list/). Suggest deleting KC article to prevent data duplication and having to maintain data in two locations.

**Comment by stephamon** [comment]
@bhpurswell thanks! I'll take care of it
