### ISSUE TITLE
Create a "how to install and configure rack" article

### ISSUE THREAD

**Issue by kenperkins** [rackerlabs/rackspace-how-to#672]
I think we need a how-to on setting up and configuring `rack`, which can then be referenced in any article mentioning `rack`. I'd love to start removing references to `novaclient` and `supernova` etc, for `rack`, but we need to be able to tell people how to configure it before we dive into using it.

**Comment by kmsholcomb** [comment]
Hi @kenperkins. Do you mean the rack CLI? If so, there *is* documentation for it, at https://developer.rackspace.com/docs/rack-cli/. Could we reuse/repurpose/refer to that? Or do you mean something completely different?

**Comment by kenperkins** [comment]
Perhaps you're right: we should be linking to: https://developer.rackspace.com/docs/rack-cli/configuration/#installation-and-configuration

**Comment by kmsholcomb** [comment]
If we are going to start linking to it, I will ping the writers about applying the edits that I have done on the content. Thanks!
