### ISSUE TITLE
Link in wrong place in How To

### ISSUE THREAD

**Issue by mushakov** [rackerlabs/rackspace-how-to#674]
Article says:

"Some users are used to taking snapshots of their Cloud Server product page as a backup. "

Instead of saying "product page" we should link to the product page in "Cloud Servers"

https://support.rackspace.com/how-to/rackspace-cloud-backup-vs-cloud-server-image-backups/

**Comment by kylelaffoon** [comment]
Fixed this issue.

**Comment by kylelaffoon** [comment]
Moved link as outlined.
