### ISSUE TITLE
Rackspace Cloud Big Data article's returning "system error".

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#678]
The following link, and all Big Data articles, return a system error.

https://support.rackspace.com/how-to/getting-data-into-your-big-data-cluster/

**Comment by ktbartholomew** [comment]
Looks like this originated (more or less) with this change: https://github.com/rackerlabs/rackspace-how-to/commit/1fa1a10095c61597d2cbeb7cd788d75c138cbccc

The permalink frontmatter value was changed from `getting-data`... to `transfer-data`... which changes the URL from which the page is accessed. (Ideally, the filename should be changed to match the permalink value, just to make things easy to find).

If there are external sources linking to `/how-to/getting-data-into-your-big-data-cluster/` then I'd recommend changing the permalink field of this article back to that. The inertia of external links is not something to take lightly!

**Comment by stephamon** [comment]
I'll fix it. I was under the impression that the permalinks weren't being used yet, so there are a couple that need to be changed back.

**Comment by ktbartholomew** [comment]
@stephamon you were right at the time the change was made. Now that the how-to site is powered by Jekyll, the `permalink` value in the frontmatter is _the_ source of truth for an article's URL. Sorry for not being clear about this earlier...I didn't think my changes would be ready so soon!

**Comment by stephamon** [comment]
@ktbartholomew not a problem! So does that mean that filenames can be changed without breaking anything now?

**Comment by ktbartholomew** [comment]
For the most part yes, but I think filenames should match the permalink value as closely as possible so things are easy to find.
