### ISSUE TITLE
Missing article - linux cloud server security

### ISSUE THREAD

**Issue by meker12** [rackerlabs/rackspace-how-to#684]
Hello,

I get a 404 error when going to: https://support.rackspace.com/knowledge_center/article/linux-cloud-server-security-best-practices/ 

Can you check into it, please?

Thanks!
-Maeve

**Comment by kylelaffoon** [comment]
@meker12 This article was marked to not migrate originally. I am importing the content to https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-servers/linux-cloud-server-security-best-practices.md today.

**Comment by meker12** [comment]
I think you still need to add a permalink to the article. It's not showing up at the URL, unless maybe the build is slow.

**Comment by kylelaffoon** [comment]
https://support.rackspace.com/how-to/linux-server-security-best-practices/ c'est fini

**Comment by kylelaffoon** [comment]
This is the permalink listed in the article: linux-server-security-best-practices/

It's working this morning at https://support.rackspace.com/how-to/linux-server-security-best-practices/. There was a long delay yesterday, though.
