### ISSUE TITLE
Content edit and image pruning

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-how-to#705]
The whole content repository should be walked through to edit for style and content, and to be more discerning when using images.

Claim a product if you want to start going through content, and check it off as you go.

**Note:** Cloud Office is undergoing a separate review.

- [x] Cloud Backup (@stephamon)
- [x] Cloud Big Data (@kylelaffoon) 
- [x] Cloud Block Storage (@DonNateR)
- [x] Cloud Databases (@kylelaffoon)
- [x] Cloud DNS (@stephamon)
- [x] Cloud Files (@stephamon)
- [x] Cloud Images (@stephamon)
- [x] Cloud Load Balancers (@stephamon)
- [x] Cloud Networks (@kylelaffoon) *Vyatta articles on hold*
- [x] Cloud Orchestration(@stephamon)
- [x] Cloud Queues (@stephamon)
- [x] Cloud Servers (@stephamon)
- [x] Cloud Sites (@kylelaffoon)
- [x] General (@kmsholcomb)
- [x] Managed Operations (@DonNateR)
- [x] Managed VMWare Services (@DonNateR)
- [x] RackConnect (@kmsholcomb)
- [x] Rackspace Auto Scale (@stephamon)
- [x] Rackspace CDN (@stephamon)
- [x] Rackspace Intelligence (@stephamon)
- [x] Rackspace Metrics (@stephamon)
- [x] Rackspace Monitoring (@stephamon)
- [x] RPC - Microsoft (@kylelaffoon)
- [x] RPC - OpenStack (@kylelaffoon)

**Comment by kmsholcomb** [comment]
As a reminder, the style guide is now posted in GitHub at https://github.com/rackerlabs/docs-rackspace/tree/master/style-guide. If you want editorial feedback on any articles you review, please just let me know.

**Comment by kmsholcomb** [comment]
Hm. @kylelaffoon. I think that this issue should stay open until all of the products are done, yes?

**Comment by kylelaffoon** [comment]
@kmsholcomb Thanks. I thought I was just closing the branch for the one PR, not the whole ticket.

**Comment by stephamon** [comment]
Putting Networks on hold until I hear back from the Vyatta team.

**Comment by kylelaffoon** [comment]
None of the Cloud Servers "T" articles had images.

**Comment by stephamon** [comment]
Finally done!

**Comment by kylelaffoon** [comment]
Great job on oversee on this one, @stephamon! It was a monster.
