### ISSUE TITLE
Ninja support schedule

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#718]
**How-To ninja support schedule **
For more information see: https://one.rackspace.com/display/devdoc/How-To+support+ninja

April 4 - 8: Laura
April 11 - 15: Renée
April 18 - 22: Nate
April 25 - 29: Kyle
May 2 - 6: Renée
May 9 - 13: Stephanie

May 16 - 20: Kyle
May 23 - 27: Nate
May 30 - June 2: Renée
June 6 - 10: Stephanie
June 13 - 17: Kyle
June 20 - 24: Nate
June 27 - July 1: Renée

**Comment by stephamon** [comment]
@ReneeRendon are we back to volunteering?

**Comment by lauracly** [comment]
I think @ReneeRendon should assign weeks to everyone across the org. Then people can swap if there are conflicts/issues.
