### ISSUE TITLE
Update and clarify Cloud Backup Troubleshooting article

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-how-to#726]
https://support.rackspace.com/how-to/cloud-backup-troubleshooting/ is in need of some reorganization and clarification.

@kmsholcomb would you upload your edits to the issue thread?

**Comment by kmsholcomb** [comment]
Sure.  
[Cloud Backup troubleshooting_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/206850/Cloud.Backup.troubleshooting_editsKH.pdf)
[Cloud Backup troubleshooting_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/206851/Cloud.Backup.troubleshooting_editsKH.docx)
