### ISSUE TITLE
Markdown cheatsheet

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#738]
Prepare a markdown cheatsheet in the repo. 
Link to it from this wiki page. https://one.rackspace.com/display/devdoc/How-To+team+processes

**Comment by kmsholcomb** [comment]
The CONTRIBUTING.md file points to this cheat sheet: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet. Are we trying to replicate something like this? Or are we just documenting How-To specific things? Well, regardless, revise the CONTRIBUTING file as needed after you create the cheat sheet (I'm sure you were planning on it).

**Comment by ReneeRendon** [comment]
Oh, I didn't notice that before. Now it clearly jumps out at me. Thanks for pointing that out @kmsholcomb.  We'll look thru it and see if there is anything missing that specifically pertains to the How-To that we might want to document.

**Comment by kmsholcomb** [comment]
Note that the link in the CONTRIBUTING.md file points to the "Lists" section because it is so hard to create lists right! I'm not sure if the whole rest of that cheat sheet is relevant (although I'm sure it's pretty close, Markdown being as simple as it is). Anyway.

**Comment by DonNateR** [comment]
Let's see how the adam-p markdown cheatsheet works for our contribution class students. If the students dictate a need for a How-to specific version, we'll make a cheatsheet then.
