### ISSUE TITLE
Update article about Reverting from Rescue Mode

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#756]
From: Christophe Bonard <christophe.bonard@rackspace.com>
Date: Wednesday, April 13, 2016 at 12:09 PM
To: "how-to@rackspace.com" <How-To@rackspace.com>
Subject: publish public facing document for a cloud process

Hello,
 
I have created a Wiki page for a cloud process and would like to know how to have this public facing.
 
https://one.rackspace.com/pages/viewpage.action?pageId=163909472
 
I have had several techs test this successfully.
 
the current page does not work and is not very clear
https://support.rackspace.com/how-to/rescue-mode-on-windows-servers/
 
Thank you,
Christophe Bonard
UK AH 2nd shift SMB Windows support L4

**Comment by kylelaffoon** [comment]
This update is complete.

**Comment by kylelaffoon** [comment]
@kmsholcomb is editing this article.

**Comment by kmsholcomb** [comment]
Hi @kylelaffoon: The attached Word doc (and the PDF copy of it) contains my suggested edits. Please let me know if you have any questions. Thanks!

[Rescue Mode on Windows Cloud Servers_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/226862/Rescue.Mode.on.Windows.Cloud.Servers_editsKH.pdf)
[Rescue Mode on Windows Cloud Servers_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/226863/Rescue.Mode.on.Windows.Cloud.Servers_editsKH.docx)

**Comment by kylelaffoon** [comment]
Applied edits and opened PR https://github.com/rackerlabs/rackspace-how-to/pull/808. Will post on Slack when build completed.

**Comment by kylelaffoon** [comment]
Refined applied edits further.
