### ISSUE TITLE
Cloud Servers CLI audit 

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#769]
**Audit Cloud Servers for articles that have command line instructions. **
Record the article title and the CLI used in the article on the spreadsheet that's located here: https://docs.google.com/spreadsheets/d/14N5sE9mijlgDtdvqMse-aA6VNji6Car1t7K1Joi2YDs/edit#gid=0

Ken's team will use this information to improve the Rack CLI and to help us improve our articles.

**Comment by ReneeRendon** [comment]
Cat is working on this while she edits the titles on issue #416.

**Comment by ReneeRendon** [comment]
@catlook Please create an issue for each article.
https://github.com/rackerlabs/rackspace-how-to/issues/885

**Comment by catlook** [comment]
issues are created for Ken.
