### ISSUE TITLE
New CP landing page rolled out

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/rackspace-how-to#770]
The Control Panel landing page has gotten a major update, so we'll need to crawl through the repo and update screenshots.

**Comment by kmsholcomb** [comment]
Or delete them!

Also, some tasks that include information such as "The Cloud Servers page opens by default" when you log in to the CP need to be revised. https://support.rackspace.com/how-to/create-a-cloud-server/ is an example.

**Comment by ReneeRendon** [comment]
Link to spreadsheet to keep track of what we've already combed through.
https://docs.google.com/spreadsheets/d/1ML8PRUTT3asvdU8vSwbBVHM9wOPztN2GAEDnB4OlJ_w/edit?usp=sharing
