### ISSUE TITLE
Missing image in Cloud Load Balancers FAQ

### ISSUE THREAD

**Issue by kruzda** [rackerlabs/rackspace-how-to#780]
The Cloud Load Balancer FAQ has a section that refers to an image that is not in this repository and is not displayed.

https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-load-balancers/cloud-load-balancers-faq.md#what-are-the-security-concerns-with-ssl-termination

The reference is at the end of that section:

unencrypted traffic to within the data center's network, as illustrated
in the following diagram.

(sslterminationsFAQpic.png)

**Comment by kylelaffoon** [comment]
The image is not among the "everything - KC" historical files. Removed image ref and text referring to it.

**Comment by kylelaffoon** [comment]
@cyrichardson  merged this PR.

**Comment by kylelaffoon** [comment]
@kmsholcomb is editing this article.
