### ISSUE TITLE
2016 Update needed for Exchange 2013 article

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#809]
Submitted by Isidro Perez:

Hey Team,

Hope this message finds you well! I wanted to reach out for some help on the following two support Articles, please see below:

https://support.rackspace.com/how-to/public-folders-availability-for-hosted-exchange-2013/
https://support.rackspace.com/how-to/manage-public-folders-in-the-control-panel-for-hosted-exchange-2013/

Desired Result:
Both of these support articles are currently written to address Exchange type mailboxes on our Hosted Exchange environment 2013.  After review, these can be updated to include our Hosted Exchange 2016 environment as well.
I have confirmed that the content listed on both articles is still valid and applies to both Exchange environments  so no content needs to be edited, only updated to include Exchange 2016.  

I am not sure of the proper  way to update the Articles to show it applies to both environments   i.e.  2013/2016  etc..     I would like to work with you on these to get them updated. If any further information is needed, please let me know.

Best,
Isidro

**Comment by ReneeRendon** [comment]
Fixed with PRs #815 and #816.
