### ISSUE TITLE
Fix Cloud Big Data RBAC v2 matrix

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#820]
-Cloud Big Data RBAC permissions matrix needs to be reworked. 
-Remove the ampersands.

I redid the matrix to match the Cloud Servers RBAC table, but it still didn't display correctly in the preview. I've attached the file with the "&'s" removed and the table reworked. 

https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-big-data/detailed-permissions-matrix-for-cloud-big-data-v2.md

[BigDataRBAC.txt](https://github.com/rackerlabs/rackspace-how-to/files/243030/BigDataRBAC.txt)

**Comment by ReneeRendon** [comment]
Fixed with #822

**Comment by DonNateR** [comment]
@ReneeRendon: Close this issue or leave it open?

**Comment by ReneeRendon** [comment]
fixed with PR #822
