### ISSUE TITLE
Improve Windows Bootstrap Documentation

### ISSUE THREAD

**Issue by catlook** [rackerlabs/rackspace-how-to#832]
I got a uservoice message forwarded from Laura, with the text below.  I don't have access so I can't provide additional info, or even a reference number.  If we take this on, it belongs in an H2 article rather than in an API doc, I think.

Improve the documentation on Windows bootstrapping
Posted in Cloud Servers » Feature Request

There is no information in the documentation on using bootstrap.cmd to bootstrap new Windows instances. The only place it is mentioned is in a blog post about installing chef on Windows. Also include how to control when it is run through the registry.  - Anonymous

**Comment by kylelaffoon** [comment]
Windows and Chef have documentation on this. This article is not needed in the how to.
