### ISSUE TITLE
Duplicate title tags

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#837]
The following items show up as having duplicate title tags in the Google Search Console. 

Pages with duplicate title tags	Pages
NUMA, VNUMA and CPU Scheduling
/how-to/numa-vnuma-and-cpu-scheduling/
/white-paper/numa-vnuma-and-cpu-scheduling/
2

Systems Management, Simplified in the Cloud
/how-to/systems-management-simplified-in-the-cloud/
/white-paper/systems-management-simplified-in-the-cloud-0/
/white-paper/systems-management-simplified-in-the-cloud/
3

Generate your encrypted key in Cloud Backup
/how-to/generate-your-encrypted-key-in-cloud-backup/
/how-to/generating-your-encrypted-key-in-cloud-backup/
2

Getting started with Cloud Files and CDN
/how-to/getting-started-with-cloud-files-and-cdn-0/
/how-to/getting-started-with-cloud-files-and-cdn/
2

**Comment by kylelaffoon** [comment]
Added redirects for unneeded items.
