### ISSUE TITLE
Article needs content or needs to be removed

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#838]
https://support.rackspace.com/how-to/rackspace-private-cloud-backup-and-recovery/

**Comment by kylelaffoon** [comment]
Reached out to Karin Levenstein to see if content is currently available or if this may have been a migration issue.

**Comment by kylelaffoon** [comment]
Karin confirmed this placeholder is no longer needed. Deleted article draft and redirected url to support.rackspace.com/how-to/rpc-openstack/.
