### ISSUE TITLE
In migration article, document how to remove load balancer

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#842]
UserVoice suggestion from here: https://feedback.rackspace.com/admin/v3/suggestions/13719234/activity

In this article, you have the user set up a load balancer in order to migrate from 1st gen to 2nd gen:
At the end of the article, you should have instructions for getting rid of the load balancer.

https://support.rackspace.com/how-to/migrate-a-first-generation-server-to-a-next-generation-server-with-minimal-downtime/

**Comment by kylelaffoon** [comment]
@kmsholcomb Ready for your review.

**Comment by kmsholcomb** [comment]
I will send you comments later today, @kylelaffoon.

**Comment by kylelaffoon** [comment]
Reached out to Thomas Duesing for article validation/audit and with questions on when customers are done using the load balancer and on the synchronization item at the end.

**Comment by kylelaffoon** [comment]
Thomas is checking with Trey Hoehne to see if this article is still needed.

**Comment by kylelaffoon** [comment]
Applied Trey Hoehne's direction in PR1009.
