### ISSUE TITLE
New articles are not searchable on the How-To site

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#844]
New articles are not appearing in the search results on the How-To site.

As a test, we can see how long it takes this to appear in the search results. This was merged May 3rd (afternoon).

https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-databases/Replicate-backup-for-disaster-recovery-with-cloud-databases.md

**Comment by ReneeRendon** [comment]
This article is not showing in search results yet. We'll continue to monitor and see how we can improve this.

**Comment by ReneeRendon** [comment]
This article is not showing in search results yet. We'll continue to monitor and see how we can improve this.

**Comment by ReneeRendon** [comment]
Noticed that the file name started with uppercase. Lowercased it today to see if that changes the search results.

**Comment by ReneeRendon** [comment]
Still not appearing in the search results.

**Comment by ReneeRendon** [comment]
Still not appearing in the search results.

**Comment by ReneeRendon** [comment]
Still not appearing in the search results.

**Comment by kylelaffoon** [comment]
As of this morning, the Replicate backups for disaster recovery with Cloud Databases article (published May 3rd) shows up in the How-To search function and is found in Google.

**Comment by ReneeRendon** [comment]
I'm closing this issue and creating a new one for submitting a sitemap for the support site.
