### ISSUE TITLE
Apache install command incorrect.

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#849]
From an email by Angela Boulinea:

Hi team!

I'm hoping I reached the correct team in regards to page:

https://support.rackspace.com/how-to/centos-6-apache-and-php-install/

One of our customers found the php primary package is missing in the following line (near the bottom of the page) when installing for themselves:

sudo yum install php-mysql php-devel php-gd php-pecl-memcache php-pspell php-snmp php-xmlrpc php-xml

Should read:

sudo yum install php php-mysql php-devel php-gd php-pecl-memcache php-pspell php-snmp php-xmlrpc php-xml

**Comment by DonNateR** [comment]
Emailed Angela back. Change needs to be technically verified before it can be made.

**Comment by stephamon** [comment]
@DonNateR have you heard back about the missing `php` in the command?

**Comment by DonNateR** [comment]
@stephamon: Yes, she confirmed the need for the command changed. I confirmed the command worked. I took the liberty of making the change.
