### ISSUE TITLE
Create Floating IP subsection of Network FAQ

### ISSUE THREAD

**Issue by catlook** [rackerlabs/rackspace-how-to#872]
Here is basic content: https://one.rackspace.com/pages/viewpage.action?title=Floating+IP+EA+FAQ&spaceKey=compute#FloatingIPEAFAQ-Limitations

Touch base with Jorge Miramontes on June 1st to make sure everything is good to go.
Go-live is scheduled for June 6th.

**Comment by catlook** [comment]
@stephamon  Here it is!

**Comment by kylelaffoon** [comment]
@kmsholcomb I have PR 976 (https://github.com/rackerlabs/rackspace-how-to/pull/976) for this curently. I will incorporate your edits in this concurrent to launching for Jorge's timeline.

**Comment by kmsholcomb** [comment]
Sounds good, @kylelaffoon

**Comment by kylelaffoon** [comment]
From Cat: this from Jorge:  the latest we will launch floating ip is june 21st for ea.
so..maybe not the 6th after all 

Removing EA steps until launch.

**Comment by kylelaffoon** [comment]
Cut new FAQ items out of Cloud Netowrks FAQ and saved to add back for launch.

**Comment by kylelaffoon** [comment]
Checked back on this for possible 6/21 launch. Will need to wait until at least 6/26. Setting calendar reminders.
