### ISSUE TITLE
Edits for "Use Cloud Databases with Cloud Sites"

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/rackspace-how-to#946]
Hi @kylelaffoon. My edits for the article are attached (Word doc and PDF copy of it). I created an issue because https://github.com/rackerlabs/rackspace-how-to/pull/901 was already merged. I suppose you can create a new PR! Please let me know if you have any questions. Thanks!  

[Use Cloud Databases with your Cloud Site_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/271202/Use.Cloud.Databases.with.your.Cloud.Site_editsKH.docx)
[Use Cloud Databases with your Cloud Site_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/271203/Use.Cloud.Databases.with.your.Cloud.Site_editsKH.pdf)

**Comment by kylelaffoon** [comment]
Applied all edits.
