### ISSUE TITLE
First to next gen migration article has wrong script

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#956]
Howdy KC Folks! 

We have a and script in the following article: 

https://support.rackspace.com/how-to/first-gen-to-next-gen-cloud-servers-migration-pre-checks/

Specifically the script in the "PV Driver Check" section: 

 sudo curl http://437117ba0e2524fdae22-6a87f3acbfcde81a104bb18fbb8cb85f.r47.cf2.rackcdn.com/xen_tools_installer.sh | bash

It currently will error with the following output: 

https://gist.github.rackspace.com/rees4065/33e5a0b15709f263e483

Can y'all please work with the racker or team that created the script to have it updated or pulled down till it is working.

Thanks
Reese

**Comment by DonNateR** [comment]
Reached out to Luke Repko to receive technical verification.

**Comment by DonNateR** [comment]
Hello Everyone,

Just wanted to make sure everyone knows for the record, I didn't write this script but I believe I found the problem. The ./install script for the PV drivers is being run without the, "-n" (non-interactive) flag so when the next line in the script is reached, "rm -rf Linux/" it's trying each letter consecutively until it gets to the N in Linux at which point it aborts because "n" for the install script means no, don't proceed. I am going to work on updating the script in place where it resides so nothing will need to be changed in the KC article. I will report back once this has been taken care of.  

*example*

Invalid response `r'

Invalid response `m'

Invalid response `'

Invalid response `-'

Invalid response `r'

Invalid response `f'

Invalid response `'

Invalid response `L'

Invalid response `i'

Aborting.

Fanatically Yours,

Luke Repko
Cloud Virtualization Engineer

**Comment by LukeRepko** [comment]
This has been resolved, and the script is working as intended.
