### ISSUE TITLE
Add new Tiered Configurations article

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#960]
The article attached in this word doc needs to be published ASAP.
The diagram also needs to be updated to conform to our visualization standards.

[SSNLB Doc_v2[1].docx](https://github.com/rackerlabs/rackspace-how-to/files/279887/SSNLB.Doc_v2.1.docx)

**Comment by mushakov** [comment]
Thanks so much for the help with this. I see that the article was merged. Can you let me know what the url for it will be and when it'll go live?

**Comment by DonNateR** [comment]
@mushakov: https://support.rackspace.com/how-to/tiered-configuration-using-cloud-load-balancers
