### ISSUE TITLE
Retire Article forced-ma-routing/

### ISSUE THREAD

**Issue by beau-bailey** [rackerlabs/rackspace-how-to#966]
Hey team,

Can we have article https://support.rackspace.com/how-to/forced-ma-routing/ retired. This is no longer a functionality with in our system because of infrastructure changes that have been made. Ultimately, MX routing is forced at all times now, which is an industry standard. We worked through notifying customers of these changes through other channels prior to the change. I do not believe we need an article to cover the current behavior as it is a standard. 

Let me know if you have any questions. Thanks!

**Comment by stephamon** [comment]
Thanks @beau-bailey I'm on it!
