### ISSUE TITLE
Broken links for Rackspace metrics

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/rackspace-how-to#993]
Under "Rackspace Metrics – All Articles", the last 2 items listed:

o   Use annotation metrics
o   Use Enum metrics

Open with:
"Page Not Found

Sorry, we couldn't find the page you were looking for. The page may have moved or been deleted. You can also search our community forum."

**Comment by stephamon** [comment]
If you hover over the two articles, the link that shows up is:

https://support.rackspace.com/how-to//:basename/

**Comment by meker12** [comment]
Missing permalink field. Fixed by PR #1004
